Flexget/Flexget

flexget/plugins/plugin_transmission.py
Try to fix bug #2804 by making RPC client object re-initiated for every task rather then doing it once for whole plugin.
=> Update plugin_transmission.py to fix bug #2804

flexget/plugins/output/subtitles_subliminal.py
Subliminal plugin would throw an exception when trying to download subtitles for movies as the movie object does not have the `series` attribute.
=> fixed attribute error when downloading subtitles for movies

flexget/manager.py, flexget/plugins/api_tvrage.py, flexget/plugins/filter/remember_rejected.py, flexget/plugins/filter/seen.py, flexget/plugins/filter/series.py, flexget/plugins/input/discover.py, flexget/task.py, flexget/utils/cached_input.py, flexget/utils/log.py, flexget/utils/simple_persistence.py
Simple persistence had an issue causing db locks when plugins were calling it while doing their own database read/writes. This branch changes the behavior so that the data is read from the database before a task is run, and written after.
http://flexget.com/ticket/2762
http://flexget.com/ticket/2820
=> Switch simple persistence to load/flush from/to db outside task runs fix #2820, #2672, #2835

flexget/manager.py, flexget/plugin.py
instead of the hardcoded ~/.flexget/plugins. This effectively allows to
put plugins in $XDG_CONFIG_HOME/flexget/plugins.
=> Search for plugins in config_base

flexget/plugins/plugin_configure_series.py
Right now, configure_series will fail the task if one of the inputs fail. Is this the intended behaviour? The discover plugin will simply catch the plugin error exceptions and move on to the next input.
I wanted to hear from you, @gazpachoking, before just pushing random changes that conflict :) I feel it is an inconsistency though.
=> handle pluginerrors in configure_series

flexget/entry.py, flexget/plugins/modify/set_field.py
This changes the set plugin to render entries lazily. This has several advantages:
- We can do the set earlier, so that its fields can be used throughout the filter phase. (also less chance of people needing to use plugin_priority for advanced setups)
- Fields get set on all entries, instead of just accepted ones, so they can be used for filtering (or other plugins that act on non-accepted entries) if desired.
- Less chance of causing lookups that aren't needed, if the fields never get accessed.
- We can now reference other fields set by the set plugin, no matter the order.
@paranoidi Thoughts on this? I think the outcome is awesome, perhaps there are better ways to implement though, or unintended consequences.
=> Refactor set plugin to render templates lazily.

flexget/plugins/input/trakt_emit.py
See example of Trakt.tv json response data from
http://docs.trakt.apiary.io/#reference/users/watched/get-watched
Previous Flexget code was looking for a "type"-attribute that is no longer available in the response.
=> trakt_emit: fixed parsing error for getting show data

flexget/plugins/input/listdir.py
Last pull request had some garbage commits I thought I had removed. Let's try again.
The daemon will check for the existence of folders listed in `listdir`, but if they disappear after the config validation, then the `listdir` plugin will throw an OSError and abort the task (same for non-daemon runs). I haven't really tested my changes but it should work.
Log:
```
2015-01-12 12:00 ERROR    task          Move tvshows    BUG: Unhandled error in plugin configure_series: [Errno 112] Host is down: '/media/network/seagate/staging/tv'
File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 444, in __run_plugin
return method(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
return self.func(*args, …
```
=> handle disappearing folders (eg. samba shares) in listdir

flexget/utils/trakt.py
Right now the trakt error messages do not quite make sense. For instance, 500 error codes are server errors and have nothing to do with authentication. It seems to confuse some people.
=> separate authentication and regular http errors in trakt

bootstrap.py, jenkins-requirements.txt
I hit this bug when trying to run bootstrap on Ubuntu 14.04
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991
It's easily solved by running `sudo pip install setuptools pip --upgrade` to upgrade pip and setuptools in system python.
So maybe you could test on your system before merging.
=> Bootstrap update

flexget/ipc.py
This PR fixes an issue I had with getting Flexget to start on a host running Omnios (Solaris).
***
Starting Flexget with a minimal configuration (or even empty config) resulted in the following error appearing:
```
(flexget-dev)aidan@pez:/export/home/aidan/flexget-dev$ ~/flexget-dev/bin/flexget execute
Could not start manager: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```
The debug output showed that the `sys.defaultencoding` and `sys.getfilesystemencoding` values matched that of a Linux host that was able to start Flexget successfully.
```
2015-02-14 02:15 DEBUG    manager                       sys.defaultencoding: ascii
2015-02-14 02:15 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2015-02-14 02:15 DEBUG    manager …
```
=> use only ascii letters for IPC password generation

flexget/plugins/urlrewrite_eztv.py
Since EZTV has moved away from the .IT domain, its URL has to be updated.
=> Update EZTV URL from .IT to .CH

flexget/plugins/urlrewrite_piratebay.py
Pirate bay discover plugin was failing with the following error:
Error searching with piratebay: RequestException: hostname 'thepiratebay.se' doesn't match either of 'ssl2000.cloudflare.com', 'cloudflare.com', '*.cloudflare.com'
It seems that TPB's HTTPS certificate is not well configured. I just disabled host certificate validation, now it works.
=> Disabled SSL certificate validation to avoid SSLErrors in TPB

flexget/ui/plugins/authentication/authentication.py
Seems like a simple typo. Tested locally. Fixes an issue where using the --username flag with flexget webui would throw an AttributeError.
=> Fix authentication.py typo for webui username.

flexget/plugins/search_kat.py
Both /search and /usearch seem to work, but the site uses the /usearch link...
=> fixed kat search plugin URL

flexget/plugins/plugin_deluge.py, flexget/plugins/plugin_transmission.py
adding a new config key (`main_file_ratio`) to deluge and transmisson plugins so that when using the `main_file_only` config item, you are not forced to assume that the main file must be > 90% of the total torrent size, this ratio is now configurable. This helps a lot with shows that sometimes include samples which are potentially 10-15% of the total size.
I'm getting this PR started early as I want to start the review process right away (since I'm not super familiar with flexget plugins to begin with). I believe I got things right, or close to right at least, but I'm happy to fix style/consistency issues if there are any. I tried to add as little code as possible and keep existing code as unchanged as possible, as a result I may not be doing things the best way possible, but it will be …
=> Main file ratio

flexget/plugins/plugin_deluge.py
this should fix the deluge plugin bug present in the latest 1.2.292 master branch. I don't have a test environment to confirm validity, but I'm fairly certain this was the missing code.
see https://github.com/Flexget/Flexget/pull/460#issuecomment-84051984
=> fixing deluge plugin crash due to main_file_ratio config value not being present

flexget/plugins/plugin_transmission.py
due to the change made in 5a4d092, the change originally made in 089f576 is no longer necessary as the `TransmissionBase.prepare_config` performs an identical `setdefault` call.
=> removing redundant config default setter for main_file_ratio

docs/plugins/flexget.plugins.rst, flexget/plugins/urlrewrite_extratorrent.py
- extratorrent doesn't mesh well with the search_rss plugin as
the data doesn't alway contains a .torrent link (enclosures are often empty)
- Work around this issue by converting the .html link (always present)
into a download link
- Add search plugin to make it easier for anyone else to get started with extratorrent.cc
=> Add search/urlrewrite plugin for extratorrent.cc

flexget/plugins/search_kat.py
Looks like the old code works again. I could have sworn that while
testing the patch, KAT was returning 404 if rss wasn't the first query
parameter. It was late, I may have been seeing things...
=> reverting changes from 761c2f206c... (pull request #453)

flexget/plugins/plugin_transmission.py
This patch addresses [this issue (#2911)](http://flexget.com/ticket/2911) that was posted not too long ago, but was closed prematurely (due to a misunderstanding of the issue I assume).
I have only patched the transmission plugin, I'm unsure if the deluge plugin requires patching but I have no test environment to do any proper QA for a deluge patch. I have just deployed the patched file to my own environment, I should get confirmation if it is working over the next few days.
This patch simply checks for a (_new_) `magnetization_timeout` configuration value (in seconds, defaults to 0, i.e., disabled). If this timeout is set to any number > 0 then the add will poll the transmission RPC client every second (until the timeout elapses) to see if the torrent has been magnetized. Once …
=> Transmission plugin magnetization waiting

flexget/plugins/output/exec.py
Not sure if this is the best approach. Maybe add a new `outputs` plugin similar to `inputs`?
The diff is a bit misleading as I had to indent large blocks, here it is again with `-w`
```diff
diff --git a/flexget/plugins/output/exec.py b/flexget/plugins/output/exec.py
index 7efeda0..b9d04f9 100644
--- a/flexget/plugins/output/exec.py
+++ b/flexget/plugins/output/exec.py
@@ -6,6 +6,7 @@ import subprocess
from flexget import plugin
from flexget.event import event
+from flexget.config_schema import one_or_more
from flexget.utils.template import render_from_entry, render_from_task, RenderError
from flexget.utils.tools import io_encoding
@@ -67,7 +68,7 @@ class PluginExec(object):
schema = {
'oneOf': [
-            {'type': 'string'},
+            one_or_more({'type': 'string'}),
{
'type': …
```
=> Allow list of exec commands

flexget/utils/requests.py
It was clear in the code that the intent was to remove these annoying INFO log messages
> Starting new HTTP connection (1): ...
by setting the log level to WARN `logging.getLogger('requests.packages.urllib3').setLevel(logging.WARNING)`
But it isn't taking any effect in the current release.
I changed the logger name to just `urllib3`, which seems to have corrected the problem. I'm not sure if there are any implications for the change I have made, so any input is welcome in that department.
Sourced my patch from these two StackOverflow questions:
* http://stackoverflow.com/questions/21944445
* https://stackoverflow.com/questions/11029717
=> remove extra urllib3 INFO logging

flexget/plugins/plugin_aria2.py
Small fixex:
1- out option should not be used for torrent files: as per http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-
Using it causes problems to follow torrent files: the torrent file is downloaded and saved with an extension different from ".torrent", which makes aria2 unable to follow the torrent. This small fix correct the behavior.
2- exclude_non_content should exclude file extenstions that are not in the list, not file extentions that are in the list as per the doc. "Whether to exclude "non-content" files; that is, anything that does not have an extension listed in file_exts". This small fix correct the behavior.
=> fix aria2 plugin

flexget/plugins/input/whatcd.py
- Add back the option to use a custom user agent for searching on what.cd.
- Fix small oversight in response handling.
=> Add what.cd user agent option

flexget/plugins/output/history.py
I'd love for history to get a few more options, maybe also a date-range instead of a count-based limit. Ideally, --search should check all (or most) fields and every field should be searchable on its own via dedicated parameter. What do you think?
=> Allow history to be filtered by task

flexget/plugins/search_cpasbien.py
This search plugin does not handle non-ascii titles (fails with error UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position XXX: ordinal not in range(128)). This fix makes sure we encode the title properly to be used in a url search string.
=> fix for titles with non-ascii characters

flexget/plugins/plugin_deluge.py
Fixed http://flexget.com/ticket/2881
Makes sure there is only one top level directory, enabling correct movedone functionality in deluge.
This is accomplished by ensuring the content_filename option doesn't pop the main file / sub file out of folder and also by changing the location of the sparse files (top_torrent_folder/.sparse_files)
=> Fix deluge sparse files/movedone functionality

flexget/plugins/plugin_sftp.py
Previous docstring was full of lies, mistruths and falsehoods.
=> sftp_list: Fix inaccurate docstring

flexget/plugins/plugin_decompress.py
Dangling file handles were causing tests to fail under Windows. This is a fix for: http://flexget.com/ticket/3003
=> Decompress: Close file handles after file is extracted

README.rst
Crate.io shield is broken. They seem to be having issues. Since we're using PyPi, let's see those stats.
=> Better shields

flexget/plugins/modify/path_select.py, tests/test_path_select.py
@gazpachoking I've changed path_select to make it simpler to understand..
-Removed has_free selector as i don't think it's required.
-Added extra test for within
So the config looks like
The follow task will find the path with the most free space by percentage. It will also include other paths within 2% diffeerence of that drive..
So below it will choose both drive1 and drive2 randomly.
```
tasks:
some-task:
path_select:
select: most_free_percent
within: 2%
paths:
- /some/drive1  # 50% free
- /some/drive2  # 51% free
- /some/drive3  # 10% free
```
Same thing goes by size..
The below config will choose paths drive1 and drive2
```
tasks:
some-task:
path_select:
select: most_free
within: 2G
paths:
- /some/drive1  # 50G free
- /some/drive2  # 51G free
- /some/drive3  # 10G Free free
```
=> -Changed config threshold to within as it makes more sens.

flexget/plugins/urlrewrite_extratorrent.py
I am getting errors whilst trying to use the plugin, this should fix it, but I was not able to test further at the moment.
=> Fix incorrectly named global in extratorrent url rewrite plugin

flexget/plugins/input/couchpotato.py, flexget/plugins/input/sickbeard.py, flexget/plugins/input/sonarr.py
should fix the use case where these plugins are not located at the server root path or behind a http proxy
=> enhance url composition in sonarr couchpotato and sickbeard plugins

flexget/plugins/input/letterboxd.py
Creates entries for input from any **public** user list on Letterboxd. The plugin uses BeautifulSoup to parse the list for site-specific metainfo (e.g. user scores, where applicable), extracts the `tmdb_id` and average score from the page of each film included on the list, then queries the TMDb API to fill the rest of the entry.
The plugin is configured with the following settings:
* **`username`**: Your or another user's Letterboxd username, which can be found in the profile URL.
* **`list`**: The name of a custom list, or one of the built-in lists, i.e. `watchlist`, `diary`, `likes`, `rated` or `watched`. It should be entered as it appears in the list URL; so for example, the a list at `http://letterboxd.com/user/list/some-list/` should be entered as `some-list`.
* **`sort_by`** …
=> Add input plugin for Letterboxd lists

flexget/plugins/output/utorrent.py
Paths are now only normalized (lowercased, on case-insensitive
platforms) when checking if directory is allowed, not when passing on
the directory name to uTorrent.
=> Allow for caps in uTorrent destination path

flexget/plugins/urlrewrite_piratebay.py
When using piratebay with 'tv' search, it won't find e.g. 1080p results. Instead, the 'highres tv' section must be used, which is added by this commit.
=> Add "highres tv" to piratebay search plugin

flexget/plugins/urlrewrite_piratebay.py
There is no reason to disable SSL verification.
=> do not skip SSL verification on plugin piratebay

flexget/plugins/plugin_transmission.py
This PR implements the ability to restrict the cleaning of torrents to specific trackers using a regular expression provided to the plugin, like so:
clean_transmission:
tracker: nyaa|animebytes
finished_for: 4 weeks
as to not interfere with non-Flexget managed torrents.
=> support tracker filtering in clean_transmission

flexget/plugins/output/pyload.py
New approach to solve my problem in PR #549.
I restructured the calls to the Pyload API to use the common task.requests object instead of its own instance. "verify_ssl_certificates: no" now gets respected and I can do unverified HTTPS calls to the Pyload API.
=> changed pyload plugin to use common requests session

flexget/plugins/output/move.py
Per conversation in IRC: Change the ‘to’ option in the move plugin to ‘move_to’, and ensure that the plugin is looking in entry for that, not ‘path’.
=> move Plugin: 'to' to 'move_to'

flexget/plugins/input/myepisodes_list.py
This pull request contains the file I've already attached to [trac-ticket #243](http://flexget.com/ticket/243:comment9):
myepisodes_list.py​ contains an input plugin that lists all ever-watched shows from myepisodes.com (all that show up on the "Time I've Wasted" page). The plugin has been based on code from the myepisodes service plugin and other input plugins, so I hope I got the coding style right.
However, I did not abstract any myepisodes api that can be shared between the two plugins, something that should probably be done (but rather by someone with more flexget experience than me).
=> Add input plugin for myepisodes.com show list

flexget/plugins/plugin_sftp.py
The current approach used for handling different path styles in the SFTP doesn't work. Switching to posixpath module to ensure correct remote path handling.
=> plugin_sftp - use correct module for remote path

flexget/plugins/output/notify_xmpp.py
As requested in [#3019](http://flexget.com/ticket/3019), add support to send to multiple recipients. This change will probably need a note on the update log for changing "recipient" to "recipients" in the config.
Also some minor PEP8 cleanup while I was committing.
=> notify_xmpp - Add support for multiple recipients

flexget/plugins/search_freshon.py
Adds a Freshon.tv search plugin.
Supports pagination (limited to 10 pages as users can set their pages to up to 100 items each).
Has a 100% and 50% torrent filter as well as HD and WebDL filters.
Downloads via RSS download link using the users passkey.
Note: throws a SSL error when getting the pages, not sure how to fix that as every recommendation doesn't seem to work including "verify_ssl_certificates: no"
=> Freshontv search plugin

flexget/plugin.py, flexget/plugins/filter/exists.py, flexget/plugins/filter/exists_movie.py, flexget/plugins/filter/exists_series.py, flexget/plugins/input/find.py, flexget/plugins/input/listdir.py
The update to path.py removes the lowercase path alias which flexget relies on
Simply change it to use 'Path' instead of 'path.
http://flexget.com/ticket/3064
=> Bugfix for 'cannot import name path' with path.py 8.0

flexget/plugins/filter/exists.py
Commit dd7d32c4568aaeb871da05a8c2fe354e0dd935e7 missed a reference to the Path module that's causing the exists plugin to crash (http://flexget.com/ticket/3069). This should fix it.
=> Fix incorrect reference to path module in exists plugin

flexget/plugins/modify/regex_extract.py, tests/test_regex_extract.py
This is a new plugin to allow an entry to be updated with the results of a regex over a specified field. This was created to scratch a personal itch of having to post-process Formula 1 from RFM, so with a good enough regex I can parse the title data and make it available for using with deluge ```movedone``` and ```content_filename```:
regex_extract:
prefix: f1_
regex: ^Formula\.?1\.(?P<year>(?:19|20)\d{2})\.Round(?:\.)?(?P<round>\d{1,2})\.(?P<location>[a-zA-Z\.]*?)\.(?P<event>Teds\.(?:Qualifying|Race)\.Notebook|FP[1-3]|Quali(?:fying)?(?:\.Build-Up)?|Race(?:\.Build-Up)?|(?:Drivers\.|Team\.Principals\.)PC|Drivers\.Parade)(?:\.(?P<channel>SkySports(?:F1)?(?:HD)?|BBC(?:(?:One|Two)(?:HD)?)?|Sat\.Feed|ITV(?:HD)?|RTBF(?:HD)?|SkySportHD1|ORTF))?(?:\.(?P<quality>720p|1080(?:i|p)?|DVD|Web-Rip))?(?:\ …
=> regex_extract plugin

flexget/plugins/output/subtitles_subliminal.py
subliminal.download_best_subtitles might return dictionaries with keys but empty values (None or empty lists). In this case, no subtitle was downloaded and the entry should fail.
=> Subliminal should fail if no subs were downloaded

flexget/plugins/search_kat.py
When no result is found, kat return an empty page with a 404 error. This should not be catched as a warning.
=> Let kat handle correctly 404 when no result found

flexget/utils/requests.py
This will make it easier to debug which host is the problem.
=> Add hostname to timeout exception message.

flexget/plugins/plugin_sftp.py
Simple fix for a regression introduced with changes for sftp_upload
=> Fix missing "host" variable which causes sftp_list to crash

flexget/plugins/filter/exists.py
Fix a typo that was merged by accident in 7ce23de951a6ebfe7937f9532d6a86cb1e0ea0a7 and results in:
`BUG: Unhandled error in plugin exists: global name 'Path' is not defined`
=> s/Path/path in plugins/filter/exists.py

flexget/plugins/est_released_series.py
To avoid breakage when calculation last_diff
=> Check if first_seen is null when calculation air date

flexget/webserver.py
Fixes wrong text on cli command for flexget users --help. Instead of 'delete a new user' now shows correct text for passwd command.
=> Fix wrong text on flexget users --help

flexget/ui/gulpfile.js, flexget/ui/sass/flexget.scss
There are two capitalisation typos in the UI build system files which prevent the tools from being used properly, at least on a case-sensitive filesystem.
=> Ui build capitalisation

pavement.py
The newer versions drop the Python2-only BeautifulSoup3 requirement.
=> Require a more recent version of FeedParser

flexget/plugins/input/myepisodes_list.py
myepisodes.com seems to have changed some URLs, and requires a
action=login GET (!) parameter in the URL for a successful login.
The "manage shows" URL used to parse the shows has been changed
as well (albeit the old url still working).
=> myepisodes_list: upgrade to new urls, fixes login

flexget/plugins/input/imdb_list.py
Enable forcing different movie title languages based on LCID language strings. Default is en-us.:
http://www.science.co.il/Language/Locale-codes.asp
This fixes an issue where IMDB would force a language based on default HTML header
=> Fix in imdb_list: Enable forcing movie title languages 

flexget/plugins/search_rarbg.py, flexget/utils/search.py
Some search engines provide scene based releases only (such as rarbg) so searching using actual movies/series names is pointless and won't return anything if it contains special chars.
According to the rules I found online, I added an utils/search function to normalize a string to scene format.
source: https://en.wikipedia.org/wiki/Standard_(warez)#Naming
As an exemple, I use it in search_rarbg input plugin. I guess it can be reused (and maybe useful) for many search plugins (as an option to search only scene releases, etc.)
=> Normalize string according to scene standards

flexget/plugins/input/ftp_list.py, flexget/plugins/output/ftp_download.py
Fix some bugs that broke FTP over TLS as well as bugs that broke ftp_list and ftp_download when file and folder names had special characters. Added better logging in some instances to help diagnose issues. Also fixed a bug where the original coder was incorrectly calling entry.failed(...) instead of entry.fail(...).
=> Fix numerous bugs and issues in FTP over TLS for ftp_list and ftp_download

flexget/plugins/output/ftp_download.py
The option is disabled by default.
The behavior before this change is especially weird if you also enable the delete_origin option since ftp_download will delete the empty directory on the server but not download anything. In other words, it doesn't download anything but does delete it.
=> Add option 'download_empty_dirs' to ftp_download to allow it to download empty directories

flexget/plugins/estimators/est_release_series_tvmaze.py, pavement.py, rtd-requirements.txt
TVMaze estimator for discover plugin
@gazpachoking Currently, some 'print' command are shown on manual series search.
This should be fixed shortly at pytvmaze side, so we can wait with merging this until that is fixed, or add another commit to suppress them.
Edit: let's sit on this for now. I'm working with pytvmaze to do something different and those changes will break behavior. I'll update when this is ready.
EDIT: @gazpachoking this is ready to be merged IMO. worked with pytvmaze dev and now it doesn't have those 'print' and is way more robust.
=> TVMaze estimator

flexget/plugins/output/pushover.py
Fix pushover errors: 
Infinite loop: Inside the while the variable was never updated
Variable not accesible: 
```
Task 'watchlist' was aborted because: BUG: Unhandled error in plugin pushover: global name 'last_request' is not defined
```
=> Fix pushover errores

flexget/plugins/input/trakt_emit.py
Adds *trakt_list* containing the list name the entry originates from. Useful to allow multiple trakt_emit configurations in the same task but specifying per-list configuration with the *if* plugin.
Basically i think it's a more elegant solution than several of the example configs that have separate tasks for each trakt list, each with a different target quality.
Example:
```
sometask:
inputs:
- trakt_emit:
list: Followed Shows
- trakt_emit:
list: Followed 720p  
- trakt_emit:
list: Followed 1080p
set:
quality: sdtv|hdtv <720p h264|xvid !dd5.1
target: sdtv|hdtv <720p h264 !dd5.1
if:
- trakt_list == 'Followed 1080p':
set:
quality: hdtv 1080p h264|xvid !dd5.1
target: hdtv 1080p h264 !dd5.1
- trakt_list == 'Followed 720p':
set:
quality: hdtv 720p h264|xvid !dd5.1
target: hdtv 720p h264 !dd5.1 …
```
=> Adds trakt list entry reference.

flexget/plugins/generic/archive.py
Cleans up titles to remove brackets around years in the same way that *flexget_archive* search does. Causes cli *flexget archive search Blah.Movie.(2015)* to return the same results as using *flexget_archive* in a task.
Also enables tags in *flexget_archive* plugin to match the *archive* command and the example documentation. Before this only *flexget_archive: yes* was implemented and you couldn't filter searches by tags set in the *archive* plugin.
This now works, before it searched the entire archive regardless of specified tags:
```
sometask:
archive: [movies, tv]
searchtask:
discover:
what:
- emit_movie_queue: yes
from:
- flexget_archive: [movies]
```
=> Archive tags

flexget/plugins/input/filesystem.py
Filesystem plugin floods log writing 'Starting to scan folders.' on every run.
=> Make filesystem plugin less verbose

flexget/plugins/input/filesystem.py
Format string was incomplete and therefore the log message lead to another exception.
=> Fix format string for faulty encoding

flexget/plugins/plugin_transmission.py
Previously, including the onlycomplete option would return any torrents that had met the seed ratio/idle limit even if it had not finished downloading.  This fixes that logic to only return torrents who have both finished downloading AND met their seed ratio/idle limit (or are stopped if neither is specified).
=> Fix from_transmission with onlycomplete

flexget/utils/imdb.py
It looks to me that the url field is used as a unique key in the imdb_movies table
depending on how it is scraped its sometimes has a query string referencing where in the search results the link was followed from
this means the same movie can be in the db under multiple urls
http://www.imdb.com/title/tt3311988/
http://www.imdb.com/title/tt3311988/?ref_=nv_sr_1
http://www.imdb.com/title/tt3311988/?ref_=nv_sr_2
etc.
I've had this patch running since 2015-12-17 and have no duplicates in this table
I believe some tables are connected via foreign keys to this table so duplicates here can mean many extra rows in other tables eg imdb_movie_actors
Cheers
mh
=> Duplicate data in imdb_movies table

flexget/plugins/api/movie_queue.py, flexget/plugins/filter/movie_queue.py, flexget/plugins/input/emit_movie_queue.py, flexget/plugins/input/imdb_list.py, tests/test_emit_movie_queue.py, tests/test_movie_queue.py
This enables multiple movie queues.
- Added attribute under `movie_queue` plugin. 
```yaml
movie_queue:
action: add
queue_name: Any Unicode name
```
- Added attribute under `emit_movie_queue` plugin:
```yaml
emit_movie_queue:
queue_name: queue number 2
```
- Added REST API support
- Backwards compatible with current config, no upgrade actions needed. Default movie queue name is set to `default` in DB Upgrade. All operations use it by default if no specific `queue_name` was specified.
- Added and updated tests
=> Multiple movie queues support

.dockerignore, Dockerfile, README.rst
I like Docker, and I think Flexget should support Docker :)
To test this ...
- [install docker](https://docs.docker.com/engine/installation/)
- build the image from sources (`docker build -t toilal/flexget .`)
- run it (`docker run -it -v /home/<username>/.flexget:/root/.flexget --rm toilal/flexget`)
`/home/<username>/.flexget` should point to your flexget configuration.
After merge, the image will be automatically build after each commit ([thanks docker hub](https://hub.docker.com/r/toilal/flexget/)), so building the image from sources won't be required as docker run will download the image from hub.
=> Add dockerfile

flexget/plugins/api_rottentomatoes.py, flexget/plugins/input/letterboxd.py, flexget/plugins/input/whatcd.py, flexget/plugins/operate/domain_delay.py, flexget/plugins/search_btn.py, flexget/plugins/search_rarbg.py, flexget/plugins/urlrewrite_google_cse.py, flexget/plugins/urlrewrite_newpct.py, flexget/utils/imdb.py, flexget/utils/requests.py, flexget/utils/tools.py, tests/__init__.py
This generalizes the `set_domain_delay` method we had for requests sessions to allow more general limiters. Specifically, a token bucket limiter, to allow bursts of requests while still limiting the average requests per time. `add_domain_limiter` method can now be used to add an instance of an implementation of `DomainLimiter` class to session. The `DomainLimiter` instance will be called once before each request to the domain, and it is free to wait or abort as desired.
There are currently 2 limiter implementations, `TimedLimiter`, which enforces a strict minimum time between requests (directly replicates old set_domain_delay behavior,) and `TokenBucketLimiter`, which enforces an average requests/time, but allows bursting.
TODO:
=> New requests domain limiter

flexget/plugins/input/discover.py, tests/test_discover.py
release_estimations replaces ignore_estimations and can be used in three different modes: strict, auto and ignore.
The latter two reflect the current behaviour of `ignore_estimations` set to `no` and `yes` respectively. Setting it to `strict` will reject entries that have no release date.
=> [discover] feature to reject entries with no release dates

flexget/plugins/api_tmdb.py, flexget/plugins/input/emit_movie_queue.py, flexget/plugins/metainfo/tmdb_lookup.py, requirements.txt, tests/cassettes/test_tmdb.TestTmdbLookup.test_tmdb_lookup, tests/test_tmdb.py
The tmdb3 library was overcomplicated and buggy, this replaces it in our api_tmdb plugin with tmdbsimple, which is just a thin wrapper around requests. Also, it doesn't support py3, which we are trying to get working.
=> Move tmdb to tmdbsimple library

flexget/plugins/api_trakt.py, flexget/plugins/metainfo/trakt_lookup.py, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_collected_lookup, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_collected_movie_lookup, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_show_collected_progress, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_show_watched_progress, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_watched_movie_lookup, tests/test_trakt.py
~~OAUTH is required, so it's not as nice as I would have liked it... Alternatively, we could just iterate over the entire collection and _count_ the number of collected episodes and compare it to `aired_episodes`. Speed might be an issue though.~~
It just iterates over the whole collection/watched to get the number of collected/watched episodes. Very simple and it allows people to check the progress for public profiles, so no OAUTH is required.
=> Added show collection and watched status

flexget/ui/src/plugins/history/history.component.js, flexget/ui/src/plugins/schedule/schedule.component.js, flexget/ui/src/plugins/seen/seen.component.js
I'm hosting flexget ui behind an apache reverse proxy with ssl activated and some api calls don't work. When there's an api call without a trailing slash a redirection is made to an absolute url without ssl, thus cancelling the request
=> fix API calls missing trailing slash to avoid unnecessary redirections

flexget/plugins/api_t411.py, flexget/plugins/plugin_torrent411.py
T411 tracker requires the use of categories to define the season and episode numbers for the series. I implemented a specific treatment that takes advantage when the entry has this information.
=> [t411] Performs specific search for series

flexget/plugins/services/kodi_library.py
Just a simple plugin to send a 'Clean' or 'Scan' request to a Kodi server listening on `<url>:<port>/jsonrpc`.
Kodi also supports sockets but it's incredibly poorly documented and the behaviour is annoying and slow.
The basic principle of this plugin is just to send a library scan/clean request upon accepted entries (can also be forced to run with `only_on_accepted: no`).
This PR is a very simplified version of #397.
=> Simple JSONRPC plugin for Kodi library

flexget/plugins/api/series.py, flexget/plugins/cli/series.py, flexget/plugins/filter/seen.py, flexget/plugins/filter/series.py, flexget/plugins/output/series_forget.py, tests/test_series.py, tests/test_series_api.py
This will change the meaning of forget globally to mean that a `forget` event has been fired. It is currently being hooked only be `seen` plugin here:
- **Series CLI** - Changed `forget` action to implement new meaning, added `remove` command to do the same but without firing event.
- **Series API** - Changed `delete_seen` flag to `forget` in relevant place, added it to DELETE `/series/` method
- **`series_forget`** plugin changed to `series_remove`. Forget functionality was not added to it.
This will remove the requirement to manually delete from seen plugin as well, as that plugin hooks the forget event.
- `series_forget` renames to `series_remove`
- Changed the meaning of CLI `series forget ...`, replaced that with `series remove ...`
=> Change the meaning of forget to fire `forget` event globally

flexget/plugins/output/qbittorrent.py
qBittorrent's API specifies using a multipart request to add torrents, so each piece is encoded as plain text rather than form encoded. This should fix issues like [this](https://github.com/Flexget/Flexget/issues/1013).
=> Change qBittorrent plugin to use multipart request for adding torrents

flexget/plugins/urlrewrite_iptorrents.py
The IPTorrents plugin attempts to parse any link ending in ".torrent", which causes it to go through the "Recommended" and "Top" torrents section at the top of the page. This isn't desirable behavior, and causes a crash when those links don't include the attributes it expects. This change will make it specifically parse the search results table on the page.
=> IPTorrents - Only parse search results

flexget/plugins/api_rottentomatoes.py
Before this, using rottentomatoes_list would try to retrieve URLs like
http://api.rottentomatoes.com/api/public/v1.0/lists/b'dvds'/b'current_releases'.json?apikey=...
(with b'' binary string markings)
=> Python3 fix for rottentomatoes_list

flexget/plugins/input/discover.py
Add fall-back blank sort key for discover, to produce same behaviour as
in Python 2. Without this it crashes on:
`TypeError: unorderable types: NoneType() < NoneType()`
=> Fix discover with limit for Python 3

flexget/plugin.py
Was returning:
`TypeError: unorderable types: PluginInfo() < PluginInfo()`
Made PluginInfo orderable.
=> Py3: Fix 'plugin list' CLI command

flexget/plugins/filter/regexp.py
There was a name clash between the list of fields that had to be unquoted and the unquote  method, both called 'unquote'. Also, unquote was not imported.
=> Py3: Fix "'list' object is not callable, in regexp plugin

flexget/plugins/filter/list_accept.py, flexget/plugins/output/list_add.py, flexget/plugins/output/list_remove.py
Before the generic list interface was introduced, each entry that was added to the movie queue was logged. This helped tremendously to see what was happening in a task.
I've restored this logging in list_add/remove/accept.
=> List interface: improve logging

flexget/plugins/output/sabnzbd.py
Fix task.get to task.requests.get
Fixed error reporting to use requests.RequestExceptions so traceback is given on unexpected crashes.
=> [FIX] Error reporting and fix. Fix #1099

flexget/plugins/input/ftp_list.py
A new FTP/S input plugin based on the `ftputil` lib.
Replaces the current `ftp_list` plugin.
To Do:
- ~~Tests~~
=> FTP input plugin (replace existing one)

flexget/plugins/operate/cfscraper.py, flexget/utils/requests.py
Created a wrapper for the CloudflareScraper class such that we can strip out some of the kwargs.
Shouldn't be merged until https://github.com/Anorov/cloudflare-scrape/pull/52 is merged upstream. Currently, he made the class such that the helper functions that make it easy to create a Session are static methods. My PR on his branch will make them class methods instead, which enables us to extend the class ad nauseam.
=> Fix cfscraper plugin, fixes #1037

flexget/plugins/urlrewrite/iptorrents.py
IPTorrents search plugin was generating invalid search strings. Also, upon further inspection, it was connecting via plaintext HTTP.
- Update search string generator code to no longer prepend "l" to each category number
- Use HTTPS instead of HTTP
- N/A
N/A
```
016-05-29 22:36 VERBOSE  discover      download-movies Searching for `The Martian (2015)` with plugin `iptorrents` (1 of 1)
2016-05-29 22:36 DEBUG    iptorrents    download-movies searching with url: https://iptorrents.com/t?90=&89=&q=The+Martian+%282015%29&qf=
2016-05-29 22:36 DEBUG    utils.requests download-movies Fetching https://iptorrents.com/t?90=&89=&q=The+Martian+%282015%29&qf=
2016-05-29 22:36 DEBUG    discover      download-movies Discovered 8 entries from iptorrents
2016-05-29 22:36 DEBUG    backlog …
```
=> Fix invalid search string generation, update base_url to use HTTPS

flexget/plugins/urlrewrite/iptorrents.py
Currently you can't use IPTorrets with the `secrets` plugin because it requires that UID be provided as an integer. UID is always cast as a string, so this should be a safe change.
- Change schema to accept either an integer or a string
N/A
```
discover:
what:
- emit_series: yes
from:
- iptorrents: 
rss_key: '{{ secrets.iptorrents.rss_key }}'
uid: '{{ secrets.iptorrents.uid }}'
password: '{{secrets.iptorrents.password}}'
category: 
- TV-x264
```
```
2016-05-30 13:26 VERBOSE  discover      series-discover Searching for `The Venture Bros. S07E01` with plugin `iptorrents` (1 of 3)
2016-05-30 13:26 DEBUG    iptorrents    series-discover searching with url: https://www.iptorrents.com/t?5=&q=The+Venture+Bros.+S07E01&qf=
2016-05-30 13:26 DEBUG    utils.requests series-discover Fetching …
```
=> Allow IPTorrents to accept UID as a string

flexget/plugins/plugin_aria2.py
torrent file won't be downloaded in default,because of a 'not'.
@ wicast has fixed this bug,but it came back :(
=> fix a bug with 'file_exts' option

flexget/plugins/daemon/scheduler.py, requirements.txt
Compatibility with APScheduler 3.2 and beyond
The scheduler plugin was modified to start the scheduler in paused mode, then manipulate the jobs and only then start the job processing. The way FlexGet was doing it before only worked because of a programming oversight which was corrected in 3.1. The 3.1 version however lacked the means to provide comparable functionality. This shortcoming was just addressed in the 3.2 release.
- 
- Fixes # .
```
```
========== 918 passed, 7 skipped, 1 xfailed, 3 xpassed, 1 pytest-warnings in 220.10 seconds ===========
```
Job stores should not be accessed before they're started. The fact this was working in previous versions was an oversight. That said, APScheduler 3.1 lacked the ability to manipulate the jobs before the …
```
=> Fix scheduler issues with APScheduler 3.1+

flexget/plugins/metainfo/metainfo_movie.py, flexget/plugins/parsers/parser_guessit.py, flexget/utils/titles/movie.py, tests/test_metainfo.py, tests/test_subtitle_list.py
Gives an ability to parse movies and add related attributes to entry in task
- Added `metainfo_movie` plugin
- Return the following `entry` attributes:
- `movie_parser`
- `movie_name`
- `movie_year`
- `proper`
- `proper_count`
If parser is `guessit`, the following attributes are also added:
- `release_group`
- `is_3d`
- `languages`
- `video_codec`
- `format`
- `audio_codec`
- `video_profile`
- `screen_size`
- `audio_channels`
- `audio_profile`
- Fixes #1015 
```
movie_task:
rss: http://url.com
metainfo_movie: yes
list_queue:
- movie_list: movies
download: /path/to/movies
```
=> `metainfo_movie` plugin

flexget/plugins/list/subtitle_list.py, flexget/plugins/output/subtitles_subliminal.py, tests/test_subtitle_list.py
Someone asked for this feature, which was already in the now deprecated subtitle_queue. It's a slippery slope though as it can get very messy very fast. Torrent support has been dropped as it is too complex to handle all cases eg. single file torrents are not always placed in a folder.
- Added `path` config option
- Added `check_file_existence` (should probably be renamed as this option is deleting from the list if file doesn't exist)
- Added `allow_dir` option, which allows dirs to be put in the list
- Fixes #1224
```
subtitle_list:
path:
from_field: output
allow_dir: yes
check_file_existence: no
list: subtitle_queue
```
=> added some requested features to subtitle_list, closes #1224

flexget/plugins/modify/path_by_space.py, flexget/plugins/output/telegram.py, tests/test_path_by_space.py
Consistent naming convention
- Renamed send_telegram to telegram
- Renamed path_select to path_by_space
=> Unified naming

flexget/task.py
Fixes a crash that can occur on py3.5 on a specifc discover task when it is re-run. Just switched to py3.5 on main machine
```
templates:
trakt_shows:
from:
trakt_list:
username: '{{ secrets.credentials.trakt.username }}'
account: '{{ secrets.credentials.trakt.account }}'
list: '{{ secrets.credentials.trakt.list }}'
type: '{{ secrets.credentials.trakt.type }}'
strip_dates: yes
settings:
quality: 720p hdtv h264 !aac
identified_by: ep
upgrade: yes
propers: yes
trakt_lookup:
username: '{{ secrets.credentials.trakt.username }}'
account: '{{ secrets.credentials.trakt.account }}'
tvmaze_lookup: yes
tasks:
download_from_trakt_list:
discover:
what:
- next_series_episodes: yes
from:
- torrentleech: 
rss_key: '{{secrets.credentials.torrentleech.rsskey}}'
username: …
```
=> Fix py3 crash

flexget/plugins/list/regexp_list.py, tests/test_regexp_list.py
I'm greedy and want to match a list of automatically generated regexes (from trakt_list etc.) on rss feeds.
It contains a list of regular expressions that it uses to match entries.
- added
```
regexp_list_add:
trakt_list:
account: '{{ secrets.trakt.usr }}'
list: my_shows
type: shows
strip_dates: yes
list_add:
- regexp_list: test
manipulate:  # example result: game.*of.*thrones.*s\d{2}e\d{2}
- title:
replace:
regexp: '$'
format: 's\d{2}e\d{2}'
- title:
replace:
regexp: ' '
format: '.*'
regexp_list_download:
rss: https://some_url.com/rss
list_match:
from:
- regexp_list: test
remove_on_match: no
single_match: no
download: /home/derp/watch_dir
```
=> New list plugin: regexp_list

flexget/plugins/output/download.py, flexget/plugins/output/move.py, tests/test_misc.py
It makes more sense that `location` always contains the _current_ location of the file.
- Simply changed `output` to `location` and added `old_location` field.
=> change download and move to set 'location' instead of 'output'

flexget/plugins/output/download.py
request on IRC/Gitter
Allows doing something like this:
```
my_task:
plugin_priority:
download: 256  # run download before builtin torrent plugin
download:
path: /my/path
filename: "{{ torrent_info_hash }}.torrent"
```
=> Allow setting filename with config in download plugin

flexget/plugins/list/trakt_list.py, tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode, tests/test_trakt_list_interface.py
Reporting to trakt about collected episodes was broken. Their documentation suggested a completely different method, which I implemented. Now works.
- Adding episodes to lists is now done via "episodes" and not via "shows", while specifying all known episode ids (trakt, imdb etc)
=> Fixed Trakt adding episodes to list

flexget/plugins/modify/list_clear.py, tests/test_list_interface.py
Wanted to be able to clear an entry_list before populating it eg. make entry_list mimick an RSS feed. It takes as input a `phase` param that specifies at which phase it should clear the list.
- Added plugin
- Added three tests
```
list_clear:
what:
- entry_list: whatever
phase: start
```
=> list_clear - new list plugin

flexget/plugins/api_t411.py, flexget/utils/qualities.py, tests/test_qualities.py
Webrip quality has improved greatly over the last few years to the point where it's even better than hdtv. Quality is known as `webrip` or `web` (scene), but some p2p groups also call it `web-dl` (although technically, `web-dl` refers to something like iTunes download).
Qualities is in need of an overhaul, but this small change would help immensely until then.
=> Merged web qualities, closes #1218

flexget/plugin.py, flexget/plugins/api/plugins.py, tests/test_plugins_api.py
View registered plugins
- `/plugins/` endpoint will return plugin list. `group` and `phase` can be added as params. `include_schema` is also a param which is `false` by default since the response is very big with all the schema.
- `/plugins/<plugin_name>/` will retrieve a single plugin info. `include_schema` param is also relevant here.
- ~~Added `to_dict()` method for `PluginInfo`~~ Created method in API module
Example output for `http://127.0.0.1:5050/api/plugins/seen/?include_schema=true`:
```
{
"api_ver": 2,
"builtin": true,
"category": "filter",
"contexts": [
"task"
],
"debug": false,
"groups": [],
"name": "seen",
"phase_handlers": [
{
"phase": "filter",
"priority": 255
},
{
"phase": "learn",
"priority": 128
}
],
"schema": {
"id": "/schema/plugin/seen",
"oneOf": [
{
"type": "boolean" …
```
=> Plugins API

flexget/api/tasks.py, flexget/manager.py, flexget/options.py, flexget/plugins/daemon/irc.py, flexget/plugins/daemon/scheduler.py, flexget/plugins/operate/manual.py, flexget/task.py, tests/conftest.py, tests/test_feed_control.py
`manual` plugin doesn't work, because the condition that it checks can never be True. 
- Added a `allow_manual` flag to `Manager.execute()` and set it to True when calling it from CLI/API and IRC plugin.
- If a task is triggered by schedule plugin and has `manual: yes` set, it will be aborted.
- Fixes #1291
=> Tasks with manual plugin enabled run even when not via manual run.

flexget/plugins/filter/regexp.py, tests/test_regexp.py
Regexp filter passes on non-strings
There is no way to reject on field values for non-strings
e.g.: Can't reject entries with `trakt_collected: True`
- Regexp plugin will now convert non-string fields to string instead of skipping over them
=> Regexp plugin will now handle non-strings

flexget/plugins/output/move.py
Sometimes subtitles are in a subdir called `Subs`. One would expect `along` to support this already, but it doesn't. This change is mostly relevant for `copy` and `move`.
- `along` takes a string (as now) or an object that is `subdir_name: one_or_more(string)`.
- Changed it to use `glob` to allow wildcards etc.
```
move_my_stuff:
filesystem:
path: /my/storage
regexp: '.*\.mkv'
retrieve: files
move:
to: /my/media
along:
files:
- nfo
subdirs:
subs: 
- *.srt
```
=> [change] move/copy/delete 'along' now supports subdirs

flexget/plugins/input/plex.py
Sometimes I download episodes into my Plex server through channels other than Flexget.  I would like to mark these episodes as seen/downloaded in Flexget.  Currently the series plugin cannot be used with Plex episode entries because the necessary field are not set, although the information is available.  These changes set the relevant fields so Flexget can get metainfo about Plex episodes.
Added the fields `series_name`, `series_season`, `series_episode`, `series_id_type`, and `series_id` for Plex episode entires.  The necessary info was already used in Flexget for setting other fields, so my changes are entirely setting these fields.
=> Populate series info for Plex episodes

flexget/plugins/output/prowl.py
Allow the sending of the url parameter in prowl notifications
This alteration allows the prowl message to link to a user defined url
Such as the imdb page for a movie
```
prowl:
apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
event: 'New movie'
description: '{{title}}'
url: '{{imdb_url}}'
```
Or for the more tech savy a custom page that deals with the torrent
```
prowl:
apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
event: 'New movie'
description: '{{title}}'
url: 'https://myserver.com/ctrl/{{torrent_info_hash}}'
```
n/a
```
prowl:
apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
event: 'New movie'
description: '{{title}}'
url: '{{imdb_url}}'
```
```
```
=> Allow the sending of the prowl url parameter

flexget/plugins/search/1337x.py
Add 1337x search plugin
- Adds UrlRewriter and search plugin for search 1337x.to
```Either
- 1337x: yes
or
- 1337x:
order_by: (seeders|leechers|time|size)
```
(removed due copyrighted material)
=> 1337x Search Plugin

flexget/plugins/input/plex.py
I needed this two fields in order to be able to mark as seen and vote the episodes in tvshowtime and letterboxd websites automatically
plex_userrating: Rating given by the user. From 1 to 10
plex_key: Internal Plex identificator for the Media
=> Added two new fields in Entry

flexget/plugins/metainfo/thetvdb_lookup.py
trivial fix in tvdb plugin documentation
`tvdb_ep_image_url` -> `tvdb_ep_image`
=> remove '_url' from variables in documentation of tvdb plugin

flexget/tests/test_misc.py
Calculating the umask by subtraction only works by coincidence in some cases. The correct way is to use bitwise operations to unset any bits in the umask from the expected permissions. I found this since I run with `umask 077` and the test always failed on my system.
=> Fix wrong umask calculation in download test

flexget/plugins/output/subtitles_subliminal.py
- Use the effective list of providers to validate configuration when possible. Avoids needing to manually update the list to follow upstream.
- Make it possible to use providers that require login by adding the `provider_configs` option.
- Add `hearing_impaired` option.
- Make debugging easier by silencing useless spam, and un-silencing subliminal itself.
```yaml
subliminal:
provider_configs:
legendastv:
username: myuser
password: mypassword
```
```yaml
subliminal:
hearing_impaired: yes
```
=> Miscellaneous Subliminal plugin improvements

flexget/entry.py, flexget/tests/test_misc.py
BeautifulSoup, as used in some search plugins, returns strings from HTML
document structures in "enriched" form - instances of unicode/str mixed
in with another class. Those strings carry references to the whole
document tree, which can cause issues when attempting to serialize entry
values for saving to the database.
To avoid that, coerce any values whose type is a subtype of text_type,
but not *exactly* text_type, to text_type, with text_type being unicode
in Py2 and str in Py3. That should ensure we throw away any extra
baggage that might be attached but keep the exact same content.
Supersedes #1302 and fixes #1301.
=> Convert string-like values to plain strings in Entry

flexget/plugins/input/discover.py
Blurays are always leaked before official release, so if you want a movie ASAP you have to start searching a bit before official release date.
- Added dict option to `release_estimations`. No config upgrade required.
```
discover:
optimistic: 7 days
```
```
2016-08-15 08:48 DEBUG    discover      test_est        Suits S06E07 will be released at 2016-08-24 00:00:00. Ignoring release estimation because estimated release date is in less than 10 days
```
=> Added 'optimistic' config option to release_estimations in discover.

flexget/plugins/sites/limetorrents.py
Create a way to search limetorrents
```
Either
- limetorrents: yes
or
- limetorrents:
order_by: (date|seeds)
category: (all|anime|applications|games|movies|tv|other)
category defaults to all if not specified.  You may specify order_by and not category or vice versa.  You may only select one category.
```
=> Limetorrents Search Plugin

flexget/plugins/plugin_formlogin.py
When the default fields on a web form aren't ```username``` or ```password``` the resulting HTML file  the plugin tries to write generates the following error.
```
TypeError: must be unicode, not str
```
- Added b to the open() function to enable the file to be written in binary.
- Fixes #1344 .
=> Solved TypeError Issue

flexget/plugins/services/myepisodes.py
Adjust to new tvdb plugin api
The property is no longer named seriesname, but is (after a few renames) now called simply name.
=> Adjust myepisodes to new tvdb plugin api

flexget/manager.py
Why not
- On initialization, a sha1 hash of the config file is saved in the manager.
- Before task execution the sha1 hash of the config file is compared to the cached one. Calls `load_config()` if they don't match and `self.is_daemon` is `True`. If new config is invalid, the hash is still saved so it doesn't try to reload it again, but the config changes will be rolled back to the last valid one (as has always been the case)
=> Daemon will now auto-reload config file if it changes

flexget/plugins/sites/alpharatio.py, flexget/plugins/sites/morethantv.py, flexget/plugins/sites/rarbg.py
Needed a search plugin for alpharatio and rarbg had categories that were added since the creation of the plugin
```
- alpharatio:
username: user
password:  pass 
scene: (yes|no) #defaults to both
category: 
tvsd,tvhd,tvdvdrip,tvpacksd,tvpackhd,moviesd,moviehd,moviepacksd,moviepackhd,
moviexxx,mvid,gamespc,gamesxbox,gamesps3,gameswii,appspc,appsmac,appslinux,
appsmobile,0dayxxx,ebook,audiobook,music,misc
order_by: (seeders|leechers|time|size|year|snatched) # defaults to time
order_way: (desc|asc) # defaults to desc
leechstatus: (normal|freeleech|neutral leech|either) # defaults to normal
Multiple categories can be used.  Username and Password are required.
- rarbg
category: all,x264,x264 720p,x264 1080p,x264 3D,XviD,XviD 720p,Full BD
HDTV,SDTV,XXX,MusicMP3,MusicFLAC,Games/PC ISO,Games/PC …
```
=> New AlphaRatio Search Plugin and additonal categories in rarbg

flexget/plugins/api/trakt_lookup.py, flexget/plugins/internal/api_trakt.py, flexget/plugins/metainfo/trakt_lookup.py, flexget/ui/src/plugins/movies/components/movie-entry/movie-entry.tmpl.html
Crash logs are not fun
- Removed image tables and hardcoded images as columns. Gonna suck if they change the format.
- Changed translations to many-to-one instead of m2m. Much saner.
- Fixes #1191.
=> Fixed trakt images and translations

flexget/plugins/output/qbittorrent.py
Make qbittorrent more like the other client plugins.
Allow qBittorrent plugin to properly handle input torrent files and magnet links.
Also merge [change](https://github.com/Flexget/Flexget/pull/984) to set 'label' as 'category' since qBittorrent decided to change the API and the original PR looks abandoned.
- Fixes #1390
=> Properly use the downloaded torrent file in the qBittorrent plugin (except on magnet links).

flexget/plugins/input/npo_watchlist.py
npo.nl completely changed the set-up of its watchlist, requiring a rewrite of the plug-in.
Now creates entries for:
- individual episodes put on watchlist
- all episodes for series on watchlist (since max_episode_age_days)
```
npo_watchlist:
email: aaaa@bbb.nl
password: xxx
remove_accepted: yes
max_episode_age_days: 7
exec:
fail_entries: yes
auto_escape: yes
on_output:
for_accepted:
- download-npo -o "path/to/directory/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel} ({episode_id})" -t {{url}}
=> npo_watchlist: Rewrite, after big changes to npo.nl

flexget/manager.py
`cli_config` can't work when daemon is running since config isn't reloaded and manager doesn't add updated options to itself when firing event. This kinda fixes that in a hacky way. need some ideas how to do this better.
This should affect affect any config editing plugin, like `secrets` as well.
- Fixes #1299
=> Allow config changing plugins to operate while daemon is running

flexget/plugins/filter/series.py, flexget/plugins/operate/configure_series.py, flexget/task.py, flexget/utils/cached_input.py, flexget/utils/tools.py
Current method for hashing the config falls apart when the config is nested dicts.
- Changed it to use pprint.pformat
- Fixes #1406
=> Change config hash to use pprint

flexget/webserver.py, requirements.txt
- remote access to flexget
- add ssl support to webserver.py (cherrypy)
```
web_server:
bind: 0.0.0.0
port: 3539
ssl_certificate: '/etc/ssl/private/myCert.pem'
ssl_private_key: '/etc/ssl/private/myKey.key'
api: yes
webui: yes
```
=> add ssl support to webserver

flexget/plugins/filter/crossmatch.py
Code change to prevent existing fields from being overwritten by Crossmatch during entry merge
Previous [change](https://github.com/Flexget/Flexget/commit/f461f428f0c0ff468ba0ae63c849227c8cf76a10) to add merge functionality to cross match causes existing fields from the input to be overwritten by fields in the crossmatch input.  If the input for crossmatch supplies the field 'URL' the "Real URL" is overwritten and the download fails 
- Removed entry.update statement
- Added for loop with conditional to merge entry only if the field is not present in the existing entry
=> Update Crossmatch to Merge with Clobbering

flexget/plugins/input/npo_watchlist.py
This link is better since I "own" it, and has a much higher guarantee to keep
working in the future (I may stop using BitBucket, it may shut down, etc.).
=> Update link to download-npo site

flexget/plugins/sites/piratebay.py
some results were so small they reported bytes and the regex didn't match. (resulting in an exception being thrown) This makes missed parses of size not trigger an exception, as well as supporting Bytes.
=> support size unit of "B". if sizes doesn't match log and ignore.

flexget/plugins/input/input_csv.py
csv input was not working on PY3
CSV reader in Python 2 is broken and does not support unicode strings. It therefore needs byte strings, but Python 3 needs unicode strings.
csv plugin has been changed to transform the string to the proper format based on Python version.
http://discuss.flexget.com/t/input-csv-py-not-working-on-python3/2797
=> Getting CSV input on PY3 to work

flexget/plugins/input/npo_watchlist.py
@mfonville reported that npo_watchlist episode entries cannot be looked up using thetvdb_lookup. 
- Adding series_id_type=date to each entry, to allow episode details to be looked up using thetvdb_lookup (using broadcast date)
- Extended date parsing, to accept dates without a year specified (defaulting to current year)
```
npo_watchlist:
email: aaaa@bbb.nl
password: xxx
remove_accepted: yes
max_episode_age_days: 7
thetvdb_lookup: yes
...
```
=> npo_watchlist: Date parsing fix + allow use with thetvdb_lookup

flexget/plugins/filter/crossmatch.py
- Add functionality for non-Exact searching to crossmatch plugin instead of only exact matches
- if Exact: no is specified in config then "if v2 in v1:" will be used for matching instead
- if Exact: yes is specified or is not in config then the default matching is used "if v1 == v2:"
- Fixes # .  (N/A)
---  Test / Example config  ---  
```
tasks:
hasitleaked:
make_html:
file: ~/thefile.html
crossmatch:
from:
- csv:
url: file:///home/flexget/ss.csv
values:
title: 1
url: 2
fields:
- title
action: accept
exact: no
rss:
url: http://hasitleaked.com/leakedfeed/
```
```
---  Exact not specified in config  ---  
2016-09-28 15:08 VERBOSE  manager                       Creating new database /home/flexget/db-config.sqlite - DO NOT INTERUPT ...
2016-09-28 15:09 VERBOSE  details       hasitleaked …
```
=> Update Crossmatch with Exact (yes/no) search option

flexget/api/plugins/tvdb_lookup.py, flexget/plugins/internal/api_tvdb.py, flexget/plugins/metainfo/thetvdb_lookup.py, flexget/tests/api_tests/test_tvdb_lookup_api.py, flexget/tests/cassettes/test_thetvdb.TestTVDBExpire.test_expire_check, flexget/tests/cassettes/test_thetvdb.TestTVDBExpire.test_expire_no_check, flexget/tests/cassettes/test_thetvdb.TestTVDBFavorites.test_favorites, flexget/tests/cassettes/test_thetvdb.TestTVDBFavorites.test_strip_date, flexget/tests/cassettes/test_thetvdb.TestTVDBList.test_favorites, flexget/tests/cassettes/test_thetvdb.TestTVDBList.test_strip_date, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_absolute, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_cache, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_find_series_id, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_find_series_with_languages, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_lookup, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_no_posters_actors, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_unknown_series, flexget/tests/cassettes/test_thetvdb.TestTheTVDBLanguages.test_language_lookup, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBLanguages.test_episode_lookup_with_language, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBLanguages.test_series_lookup_with_language, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBLanguages.test_tvdb_search_with_language, flexget/tests/test_thetvdb.py
#1453 
- Changed schema:
```python
schema = {'oneOf': [
{'type': 'boolean'},
{'type': 'object',
'properties': {
'language': {'type': 'string', 'default': 'en'}
}}
]}
```
- Sends `Accept-Language` header to relevant thetvdb API requests.
- Fixes #1453
```yaml
tasks:
test:
mock:
- {title: 'Tegenlicht.S010E01.HDTV.XViD-FlexGet'}
series:
- Tegenlicht
thetvdb_lookup:
language: nl
mock_output: yes
```
Tests added
=> Support different TVDB languages lookup 

flexget/manager.py
Fix stuff
- Restart task queue if is_alive() returns False when executing a task in daemon
- Fixes #1254
=> Restart task queue if it has crashed (daemon only)

flexget/plugins/operate/verify_ssl_certificates.py
Suppress expected warnings to avoid mails when run from cron.
-     Disabling SSL certificate verification results in a warning for every
HTTPS request:
"InsecureRequestWarning: Unverified HTTPS request is being made.  Adding
certificate verification is strongly advised. See:
https://urllib3.readthedocs.io/en/latest/security.html"
Disable those warnings because the user has explicitly disabled
verification and so the warning is not beneficial.
- Fixes # .
```
```
```
Test output:
1 failed, 1041 passed, 26 skipped, 2 xfailed, 2 xpassed, 5 pytest-warnings in 396.33 seconds
Failed test seems unrelated:
______________________________________________________________________________________ TestFilesystem.test_non_ascii …
```
=> Disable warnings about disabling SSL verification.

flexget/plugins/filter/series.py
This is purly cosmetic and has no functional value other than to aid in the reading of logs.
This very minor change will prepend a leading zero to single digit hours or minutes of timeframe waiting messages.
- 
- Fixes # .
none
```
N/A
```
```
2016-11-07 10:23 INFO     series        tv_task   Timeframe waiting w***w***d for 41h:07min, currently best is W***w***d S01E06 PROPER HDTV x264-KILLERS
```
When scanning the logs, many timeframe waiting messages in a row apear "broken up" when one of them has a single digit recorded against the hour or minute value of the entry. This very minor change will prepend a leading zero to single digit hours or minutes of timeframe waiting messages.
This is purly cosmetic and has no functional value other than to aid in the reading of logs.
cheers
mh
=> Leading zeros on both hours and mins of "Timeframe waiting"

flexget/plugins/clients/transmission.py
Forum discussion about skipping cleanup for certain torrents based on the presence of a tracker in the torrent's tracker list
Creation of a new config setting "preserve_tracker" and adding corresponding logic
None
clean_transmission:
port: 9091
username: myusername
password: mypassword
tracker: nyaa|animebytes
preserve_tracker: alpharatio|what
=> Preserve torrents based on presence of trackers

flexget/plugins/output/exec.py
Makes it possible to find duplicates much faster than with duplicates plugin (and without a bunch of workarounds to get it to work on shows), using the following config:
```
tasks:
dups:
assume_quality:
h264: 480p
seen: no
from:
filesystem: /tv
filesystem:
path:
- /tv
recursive: yes
retrieve: dirs
if:
- has_field('series_episode'):
exec:
on_output:
for_undecided: echo {{series_name}} {{series_id}} {{quality}}  {{location}} >> `date +%y%m%d`.dups.out
```
Added on_undecided in schema and in name_map. 
- 
```
schema = {
'oneOf': [
one_or_more({'type': 'string'}),
{
'type': 'object',
'properties': {
'on_start': {'$ref': '#/definitions/phaseSettings'},
'on_input': {'$ref': '#/definitions/phaseSettings'},
'on_filter': {'$ref': '#/definitions/phaseSettings'},
'on_output': …
```
=> Added for_undecided

flexget/plugins/clients/rtorrent.py
We seem to be moving in a direction where Digest authentication will replace Basic HTTP authentication for common seedbox setups. This change uses requests to handle the auth when uri is http(s).
=> Digest auth in rtorrent

flexget/api/__init__.py, flexget/api/app.py, flexget/api/plugins/pending.py, flexget/plugins/cli/pending.py, flexget/plugins/filter/pending_approval.py, flexget/tests/api_tests/test_pending_api.py, flexget/tests/test_pending_approval.py
A more generic approach to the `pending` idea, this will work with a single task, not list dependent.
- Each entry in `task.entries` will be cached.
- If `db_entry.approved` is True entry will be accepted
Currently this operates inside a single task, but schema can take task name and try to inject it into any other task if needed. Not sure if that's useful or not, it's @gazpachoking idea ;-)
=> Pending approval plugin

flexget/plugins/clients/deluge.py
The from_deluge only loads a default set of keys, but Deluge can send a lot more.
Adding an optional keys property allows the user to specify which extra keys the plugin should load.
- Added `keys` array property to `from_deluge`
- Can only be populated with a valid item from the `extra_settings_map` dict
- `from_deluge` will load the extra keys and perform conversions necessary (like seconds -> hours etc)
```
from_deluge:
keys:
- 'active_time'
- 'remove_at_ratio'
- ...
```
```
Nothing yet, can't test deluge at work, will provide tonight
```
=> Allow user to specify extra keys wanted to be populated with from_deluge

flexget/utils/archive.py
Prevent crashes when encountering directories
- Add IOError as a handled exception in is_archive() function
- Fixes #1525 .
```
```
```
```
=> archives plugin: treat IOErrors as “not a directory”

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_info_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_info_lookup, flexget/tests/test_npo_watchlist.py
NPO.nl exposes more information about the series than currently offered by the 'searching for broadcasts' URL that we use (e.g. http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?category=broadcasts )
If you visit and fetch the official series URL (e.g. http://www.npo.nl/als-de-dijken-breken/VPWON_1261083 ) this extra information is exposed via a small snippet:
```
<div class="schema-org-props hidden-item-props"><div itemscope="itemscope" itemtype="http://schema.org/TVSeries"><a itemprop="url" href="/als-de-dijken-breken/VPWON_1261083"><span itemprop="name">Als de dijken breken</span></a><span itemprop="description">Serie over een hedendaagse watersnoodramp in Nederland en delen van Vlaanderen.</span><span itemprop="inLanguage">nl</span></div></div>
```
- I tried to add a …
=> Fetch more of the series data exposed by NPO.nl

flexget/options.py, flexget/plugins/cli/inject.py, flexget/plugins/input/gen_series.py, flexget/plugins/input/generate.py
Flexget crashes on generating random URLs, for example on injecting an entry, using Python3:
```
[/opt/local/flexget-test] # flexget inject FooBar --learn
File "/opt/bin/flexget", line 11, in <module>
sys.exit(main())
File "/opt/lib/python3.5/site-packages/flexget/__init__.py", line 42, in main
manager.start()
File "/opt/lib/python3.5/site-packages/flexget/manager.py", line 326, in start
self.handle_cli()
File "/opt/lib/python3.5/site-packages/flexget/manager.py", line 353, in handle_cli
options.cli_command_callback(self, command_options)
File "/opt/lib/python3.5/site-packages/flexget/plugins/cli/inject.py", line 38, in do_cli
entry['url'] = 'http://localhost/inject/%s' % ''.join(random.sample(string.letters + string.digits, 30))
AttributeError: module …
```
=> [fix] Possible crashes on generating random URLs on Python3

flexget/plugins/input/next_trakt_episodes.py
I noticed that without a extra trakt_lookup the next_trakt_episodes plugin did not fill in all the available trakt fields for the api call.
fields now also filled:
`trakt_series_name, trakt_series_year, tvrage_id, imdb_id, tmdb_id, trakt_slug`
=> [updated] fill in all the trakt fields

flexget/plugins/filter/if_condition.py, flexget/utils/template.py
Python eval is not safe for user input. Jinja expressions are much more appropriate.
- `if` plugin statements are now evaluated as jinja [expressions](http://jinja.pocoo.org/docs/dev/templates/#expressions)
- As jinja expressions have mostly the same syntax as the limited form of python we intended with the if plugin, most current configs should still work.
- We can now also use jinja [filters](http://jinja.pocoo.org/docs/dev/templates/#filters) and [tests](http://jinja.pocoo.org/docs/dev/templates/#tests) in if statements.
- implemented the expression evaluation via `flexget.utils.evaluate_expression` which allows for lazy fields to stay lazy for evaluation. (which the fully default jinja method wouldn't do by itself)
Our tests seem to just pass, not sure if there are cases where config …
=> Convert if plugin to use jinja expressions instead of python eval.

flexget/logger.py, flexget/terminal.py
As seen in #1558, if we try to log a character that the user's terminal doesn't support, it causes a crash.
Our console logging handler now makes sure to replace any characters the terminal is unable to display with a `?`.
- Fixes #1558
=> Prevent unicode encoding errors while logging

flexget/plugins/input/npo_watchlist.py
Prefer word-matching first; if there is more info in the date like runtime, it can confuse the date-number matching regex.
- Switched the order, by first checking for the word, this should make the system more robust.
- Fixes #1588
=> Fix #1588 in npo_watchlist

flexget/plugins/input/kitsu.py
making Flexget able to accept anime series based on their status in the kitsu.io library (former hummingbird.me)
- updatted the old hummingbiird plugins [here](https://github.com/matthewdias/hummingbird_list) to the new api
- Entry fields
- always:
- title
- url `= ''`
- when available:
- kitsu_title_en
- kitsu_title_en_jp
- kitsu_title_ja_jp
- if `latest` is set:
- series_episode
- series_id_type `= 'sequential'`
```yaml
Syntax:
kitsu:
username: <value>
lists:
- <current|planned|completed|on_hold|dropped>
- <current|planned|completed|on_hold|dropped>
latest: <yes|no>
limit_to: <airing|finished>
Example:
settings:
identified_by: sequence
from:
kitsu:
username: NikkyAi
lists:
- current
- planned
limit_to: airing
latest: no
```
- authetication (oath)
- shows series marked …
=> input plugin for kitsu.io

flexget/plugins/sites/torrentleech.py
TL changed login page/URL and now requires HTTPS for all links. Also the "www." subdomain is now required (requesting addresses without www causes redirects). This change caused the plugin not to be able to find any entries.
- Corrected login page URL and login form data.
- Corrected all addresses to start with ```https://www.```.
=> Fix torrentleech URLs after changes on the site

flexget/plugins/input/npo_watchlist.py
Needs to remove also some special character processing to produce filesystem-safe strings
Current series_name_plain produced outputs that are unprocessable on e.g. Windows filesystems or Samba shares; for passing a better value to `download-npo` a further processed plain string is more practical
- Rewrote the `_strip_accents` function into a `_convert_plain` function
=> Make sure series_name_plain is really plain

flexget/plugins/sites/torrentday.py
i used torrentleech as a starting point. The main difference being that TL uses uname/pass to login, generate the cookies & access the search pages. TD's login page has captcha, so instead i put the 3 cookies it needs as required keys. this should be fine, because in my browser they all have expiry date of 2038. Beyond that, the 2 sites have a slightly different CSS so i'm look for some different classes and divs (this is my first PR ever, so plz be gentle)
TD is my primary private tracker and TL secondary 
i'd like to discover stuff. maybe others will too
- new private tracker search plugin
```
discover:
from:
- torrentday:
uid: xxxxxxxxxxxxx  (required)  NOT YOUR LOGIN. find this in your browser's cookies
passkey: xxxxxxxxx  (required)  NOT YOUR PASSWORD. see previous
cfduid: xxxxxxxxxx …
```
=> [added] new search plugin for private tracker torrentday

flexget/plugins/sites/bakabt.py
bakabt only uses https, http links just auto forward and the url rewriter misses them, also new torrent_url needs an additional forward slash.
=> Update URLs for bakabt

.gitignore, flexget/plugins/estimators/est_released_movies.py, flexget/plugins/list/trakt_list.py
Was seeing a crash when using a list containing a movie with no release date:
```
File "/home/jacob/flexget/lib/python3.5/site-packages/flexget/task.py", line 477, in __run_plugin
return method(*args, **kwargs)
File "/home/jacob/flexget/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
return self.func(*args, **kwargs)
File "/home/jacob/flexget/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 289, in on_task_input
entries = self.estimated(entries, estimation_mode)
File "/home/jacob/flexget/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 201, in estimated
est_date = estimator.estimate(entry)
File "/home/jacob/flexget/lib/python3.5/site-packages/flexget/plugins/estimators/est_released.py", line 28, …
```
=> [fix] est_released_movies: Fixed crash with movie_year of None

flexget/webserver.py, requirements.txt
Currently in the webserver password strength is checked using the Python library [Safe](https://github.com/lepture/safe/). This library has not seen very much attention from its author in a while and it is quite simplistic in its approach.
Instead I propose to use the Python implementation of Dropbox's zxcvbn library [dwolfhub/zxcvbn-python](https://github.com/dwolfhub/zxcvbn-python). This is a more sophisticated password strength checker which is actively maintained. It is pure Python and does not introduce extra dependencies. Note that there are older forks of the code but this is the current officially endorsed one.
Replace the dependency on Safe with one on zxcvbn-python.
It can provide a more detailed password analysis but at the most basic level it returns a score from the following …
=> relplace Safe by zxcvbn for password strength testing

flexget/plugins/parsers/parser_common.py, flexget/tests/test_qualities.py, flexget/tests/test_seriesparser.py, flexget/utils/qualities.py
Bored
- #748
- Added 2160p support. 3840x2160 or 2160p or 4K are all valid. KNOWN LIMITATION: guessit cannot parse 'Some title 4K' as 2160p, but there's no reason the internal parser shouldn't be allowed to (I think).
=> Support for 2160p

flexget/tests/test_series.py, flexget/tests/test_seriesparser.py, flexget/utils/titles/series.py
Mini-series tend not to have season number in title. Sometimes they are called "Some Show Part 01" (already supported), but sometimes it's "Some Show E01".
Don't think I've ever seen "E" followed by roman numerals, which is why I gave it its own line in ep regexps.
=> added support for Exx identifier in series parser

flexget/plugins/input/my_anime_list.py
The input plugin for My Anime List was missing, and other alternatives felt lacking or non-practical
- Added My Anime List input plugin for use with configure_series
```
from:
my_anime_list:
username: <<username>>
status:
- watching
- plan_to_watch
```
=> [Add] My Anime List input plugin

flexget/api/app.py
Remove strict trailing slashes on API endpoints.
Fix for #1635
- Change to Flask API app
- Fixes #1635
=> [Fix] Remove strictness in API trailing slashes, fixes #1635

flexget/plugins/sites/torrent411.py
Hi, it stay one occurence of the old url in url-rewritter plugin torrent411: "plugins/sites/torrent411.py" line 401
Thanks
=> T411 url has changed (still one)

flexget/plugins/notifiers/toast.py
Make toast notifications work on MacOS
- Requires `pync` 
```
tasks:
not_test:
mock:
- {title: 'bla', url: 'https://flexget.com'}
disable: seen
notify:
entries:
message: '{{title}}'
via:
- toast:
timeout: 3
url: '{{ url }}'
```
=>  toast - Added mac support

flexget/plugins/input/imdb_watchlist.py
#1639
- Added support for types and added it as an entry field as well
- Closes #1639
```
imdb_watchlist:
user_id: ur11111111
list: watchlist
type:
- mini series
- episodes
```
```
2017-01-18 15:52 VERBOSE  imdb_watchlist test_imdbwatchlist Skipping title Andaz Apna Apna since it is a movie
2017-01-18 15:52 VERBOSE  imdb_watchlist test_imdbwatchlist Skipping title L. A. Confidential since it is a movie
2017-01-18 15:52 VERBOSE  imdb_watchlist test_imdbwatchlist Skipping title Taboo since it is a show
```
=> imdb_watchlist: added support for choosing types

flexget/plugins/sites/hliang.py
bt.hliang.com provides asian tv show torrents.  However, it does not support rss feeds.  To auto download shows, use http plugin to download the homepage of bt.hliang.com, and this url rewrite plugin will do the following:
1.  Go through each entry url and follow the link to open the details page.
2.  In the details page, search for the actual torrent download url (any link that contains "down.php?[unique id]"
3. Return the url if found, or raise UrlRewriteError.
=> Add url rewrite support for bt.hliang.com

flexget/plugin.py, flexget/plugins/notifiers/notification_framework.py, flexget/plugins/notifiers/notify.py, flexget/plugins/output/sns.py, flexget/task.py
Notify phase was added to enable plugins that don't end up propagating errors to task. We since combined all notify plugins into one master 'notify' plugin, which means there is already a common place to catch the errors without a special phase.
- Remove notify phase. 'notify' plugin runs on output phase and catches child plugin errors itself
- Fixes #1634
=> Remove notify phase

flexget/plugins/sites/iptorrents.py
Fix both crash issues mentioned in #1643
- Change login check to use req.text instead of req.content; this should fix Python 3 crashes
- Change parser to reflect changes to ITPtorrents page layout
- Fixes #1643.
=> Fix IPTorrents crashes

flexget/tests/test_series.py, flexget/utils/titles/series.py
This change adds a new format to the from_group filter in the series plugin.
The existing formats do not cover AnimeBytes' torrent feeds.
At the moment, upload-groups are only recognized in a '-Group' or '[Group]' format.
This PR adds recognition for the '(Group)' format.
In addition, I added unit test cases that check the recognition of this new format.
=> added extra recognized group format

flexget/plugins/input/betaseries_list.py
plugin betaseries_list has a bug when using python 3 (BUG: Unhandled error in plugin configure_series: Unicode-objects must be encoded before hashing)
- encode the password in utf-8 to avoid crash
- Fixes # .
```
```
```
```
Tested on a local installation
=> FIX Unicode-objects must be encoded before hashing

flexget/plugins/cli/plugins.py
Issue #1666
The output of the command `$ flexget plugins` included 'Keyword', 'Phases' and 'Flags', the logical extension was to include 'Interfaces' as well thus completely describing the plugins.
- Adds a header field.
- Adds a simple compaction of the interfaces list in the plugin interface field of the output.
- Added some white space between the logical constructions of the plugin fields.
- Fixes #1666
=> Add Interfaces column to plugins output.

flexget/plugins/sites/divxatope.py
=> [fix] divxatope to use new domain divxatope1

flexget/plugins/clients/aria2.py
I am pulling down a podcast feed which uses random strings for filenames, but there was no way to pass in the "--out" parameter to aria to make it rename the file
Used the same logic that was there for path for filename 
```
tasks:
podcast-1:
rss:
url: https://podcast.feed/rss.xml
regexp:
accept:
- .*
aria2:
path: '/downloads'
filename: '{{title|pathscrub}}.mp4'
```
=> added filename->out option for aria2

flexget/plugins/sites/freshon.py
Generated entry URL was wrong due to the fact that `urlparse.parse_qs` returns a dict wich values are lists.
My bad.
=> Fix bad entry url dues to parse_qs values being lists

flexget/plugins/sites/lostfilm.py
original rss feed has link to episode page on site
this plugin make right links to torrent files
lostfilm.tv change rss-feed
- New site plugin lostfilm.py
-
```
lostfilm: yes
or
lostfilm:
url: <url>
```
```
...
2017-02-10 22:33 DEBUG    input_cache   lostfilm        storing to cache rss_90da24530a4756cb92568e3143af42a4 15 entries
2017-02-10 22:33 DEBUG    utils.requests lostfilm        Fetching URL https://www.lostfilm.tv/v_search.php?c=277&s=2&e=3 with args () and kwargs {'headers': {'Connection': 'keep-alive', u'cookie': u'uid=XXXXXX;
pass=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; usess=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; lf_session=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', u'User-Agent': u'FlexGet/2.9.18 (
www.flexget.com)'}, 'allow_redirects': True, …
```
=> New lostfilm plugin

flexget/plugins/notifiers/notify.py, flexget/templates/task/default.template, flexget/templates/task/html.template
Someone wanted this.
- Added `always_send` option to `task` 
- Fixes #1657 
```yaml
tasks:
not_test:
mock:
- {title: 'bla'}
disable: seen
notify:
task:
always_send: yes
via:
- toast: yes
```
=> Added ability to always send task scoped 

flexget/plugins/sites/freshon.py
fix an import error for python3
- 
- Fixes # .
```
```
```
```
=> fix a import error for python3

flexget/plugins/filter/unique.py, flexget/tests/test_unique.py
Takes action on all duplicates, except for the first
Redoing #1231 in a separate plugin
Allowing to create unique lists by rejecting second+ items based on a list of fields.
Also created tests
New plugin "unique":
```
unique:
field: imdb_id
unique:
field: 
- series_episode
- series_name
```
(no tickets)
Personal usecase - select only one entry of each kind (e.g. only one torrent for a movie)
New plugin as described above.
Nothing else
```
nitz@mars:~/projects/flexget/virtualenv (master *+%)$ bin/py.test ~/projects/flexget/flexget/flexget/tests/test_unique.py 
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python …
```
=> Created unique plugin

flexget/plugins/sites/filelist.py
Request
```
schema = {
'type': 'object',
'properties': {
'username': {'type': 'string'},
'password': {'type': 'string'},
'passkey': {'type': 'string'},
'category': {'type': 'string', 'enum': list(CATEGORIES.keys())},
'order_by': {'type': 'string', 'enum': list(SORTING.keys()), 'default': 'hybrid'},
'order_ascending': {'type': 'boolean', 'default': False},
'search_in': {'type': 'boolean', 'enum': list(SEARCH_IN.keys())},
'include_dead': {'type': 'boolean', 'default': False}
},
'required': ['username', 'password', 'passkey'],
'additionalProperties': False
}
```
For some weird reason, the site only allows you to search in one category. Picking multiple categories and a search string makes it search in all categories.
=> New search plugin, FileList

flexget/plugins/list/entry_list.py, flexget/tests/test_entry_list.py
Added search capability to `entry_list`
```yaml
tasks:
entry_list_discover:
discover:
release_estimations: ignore
what:
- mock:
- {title: 'test title'}
from:
- entry_list: 'Test list'
```
=> Entry list search

flexget/plugins/cli/filters.py, flexget/utils/template.py
A detailed view of all jinja2 filters, native and our custom ones.
`flexget filters`:
http://pastebin.com/Vfi6PH5V
=> jinja2 filters CLI

flexget/plugins/sites/rutracker.py
Sometimes rutracker.org available only throw https
- Add new property use_ssl(boolean)
- Small code changes
- None
```
rutracker_auth:
username: 'username_here'
password: 'password_here'
use_ssl: yes
```
- None
=> rutracker - always use https

flexget/plugins/clients/transmission.py
When setting "clean_transmission: yes" nothing is cleaned before this patch.
Code used to set a value to False and test for None.
=> Set is_clean_all when intended.

flexget/plugins/input/npo_watchlist.py
NPO.nl blocks if too many requests directly after one another, probably to prevent DDoS attacks.
This spawned errors during the execution of `npo_watchlist` if having several favorite series
- Added some fixed 5 second delays before requests to NPO.nl
Prevents that Flexget randomly gives
```
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 240, in request
result = super(Session, self).request(method, url, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
r = …
```
=> Add some delays when querying NPO.nl

flexget/plugins/cli/series.py
See #1720 
- Added 1 line of helpful text.
- Fixes #1720.
When 'implementing' this I noticed that most of the CLI plugins don't return anything when no additional CLI arguments are given. For example `flexget series` just returns as does `flexget archive`. `flexget regex` crashes (because it uses a map). That's rather confusing (for me at least).
I believe it would be helpful to print the help page with a leader like 'no option selected'. Would you agree?
=> [change] Extend series list help message. (#1720)

flexget/plugins/clients/deluge.py
- I had torrent adding exceptions when waiting on magnetization. Torrent was actually added, so it's not showstopping, but feature is still defective.
- Will supply default value of `[]` when trying to access `status['files']`, which might not exist.
- Also made line a bit more Pythonic
This is the error I had.
```
2017-03-24 10:23 INFO     deluge        download_tv     REDACTED was not added to deluge! [Failure instance: Traceback: <type 'exceptions.KeyError'>: u'files'\n/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:393:callback\n/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:501:_startRunCallbacks\n/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks\n/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1184:gotResult\n--- …
```
=> Preparing for no files key when magnetizing

flexget/plugins/input/next_trakt_episodes.py, flexget/plugins/internal/api_trakt.py, flexget/plugins/list/trakt_list.py, flexget/plugins/metainfo/trakt_lookup.py, flexget/tests/test_trakt_list_interface.py, flexget/ui/tests-mock-data/history.js, flexget/ui/tests-mock-data/seen.js
The URLs generate by flexget in various places still used http as
protocol. This was changed by Trakt to https some time ago. The commit
reflects that fact.
Several URLs have changed from using `serie` and `movie` in the path to
their plural form. Trakt.tv redirected these singular forms to the
canonical plural form.
In essence this was a search and replace exercise.
None. All the 'wrong' URLs are correctly redirected by Trakt.tv. They might stop doing that at some point.
=> Change trakt URLs to TLS and plural collections.

flexget/plugins/sites/btn.py
The recent addition of season pack support to Flexget allows discovering by season, but the BTN search plugin is currently hardcoded to search for episodes. This change enables searching by season pack when appropriate.
- Search in category "Season" when ``season_pack_lookup`` is in the entry (based on entries created by [new_series_seasons.py](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/input/next_series_seasons.py#L55))
- When the above is true, search for "Season X", which is BTN's required titling for season packs
No change to config.
```
2017-04-06 19:56 DEBUG    utils.requests catchup_btn_search_seasons Fetching URL https://api.broadcasthe.net/ with args () and kwargs {'headers': {u'Content-type': u'application/json'}, 'json': None, 'data': '{"params": …
```
=> [added] btn - Search by season when the entry is a season pack

flexget/api/app.py
Outside of the [six "simple response headers"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers), most headers returned by a cross-origin ``XMLHttpRequest`` are not available to JavaScript in browsers. In order to programmatically use in JavaScript the pagination and ETag headers returned by the Flexget API, the ``Access-Control-Expose-Headers`` header must be sent to the browser.
Implements the Flask-CORS [``expose_headers`` option](http://flask-cors.readthedocs.io/en/latest/api.html#flask_cors.CORS) with the four additional headers Flexget sends (Link, Total-Count, Count, ETag). This causes the ``Access-Control-Expose-Headers`` header to be sent. This option should be updated if Flexget sends additional headers in the future. _Note the the presence …
=> [fix] api - Send Access-Control-Expose-Headers for pagination and ETag headers

flexget/plugins/filter/if_condition.py
The "now()" function in Python is relative to your local timezone,
whereas the pubdate for most RSS feeds, and possibly many other sources
of input, are specified as UTC. So when comparing dates, similar to what
is shown in the documentation, it's a lot easier to use utcnow instead
of now.
This allows you to be able to compare dates in a like manner without having to do timezone offset tracking yourself when using the if plugin. While the current implementation of the "if" plugin already handles comparing local timezones with the "now" keyword. Adding the "utcnow" keyword would allow comparing UTC timezones.
- add utcnow keyword to the list of keywords the if plugin understands
```
if:
- rss_pubdate > utcnow - timedelta(hours=1): reject
```
I've tested this locally by making the change, …
=> add utcnow to if conditional evaluation

flexget/plugins/filter/series.py
Exposing the ``identified_by`` and ``exact`` values allows other plugins to determine what their values were at the time of parsing. This allows, for example, the btn plugin to determine if the user wants a search done with the exact series name only, or if a second search (which strips any parenthetical information from the title) should also be run. It also allows the ``next_episode_*`` plugins to determine if an unknown series, or a series still being learned (i.e. set to ``identified_by: auto`` in the database) should be treated as ep or sequence ID type, or rejected.
- Add the two values as ``series_identified_by`` and ``series_exact`` to the entry when its ``series_*`` fields are populated after parsing. ``series_identified_by`` will be one of the ID types or ``auto``. …
=> change series - Expose identified_by and exact

flexget/api/core/authentication.py
When sending cross-origin requests to the Flexget API server initiated via JavaScript, clients (web browsers) follow the [W3C Recommendation CORS section 7.1.5](https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0) and do preflight checks “to ensure that the resource is aware of this specification”. User credentials must be excluded from the request.
These requests are sent via the OPTIONS method. Currently, because of the lack of authentication details in the request, Flexget responds with status code 401 (unauthorized), causing the preflight request to fail in the browser, and therefore the subsequent request with authentication information is never sent. This prevents all endpoints except /auth/login/ and /auth/logout/ from being accessible via JavaScript, _even after …
=> [fix] api - Accept OPTIONS requests without authentication to satisfy preflight browser cross-origin requests

flexget/plugins/list/couchpotato_list.py
Error after successful adding movie to couchpotato list
CouchPotatoBase.add_movie returns json with no _movies_ key. We should  get film name directly from _info_ dict ([source](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/list/couchpotato_list.py#L156)).
```
2017-04-22 15:48 VERBOSE  couchpotato_list TrakttoCP       Connection to CouchPotato to add a movie to list.
2017-04-22 15:48 CRITICAL task          TrakttoCP       BUG: Unhandled error in plugin list_add: u'movie'
File "/home/qk4l/progs/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 483, in __run_plugin
return method(*args, **kwargs)
File "/home/qk4l/progs/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
return self.func(*args, …
```
=> [fix] couchpotato_list minor fix in debug logging

flexget/plugins/output/auth.py, flexget/plugins/output/download_auth.py, flexget/tests/cassettes/test_download.TestDownloadAuth.test_download_auth, flexget/tests/test_download.py
#1240
- Added support for base and digest auth
- Fixes #1240 
```yaml
auth_test:
mock:
- title: bla
url: https://httpbin.org/digest-auth/auth/user/passwd/MD5
download_auth:
- https://httpbin.org:
username: user
password: passwd
type: digest
download: ~/
disable: seen
```
=> [add] auth plugin - Enable generic basic and digest auth

flexget/plugins/internal/api_t411.py, flexget/plugins/sites/torrent411.py, flexget/tests/cassettes/test_t411.TestRestClient.test_auth, flexget/tests/cassettes/test_t411.TestRestClient.test_error_message_handler, flexget/tests/cassettes/test_t411.TestRestClient.test_malformed_search_response, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_categories, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_terms
According to t411 website : 
Il faudra donc tout faire passer du .ai au .al
L'adresse du site est https://www.t411.al/  (à mettre en favoris) 
Commit modify both plugins : api_t411 (+tests) and torrent411
=>  Multiples changes for t411 domain name change : from .ai to .al

flexget/api/plugins/series.py, flexget/plugins/cli/series.py, flexget/plugins/filter/series.py, flexget/plugins/input/next_series_episodes.py, flexget/plugins/input/next_series_seasons.py, flexget/plugins/metainfo/thetvdb_lookup.py, flexget/plugins/output/series_forget.py, flexget/tests/test_discover.py, flexget/tests/test_next_series_episodes.py, flexget/tests/test_next_series_seasons.py, flexget/utils/titles/series.py
More stuff to do
- Added season pack support to `forget` CLI
- Added ability to forget multiple entities per command `series forget foo s01 s02e01 s03e01`
- Fixed sorting bug with `series show`
- TheTVDB lookup (Just a log message, not support for season packs from tvdb)
- Trakt lookup (Done by @cvium)
- Fixed issue where `next_series_X` didn't emit the next entity if the last one was a season pack with not series begin set.
- Fixed `series show` sort bug
- Fixed issue where `next_series_X` emitted the begin episode in error if there was a gap in series history
- Lots of additional tests
=> Season packs phase 2

flexget/plugins/notifiers/email.py, flexget/plugins/notifiers/join.py, flexget/plugins/notifiers/notifymyandroid.py, flexget/plugins/notifiers/prowl.py, flexget/plugins/notifiers/pushalot.py, flexget/plugins/notifiers/pushbullet.py, flexget/plugins/notifiers/pushover.py, flexget/plugins/notifiers/pushsafer.py, flexget/plugins/notifiers/rapidpush.py, flexget/plugins/notifiers/slack.py, flexget/plugins/notifiers/sms_ru.py, flexget/plugins/notifiers/telegram.py, flexget/plugins/notifiers/toast.py, flexget/plugins/notifiers/xmpp.py
Title and message now belong in the `notify` plugin. Some of the documentation still included these (and at least one plugin still had them in its config). Examples didn't make clear that these are sub-plugins of `notify`, and some plugins didn't have examples.
- Remove `message` and `title` from all examples.
- Remove `message` and `title` from `pushbullet` config options.
- Fix all examples to reflect these are sub-plugins of `notify`'s `via` key.
- Add brief documentation and examples for `xmpp` and `toast`.
=> [fix] notifiers - Fix notifier plugins documentation

flexget/plugins/input/next_series_seasons.py
Fixes a bug with erroneously-generated rerun entries. I realize it's small - I submitted it as a PR to ensure this is the FlexGet way to make sure there's no duplicate entry in `self.rerun_entries`.
Given begin episode of S2014E01, S2017 downloaded in history, and backfill enabled, `next_series_seasons` will emit S2014, S2015, S2016, and S2018.
If those are accepted and it’s allowed to rerun, it will then look for S2015, S2016, S2018, and S2019, because when each of the previous seasons was accepted, a rerun entry was created for the season immediately after the accepted season regardless of whether that “next” season was also accepted in that run. This is further compounded by the fact that rerun entries are generated without the normal review process in the `latest_season` -> …
=> [fix] next_series_seasons - Use latest download for rerun entry generation

flexget/plugins/input/next_series_seasons.py
Given a season identifier of S2014 and backfill enabled, it is possible for `next_series_seasons` to emit all the way down to S01 in one run.
This change prevents it from emitting if `begin` is not set and the group of seasons to review is more than 15, or if `begin` is set and the difference between the latest season to review and `begin` is more than 30. In both cases the user will be required to set or adjust `begin` before any emit will occur.
- Fixes issue originally raised by @jawilson [here](https://github.com/Flexget/Flexget/commit/30751df7da16bdc12781411cdec9f51d9e02a890#commitcomment-22161686).
=> [fix] next_series_seasons - Limit size of emit in one run

flexget/plugins/modify/sort_by.py, flexget/tests/test_sort_by.py
I wanted to sort my series without regard to leading articles.
- Adds an additional option, `ignore_articles`:
- When set to yes, the sort will ignore the English articles ‘the’, ‘a’, and ‘an’ when they appear as the first word in the field to be sorted.
- Alternatively, you can specify a custom regular expression to be used, for use with other languages or to otherwise customize the articles that are ignored.
- Added tests for both bool and custom regex forms of `ignore_articles` options.
- All tests now run from one function through use of `@pytest.mark.parametrize`.
```
sort_by:
field: title
ignore_articles: yes
sort_by:
field: title
ignore_articles: '^(ignore|other|words)\s'
```
Added two tests to test_sort_by.py for `ignore_articles: yes` and `ignore_articles: '^(the|a)\s'`.
=> [add] sort_by - Option to ignore leading articles

flexget/plugins/cli/series.py
Unseen episodes shouldn't be listed in the `series show` table, whether they are the `begin` episode or not.
Episodes which have never been seen by FlexGet are now hidden when using the `series show <show_name>` subcommand. This includes the `begin` episode if that episode was never seen by FlexGet. The `begin` episode is still listed below the table, if it is set.
=> [change] series CLI - Hide unseen episodes

.github/ISSUE_TEMPLATE.md
I noticed a very strange issue with rTorrent; payloads/torrent encoded payloads bigger than 16256 bytes were failing.  I put some logging around this `sock.send` line.  Here's a working example:
```2017-05-11 20:27 VERBOSE  rtorrent      task   Calling load.raw()
2017-05-11 20:27 INFO     rtorrent      task   Sending body of len: 11344
2017-05-11 20:27 INFO     rtorrent      task   Actually sent len: 11344
2017-05-11 20:27 INFO     rtorrent      task   Sending body of len: 1026
2017-05-11 20:27 INFO     rtorrent      task   Actually sent len: 1026
2017-05-11 20:27 INFO     rtorrent      task   some.torrent.title added to rtorrent
```
And this is a broken example:
```2017-05-11 13:20 INFO     rtorrent      task Sending body of len: 5734
2017-05-11 13:20 INFO     rtorrent      task Actually …
```
=> Fix non-check of bytes sent over Unix socket

flexget/plugins/filter/remember_rejected.py, flexget/plugins/filter/series.py, flexget/plugins/operate/configure_series.py, flexget/plugins/operate/include.py, flexget/plugins/operate/template.py, flexget/task.py, flexget/tests/test_include.py, flexget/tests/test_template.py
It's ugly
- Removed specific plugins hash table, hash table check is now global per task
- Config is checked after start phase so all changes on that phase can cause a new hash to be created
=> Refactor config hash management

flexget/config_schema.py, flexget/plugins/input/trakt_calendar.py
Dunno
```
trakt_calendar:
account: myaccount
start_day: -7  # number of days from today
days: 10
strip_dates: yes
type: episodes
```
~- [ ] Structural pytest?~
```YAML
tasks:
notify_missed:
disable: seen  # we do not want seen to interfere
metainfo_series: yes
notify: bla bla
trakt_calendar:
type: episodes
account: asdas
start_day: -7
days: 6  # Grab episodes in the last 6 days (not including today)
if:
- "trakt_collected or trakt_watched": reject
- "series_season == 0": reject
trakt_lookup:
account: dsadsa
crossmatch:
from:
- trakt_list:
account: dsadsa
type: shows
list: ddsadasdas
action: accept
fields: [trakt_series_name]
```
=> New input plugin: trakt_calendar

flexget/plugins/cli/series.py, flexget/plugins/filter/series.py
I want to sort by entity ID.
When using the `series show` CLI subcommand, you can now specify `--sort-by identifier` to sort by entity ID (aka season/episode) or `--sort-by age` for last seen date (default), and `--descending` or `--ascending` to specify the sort order.
`get_all_entities` now supports return entities sorted by `identifier` or age (default).
Renamed 'Entity ID' and 'Latest age' columns in `series show` output to 'Identifier' and 'Last seen', respectively.
=> [add] series CLI - --sort-by argument for series show

flexget/plugins/sites/newpct.py
Take all the IDs of the content on the page but the valid are those are within "parametros".
- Update the regular expression that detects the IDs.
[RegEx Test](https://regex101.com/r/vaGfdf/1)
Replace: (?:parametros\s*=\s*.*?) for check match.
=> [fix] newpct - Detect correct IDs

requirements.txt
Guessit dep change brakes tests
- lock rebulk to 0.8.2
=> Lock rebulk because guessit

flexget/logger.py
Feature request to allow larger log files in light of some plugins being _very_ verbose when using `VERBOSE` and especially `DEBUG` logging.
Two environment variables were added to allow customization of the rotating log parameters:
- `FLEXGET_LOG_MAXBYTES` defines the maximum bytes per file (default 1 MB)
- `FLEXGET_LOG_MAXCOUNT` defines the maximum number of files (default 9)
- Feathub #[17](https://feathub.com/Flexget/Flexget/+17).
=> [add] logger - use environment variables for rotating log parameters

flexget/plugins/cli/series.py, flexget/plugins/filter/series.py
Provide a better way to inject episodes and season packs into the series database.
Implements a new CLI subcommand:
```
series add "<series_name>" <entity_id> [<entity_id> ...] [--quality <quality_string>]
```
- `<entity_id>`: One or more entity IDs recognized by FlexGet, either episodes or season packs.
- `--quality <quality_string>`: Set quality for all entities (otherwise will be shown as 'None' in `series show <series_name>`). Accepts any string that the series parser will recognize as a quality string.
- Feathub #[16](https://feathub.com/Flexget/Flexget/+16).
=> [add] series CLI - manually add entities to series database

flexget/plugins/clients/deluge.py
Yet another step towards me not needing a custom `deluge` plugin anymore. (Also [it's a feature request](http://feathub.com/Flexget/Flexget/+23).)
The `deluge` option `label` is now a jinja-rendered field.
- feathub #[23](http://feathub.com/Flexget/Flexget/+23)
=> [change] deluge - Render label

flexget/plugins/cli/series.py
[Feature request](https://github.com/Flexget/Flexget/commit/dba8b0b37dc87316c67c754e98c491c2c015b920#commitcomment-22299675)
`series show` and `series list` CLI subcommands now read environment variables to determine default parameters. These can be overridden on a per-run basis by utilizing the existing command-line arguments.
- `flexget series show`:
- `FLEXGET_SERIES_SHOW_SORTBY_FIELD` can be set to `age` (default) or `identifier` to determine which field releases are sorted by. (`--sort-by` optional argument)
- `FLEXGET_SERIES_SHOW_SORTBY_ORDER` can be set to `desc` to display results in descending order. (`--descending`/`--ascending` optional arguments)
- `flexget series list`:
- `FLEXGET_SERIES_LIST_CONFIGURED` can be set to `configured` (default), `unconfigured`, or `all` to …
=> [add] series CLI - use environment variables for defaults

flexget/api/core/format_checker.py, flexget/api/plugins/series.py, flexget/config_schema.py, flexget/plugins/cli/series.py, flexget/plugins/filter/series.py, flexget/plugins/sites/iptorrents.py, flexget/tests/api_tests/test_format_checker_api.py, flexget/tests/test_series.py, flexget/utils/tools.py
Be able to use `S02` as a `begin` identifier, and also forget a `begin` episode link without removing the history of the episode itself.
Two changes relating to `begin`:
- Behind the scenes, appends ‘E01’ when an identifier of the type SXX is used as the begin episode. This can be done via CLI `series begin SXX`, config with series plugin, or API. To make this work, an additional config format validator of `episode_or_season_identifier` was added which calls `parse_episode_identifier` with the new parameter `identify_season` set to `True`. When this is not wanted, continue to use the existing `episode_identifier` config format validator.
- CLI `series begin <show> --forget` argument to remove begin episode association in series table. 
- feathub …
=> [change] series begin - SXX accepted as ID / CLI --forget option

flexget/utils/bittorrent.py
The `name` attribute of the `info` dictionary in the torrent file is often used as the container folder name in various torrent programs. However, this is not exposed in FlexGet.
- `name` is now a property of the `Torrent` class and returns the `name` attribute of the `info` dictionary from the torrent file.
=> [add] bittorrent - expose torrent name in Torrent class

flexget/tests/test_qualities.py, flexget/tests/test_series.py, flexget/utils/qualities.py
DD+ audio is becoming more common. It stands for Dolby Digital Plus aka Enhanced AC-3 and it is therefore better than both DD and AC-3. It supports up to 7.1 channels and a more efficient compression.
- Added dd+/ddp to qualities.py
- Added tests for series and quality filter
- Added support for parsing x.{0,1} audio eg. 7.1, 5.0 etc.
=> [add] parser - Support for DD+ audio and more channels

flexget/plugin.py, flexget/plugins/filter/remember_rejected.py, flexget/plugins/filter/series.py, flexget/plugins/operate/configure_series.py, flexget/plugins/operate/include.py, flexget/plugins/operate/template.py, flexget/task.py
Plugins that have config modifying operations (include, configure_series and templates currently) trigger task.config+changed flag, but only after `start` phase is done. Other plugin that rely on this data need to either catch it on a later phase (like input) or ignore it, and both of this options suck.
By adding a new `preparation` phase to occur before `start`, the correct behavior of checking if config has changed in start phase can still be used.
- Added `preparation` phase before `start` phase
- Moved `include`, `templates` and `configure_series` operations to occur on that phase
- Changed config check on Task to occur after `preparation` instead of `start`
- Reinstated the logic in `series` plugin and `remeber_rejected` to occur at `start` phase
- Hopefully Fixes #1865
=> Preparation phase

flexget/plugins/sites/rmz.py
rmz.cr needs an urlrewrite plugin for the rss feed (rmz.cr/feed) because the feed only provides links back to the rmz.cr release page.
rmz.cr (rapidmoviez.com) urlrewriter
Version 0.1
Configuration
rmz:
url_re:
- domain\.com
- domain2\.org
Only add links that match any of the regular expressions listed under url_re.
If more than one valid link is found, the url of the entry is rewritten to
the first link found. The complete list of valid links is placed in the
'urls' field of the entry.
Therefore, it is recommended, that you configure your output to use the
'urls' field instead of the 'url' field.
For example, to use jdownloader 2 as output, you would use the exec plugin:
exec:
- echo "text={{urls}}" >> "/path/to/jd2/folderwatch/{{title}}.crawljob"
```
rmz:
url_re:
- domain\.com
- …
```
=> added urlrewrite plugin for rmz.cr (rapidmoviez.com|rapidmoviez.eu)

flexget/plugins/sites/rlsbb.py
rlsbb does not provide all possible download links (notably rapidgator links are missing) in their rss feed.
This urlrewrite plugin grabs additional links from the rlsbb.ru website and adds them to the urls field of the entry.
This plugin works similar to the rmz urlrewrite plugin which was just pulled recently:
#1879
rlsbb.ru urlrewriter
Version 0.1
Configuration
rlsbb:
filehosters_re:
- domain\.com
- domain2\.org
link_text_re:
- UPLOADGiG
- NiTROFLARE
- RAPiDGATOR
parse_comments: no
filehosters_re: Only add links that match any of the regular expressions 
listed under filehosters_re.
link_text_re: search for <a> tags where the text (not the url) matches 
one of the given regular expressions. The href property of these <a> tags
will be used as the url (or urls).
parse_comments: whether …
=> Added urlrewrite plugin for Rlsbb

flexget/plugins/sites/nyaa.py, flexget/tests/test_urlrewriting.py
nyaatorrents.se voluntarily took itself offline because of some rumors that the "police" were coming after them. a few alternate versions popped up shortly after, and this seems to be the de facto one. I simply took the old nyaa plugin and updated the urls and values wherever necessary.
The old nyaa plugin was using a url that no longer is online. 
- I changed the category dictionary's values because they use different numbers.
- Their url is completely different, so I had to move around where the values get plugged in.
- I added a ".torrent" append to the url_rewrite function because the new site has a different url structure.
=> updated the nyaa plugin to use the new url.

flexget/plugins/input/rss.py, flexget/tests/rss.xml, flexget/tests/test_rss.py
The rss plugin fails to import the 'content' field of a rss feed (in my case the field was named content:encoded) and logs an error: Cannot grab non text field content from rss.
This is because feedparser stores content in an object rather than a string: https://pythonhosted.org/feedparser/reference-entry-content.html
Since 'content' can be particularly useful, it may be worthwile to write a workaround.
This pull request fixed the issue for me.
- added 10 lines of code that properly handle the `FeedParserDict` object which feedparser delivers for content elements in rss feeds
- since there may be more than one content element in atom feeds, the code loops over all content elements delivered by feedparser
- Fixes #656 .
- Feathub #[25](http://feathub.com/Flexget/Flexget/+25).
```
WARNING …
```
=> added ability to read the special content object created by feedparser

flexget/plugins/daemon/irc.py
Ignoring lines in IRC currently does not work. A `continue` only skips the innermost loop ;)
- Changed from a `continue` to a boolean and moved the skip to after the iteration over all ignored patterns
N/A
N/A
None
There doesn't seem to be any tests for the IRC plugin. I'm by no means a Python developer so I'm probably not the best person to create them. If I've missed them (Or if there's some other good place for me to add a test case for this) then feel free to point it out!
None
=> [fix] Made sure ignores actually work

flexget/plugins/daemon/irc.py
This simplifies debugging when trying to add expected lines to ignore.
- Added printing of skipped lines
N/A
N/A
N/A
N/A
None
=> [fix] irc: Print skipped line when skipping

flexget/plugins/filter/abort_exists.py, flexget/plugins/filter/abort_if_exists.py, flexget/tests/test_abort_if_exists.py
I wants it. When using LFTP or another program to download from a remote location, it can ruin a lot if FlexGet moves files before the transfer is completed. A lot of it can be handled by using "incomplete" filenames in LFTP, but there are situations where I want the transfer to be fully completed before moving.
- Added new plugin
=> New plugin: abort_exists

flexget/plugins/sites/rlsbb.py
A bug occurred in rlsbb.py when an `entry` had no `urls` field.
- Fixes a bug I just recently found.
=> [fix] bug in rlsbb.py that occurred when the entry had no urls field

flexget/plugins/sites/allyoulike.py
Make allyoulike.com work with the html plugin.
allyoulike.com urlrewriter
Version 0.1
Rewrites urls for allyoulike.com
On allyoulike, each link points to a page which contains the links to the actual files. 
Often these pages contain links to more than one quality (for example 1080p, 720p etc.).
The plugin chooses the set of links with the most files which should translate into the
Best quality movie.
There is no configuration for this plugin.
If more than one valid link is found, the url of the entry is rewritten to
the first link found. The complete list of valid links is placed in the
'urls' field of the entry.
Therefore, it is recommended, that you configure your output to use the
'urls' field instead of the 'url' field.
For example, to use jdownloader 2 as output, you would use the …
=> [add] urlrewrite plugin for allyoulike.com

setup.cfg
The latest version of pycodestyle/linter gives continually warnings because `[pep8]` is still used in setup.cfg:
```
/usr/lib/python3/dist-packages/pycodestyle.py:2190: UserWarning: [pep8] section is deprecated. Use [pycodestyle].
warnings.warn('[pep8] section is deprecated. Use [pycodestyle].')
```
- Changed the appropiate header in setup.cfg
=> Use 'pycodestyle' in setup.cfg

flexget/plugins/metainfo/nfo_lookup.py
NFO file lookup plugin would exit after it finding the first NFO file.
- Changed appropriate "return" to "continue" to exit the entry loop, not function.
=> Fixes plugin from exiting entry loop upon first found NFO file

flexget/plugins/list/sonarr_list.py
Where are no options to add series to Sonarr in unmonitored state.
Sonarr starts searching episodes right after adding.
It's not always good especially if series consist of many seasons.     
- Added `addOptions` to Sonarr POST data.
[Documentation link](https://github.com/Sonarr/Sonarr/wiki/Series#post)
New options have defaults and not affected users configs.
```
list_add:
- sonarr_list:
base_url: '{? sonarr.url ?}'
port: '{? sonarr.port ?}'
api_key: '{? sonarr.api ?}'
ignoreEpisodesWithFiles: False
ignoreEpisodesWithoutFiles: True
searchForMissingEpisodes: False
```
```
2017-09-24 15:08 DEBUG    sonarr_list   Trakt2Sonar     adding show {u'certification': u'TV-MA', u'overview': u"A gritty chronicle of the war against Colombia's most notorious drug cartels.", u'airTime': u'03:00', …
```
=> Additional options for adding Sonarr series

flexget/plugins/modify/convert_magnet.py
data type of info_hash has changed in libtorrent 1.1.3
- add check if libtorrent version is less than 1.1.3 and only convert to bytes if the version is between 0.16.13 and 1.1.3
- Fixes #1983 .
```
tasks:
stage:
convert_magnet: yes
rss: http://xxx.xxx/rss
download:
path: /home/flexget/test/
```
```
2017-10-09 16:08 VERBOSE  manager                       Creating new database /home/flexget/test/db-config.sqlite - DO NOT I
NTERUPT ...
2017-10-09 16:08 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they h$
ve completed.                                                                                                            2017-10-09 16:08 VERBOSE  details       stage           Produced 74 entries.
2017-10-09 16:08 INFO …
```
=> add check for libtorrent version 1.1.3 or higher

flexget/plugins/sites/wordpress.py, flexget/tests/test_wordpress.py
I wanted to access an rss feed that required WordPress Authentication. WordPress uses cookies for authentication and they expire quickly. I was sick of using the headers plugin and having to update it every couple days. WordPress cookies are obtained through a `POST` request to a `wp-login.php` page with data of the form:
```
log=some_username
pwd=some_password
wp-submit='Log In'
redirect_to='wp_admin.php'
```
WordPress will return cookies for authentication in the form:
```
example.org	FALSE	/	TRUE		wordpress_logged_in_[some_hash]	[username][some_hash]
example.org	FALSE	/	TRUE		wordpress_test_cookie	WP+Cookie+check
example.org	FALSE	/wp-admin	TRUE		wordpress_sec_[some_hash]	[username][some_hash]
example.org	FALSE	/wp-content/plugins	TRUE		wordpress_sec_[some_hash]	[username][some_hash] …
```
=> Added WordPress Authentication Plugin

flexget/plugins/sites/piratebay.py
The Pirate Bay TLD is now .org
- Replace .se with .org tld
=> Switch TPB TLD to .org

flexget/plugins/notifiers/microsoftteams.py
Added support for sending notifications to Microsoft Teams
- 
- Fixes # .
```
notify:
entries:
via:
- microsoftteams:
web_hook_url: http://example.com
title: 'Flexget'
```
```
```
=> Microsoft team notifier added

flexget/plugins/sites/newpct.py
Changes in Newpct web: Errors downloading from Newpct, can't find torrentID
- If we can't find torrentID (old way) search into the script openTorrent for the id
=>  Fixed Newpct, new changes in the web format

flexget/plugins/clients/rtorrent.py, flexget/utils/bittorrent.py
Fast resume saves a lot of CPU cycles
- Added `fast_resume` option that adds resume data to a .torrent. **Note: it only works if flexget has direct access to the files**
=> Added fast_resume option for rtorrent

flexget/plugins/input/gazelle.py
Add capability to search Gazelle-based sites
- Use the old what.cd plugin as a base (what.cd was Gazelle-based)
- Use a base class to do most of the work
- Implement specific sites (NWCD and RED included in this PR) in subclasses
- Add 2FA detection (2FA is currently not supported)
=> Add plugins for Gazelle-based sites (including RED and NWCD)

flexget/plugins/sites/btn.py
Appending a bunch of quality strings from the API to the title is super annoying. It makes sense for anime and other release that usually don't contain this information, but for 99% other content, it's unnecessary
- Added config option `append_quality: yes|no` (default `yes`)
=> BTN: new config option "append_quality"

flexget/plugins/list/sonarr_list.py
Adding more options to the sonarr plugin for Trakt to sonarr
- Added option to set quality profile ID (defaults to 1/any) -- You can find quality profile/profile ID at http://localhost:8989/api/profile?apikey=APIKEY
- Added option to set season folder -- True/False (Default is False)
- Added option to set monitored status of whole series -- True/False (Default is True)
*** NOTE
One thing I don't understand is the why there is a profileId and a qualityProfileId as it seems only the profileId actually does anything, but I'm leaving it in as it seems it's part of the API call anyways versus profileId not being any part of the Sonarr API..
EDIT:
- Added option to set rootfolderpath -- The way I had to set this up was that it uses the ID instead of a string path (as I couldn't get string paths …
=> Trakt to Sonarr plugin: Add couple more options.

flexget/plugins/output/symlink.py
This is on par with "decompress" plugin.
I would like to inject data into path while making hard links.
```
symlink:
to: '/home/user/{{ variable }}'
```
Tested ✅
=> [symlink] Support Jinja2 templating for "to" field

flexget/plugins/list/sonarr_list.py
None really lol
- Changes how root_folder_path config option is setup. Now uses string value instead of an integer. Defaults to using an integer if no value is passed in config.
- Removed comments on old root_folder_path setup.
=> Changes how root_folder_path option is setup

flexget/plugins/list/sonarr_list.py
sonarr_list code was old and sucky. Also a bugfix
- Added ability to bypass filters when listing all entries. It was needed when adding or removing a show in order to get the unfiltered list of shows
- Made `base_url` default to `'http://localhost` and made it not required
- Refactor and tweaks
- Fixes #2041
=> sonarr list refactor

flexget/plugins/notifiers/ifttt.py
Notification plugin to send notification to ifttt.com's webhook service.
(https://ifttt.com/maker_webhooks)
Adds a simple notification plugin to send the notification to IFTTT webhook trigger that then can be used
in an IFTTT applet.
```
notify:
task:
via:
- ifttt:
keys:
- some api key
- other api key
event: test
```
```
2018-01-02 13:53 INFO     ifttt         notify_download Sent notification to key: some_valid_api_key
2018-01-02 13:53 ERROR    ifttt         notify_download Error sending to https://maker.ifttt.com/trigger/test/with/key/bad_key: 401 Client Error: Unauthorized for url: https://maker.ifttt.com/trigger/test/with/key/bad_key
```
=> IFTTT notifications

flexget/plugins/input/filmweb_watchlist.py
I want to be able to use my filmweb watch list as an input for Flexget.
```
pip install pyfilmweb==0.1.1.1
```
```
tasks:
populate-movie-list:
filmweb_watchlist:
login: 'username/email'
password: 'password'
min_star: 5
```
```
2017-12-08 16:38 VERBOSE  filmweb_watchlist populate-movie-list Retrieving filmweb watch list for user: user
2017-12-08 16:38 VERBOSE  filmweb_watchlist populate-movie-list Logging as user
2017-12-08 16:38 VERBOSE  filmweb_watchlist populate-movie-list Filmweb list contains 385 items
2017-12-08 16:38 VERBOSE  details       populate-movie-list Produced 3 entries.
2017-12-08 16:38 VERBOSE  task          populate-movie-list ACCEPTED: `Movie #1 (2017)` by accept_all plugin
2017-12-08 16:38 VERBOSE  task          populate-movie-list ACCEPTED: `Movie #2 …
```
=> Add filmweb_watchlist input plugin

flexget/plugins/clients/rtorrent.py
Who cares
- Use native_str_to_text and .encode to ensure Py2 and Py3 compatibility
- Fixes #1692 
- Builds on PR #1695
=> [rtorrent] Fix unicode handling in Python 2

flexget/utils/requests.py
- Encoding to utf-8 in Py2
- Fixes #1965
=> Fix unicode handling for urlopen in Python 2

flexget/plugins/clients/qbittorrent.py
The qBittorrent plugin is currently unable to add torrents over a secure web interface
This commit adds two new options to the qBittorrent plugin configuration:
- use_ssl: if set to True, the plugin connects to the API using https (default: False)
- verify_cert: if set to False, skips SSL certificate verification (for self-signed certificates) (default: True)
For example:
qbittorrent:
host: 192.168.1.2
port: 8080
use_ssl: yes
verify_cert: no
=> [feature] Add SSL options to qBittorrent plugin

flexget/utils/bittorrent.py
I had some crash in bittorent.py when handling torrents that included a directory using Chinese chars. 
Looking at others torrent python code (deluge) I see that they use the dictionary keys name.utf-8/path.utf-8 instead of name/path when present. 
In the torrent that crashed those keys are present and contains proper utf-8 while path/name contains some bytes that are not UTF-8
- ins bittorent.py get_filelist check if the name.utf-8/path.utf-8 keys are present and use them if they are.
- Fixes #2024 and an other I can't find anymore
=> Use name.utf-8 and path.utf-8 when present

flexget/plugins/output/ftp_download.py
ftp_download is really not useful without the ability to use jinja2 templates.
Also made a quick fix for cases when we run into download problems and the download loop starts to loop forever.
- Really simple fix and feature so all is explained above.
=> Add jinja2 templates to ftp_download and fix infinite loop bug.

flexget/api/app.py, flexget/api/core/plugins.py, flexget/api/core/server.py, flexget/api/core/tasks.py, flexget/api/plugins/tmdb_lookup.py, flexget/api/plugins/trakt_lookup.py, flexget/api/plugins/tvdb_lookup.py, flexget/api/plugins/tvmaze_lookup.py
Update ETag Cache params for the WebUI.
The etag for content such as getting the entries within a list should have a cache max-age of 0 otherwise you may see weird behaviour within the WebUI.
=> Update cache control in API to better handle dynamic content

flexget/api/app.py, flexget/api/core/tasks.py, flexget/tests/api_tests/test_tasks_api.py
Hidden tasks should be returned by the API
- Filtered out hidden tasks for `/tasks/` endpoint
- Fixes #2084
=> Tasks api disabled tasks

flexget/api/plugins/pending_list.py, flexget/plugins/list/pending_list.py, flexget/tests/api_tests/test_pending_list_api.py
@stevezau asked
- Added `/pending_list/<list_id>/entries?search=<string>` endpoint
=> Added ability to filter pending list entries via API

flexget/plugins/sites/torrentleech.py
- The V5 introduces changes that would require a major rewrite of the
plugin. This fix temporarily makes the plugin work again.
- Make the torrentleech output plugin work until support for the V5 api can be implemented
- Changed the url used for communicating with the torrentleech api from www.torrentleech.org to 
v4.torrentleech.org
- Fixes #2115
=> The torrentleech output plugin is temporarily using the V4 api

flexget/plugins/filter/series.py, flexget/utils/database.py, requirements.txt
SQLAlchemy update to 1.2.0 breaks some stuff for us
[This](http://docs.sqlalchemy.org/en/latest/changelog/migration_12.html#hybrid-attributes-support-reuse-among-subclasses-redefinition-of-getter) change in sqlalchemy 1.2 broke our custom comparators for hybrid properties we were using. Since calling 'comparator' method on hybrid properties no longer mutates the property, we have to re-assign the result back to the property name.
Replaces #2119, fixing the issue at the root.
- Fixes #2058
=> [fix] Make sqlalchemy 1.1 and 1.2 behave the same. fix #2058

flexget/plugins/list/imdb_list.py
The list exported when using 'list: watchlist' omits a number of columns compared to the regular export. These changes make these columns optional, keeping the fields empty if they were not provided.
=> Fix: imdb_list does not support 'list: watchlist'

flexget/plugins/input/rss.py
`all_entries: no` option for rss plugin did not work between runs on python 3.3+
The builtin python `hash` function was being used to remember the url for a given run, but on python 3.3+ it was no longer the same between runs. Switched to using md5 to create the hash key.
=> rss plugin all_entries option broken on python 3.3+

flexget/plugins/output/decompress.py, flexget/tests/test_decompress.py, flexget/utils/archive.py
Clean up logic in the decompress plugin to make it cleaner and easier to follow. I've also been mulling over possibly making `decompress` an entry list plugin in the future, this should make that a bit easier.
- Added ArchiveInfo class to `utils/archive.py`, which now does most of the heavy listing for decompressing files
- Moved additional logic into standalone functions
- Fixes # .
```
```
```
flexget/tests/test_decompress.py .....                                                                                                                                                               [100%]
============================================================================================= warnings summary …
```
=> Refactor decompress plugin to be a bit cleaner

flexget/plugins/list/sonarr_list.py
If Sonarr is behind a reverse proxy with a custom `URL Base` setting, the `sonarr_list` plugin wouldn't work because it doesn't support a custom base path. This should fix that.
- Can't use `sonarr_list` with my Sonarr setup (custom base path with reverse proxy)
- Added `base_path` config schema option to `sonarr_list` with default value of `''` (should be backwards compatible)
```yml
tasks:
task-name:
sonarr_list:
base_url: https://server.example.com
port: 8443
base_path: /sonarr
api_key: ...
```
This example config will use `https://server.example.com:8443/sonarr/api/` as the base API path.
=> add base_path support to sonarr_list plugin

flexget/plugins/clients/deluge2.py
this plugin should work with older Deluge versions. 
- 
- Fixes # .
```
```
```
```
=> fix import and deluge 1.3 compatibility

flexget/tests/test_qualities.py, flexget/utils/qualities.py
Resolutions can contain p60, like p50.
Qualities aren't matching.
- Recognise p60 rates
=> Recognise "p60"

flexget/plugins/internal/api_tvdb.py, flexget/plugins/list/thetvdb_list.py, flexget/tests/test_thetvdb.py, flexget/tests/test_thetvdb_list.py
Fixes thetvdb_list plugin.
- The authorization request now requires an api key, which can be generated at https://www.thetvdb.com/member/api now included at api_key in config.yml. More info here: https://api.thetvdb.com/swagger#/Authentication
- n/a
- n/a
```
tasks:
series:
...
from:
thetvdb_list:
username: invisiblek
account_id: 1234567890ABCDEF
api_key: 1234567890ABCDEF
```
```
Error during input plugin thetvdb_list: Error retrieving favorites from thetvdb: 503 Server Error: Service Unavailable for url: https://api.thetvdb.com/user/favorites
```
=> thetvdb_list: add support for new api

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup, flexget/tests/test_npo_watchlist.py
- NPO has greatly overhauled their site, everything is now on www.npostart.nl
- The 'recent' watchlist feature was not reliable anymore with the new 'subscribing' to a series mechanism, because it hides every episode before the subscription moment
- In the future maybe this can be re-added when there will be enough time to figure out handling of edge-cases
- Track which series are subscribed to via a more reliable JSON-inteface of the user's profile, instead of using bs4 for that
- Get all episode data of a series through XmlHttpRequest, more reliable with respect to UI changes
- Add pagination support to fetching episodes (this was missing, without our knowledge)
- Update the serie to test, "De dijken breken' that was original part of the test, is not available anymore, so it is replace …
=> Update NPO Watchlist plugin

flexget/plugins/daemon/irc.py
The current `task_re` functionality in the `irc_daemon` plugin allows users to define one or more regex that when matched will cause that task to execute.  When more than one regex is defined for a task, the task is executed when ANY of them are a match.  If you want to only execute a task when regex1 matches AND regex2 matches, this cannot currently be done.
This pull request restructures the format of the `task_re` config so both AND conditions and OR conditions can be achieved.
Change format of `task_re` config to allow a task multiple times with different regexes (OR condition) and multiple regexes to be defined for a single task (AND condition).
In this example, the tasks will only execute when both of their respective patterns are a match:
```
task_re:
- task: get_movie_entry …
```
=> change irc daemon task_re configuration structure to enable AND conditions

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup
NPO updated their website, to make the plugin work again we need this change.
Also fixed an error that could occur if `_get_series_info` failed to fetch info
=> NPO Watchlist website update

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup, flexget/tests/test_npo_watchlist.py
To set-up some automatic regression testing scripts, I'd like to include the version of the NPO website (that they expose via a meta-tag) in flexget and the unittest.
=> Include NPO website release version in unit test

flexget/plugins/clients/rtorrent.py
Loading torrents into rtorrent can take a while for me, so when adding multiple torrents it cannot verify the subsequent additions, but it's _never_ happened for me that it wasn't added.
- Changed entry.fail to log.warning
=> [rtorrent] Adding a torrent can sometimes take a while, so verification fails

flexget/plugins/input/next_series_episodes.py, flexget/tests/test_next_series_episodes.py
To restrict reruns to same season as latest episode emitted
```
next_series_episodes:
only_same_season: yes
```
=> next_series_episodes: added `only_same_season` config option

flexget/plugins/output/decompress.py
Decompress plugin was failing to throw `PluginError`.
- Fully qualified `plugin.PluginError` in Decompress plugin
```
2018-07-19 12:34 CRITICAL task          Movies-Decompress BUG: Unhandled error in plugin decompress: global name 'PluginError' is not defined
File "/usr/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
return method(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
return self.func(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flexget/plugins/output/decompress.py", line 205, in on_task_output
self.handle_entry(entry, config)
File "/usr/lib/python2.7/site-packages/flexget/plugins/output/decompress.py", line 182, in handle_entry
to = get_output_path(config['to'], …
```
=>  Fully qualify plugin.PluginError

flexget/plugins/notifiers/slack.py
Supersedes/reopens #1716.
- Add attachments to schema and include in payload
```
templates:
slack:
notify:
entries:
message: ":movie_camera: {{ imdb_name }}"
via:
- slack:
web_hook_url: "{? slack.web_hook_url ?}"
username: "{? slack.username ?}"
attachments:
- title: "{{ imdb_name }} ({{ imdb_year }})"
image_url: "{{ tmdb_posters | first }}" # better quality
title_link: "{{ imdb_url }}"
fallback: "{{ imdb_name }} ({{ imdb_year }})"
text: "{{ imdb_plot_outline }}"
color: "#e67e22"
footer: "{{ task }}"
footer_icon: "https://avatars2.githubusercontent.com/u/17483320?s=400&v=4"
fields:
- title: Runtime
value: "{{ tmdb_runtime }} mins"
short: true
- title: Score
value: "{{ imdb_score }}"
short: true
- title: Genres
value: "{{ imdb_genres | join(', ') | title }}"
short: true
- title: Rating …
```
=> [add] slack: Support message attachments

flexget/plugins/input/html.py
Some links are sometimes empty but have a CSS style that make them visible (typically an icon) but html plugin ignores them
- Add a `allow_empty_links` option in html plugin
- Update skipping code
`allow_empty_links` is False by default for backward compatibility.
=> Add option to allow empty links in html plugin

flexget/plugins/sites/torrentleech.py
PluginError only takes one string as an argument, it does not do string formatting.
=> Properly format PluginError string in TorrentLeech

flexget/plugins/sites/site_1337x.py
1337x.to scraping has been broken. I'm not entirely sure when it broken, but the scraping login does not match current site content.
In site_1337x.py, 1) Fixed url_rewrite() logic to properly match on torrent and magnet urls, 2) Fixed search() to properly match on download entries and corresponding columns (seeds, leeches, size).
=> Fixing 1337x.to scraping

flexget/_version.py, flexget/plugins/daemon/scheduler.py
It appears slower devices have trouble with race conditions in the scheduler and task executions. Credit goes to #2205 (@gxfxyz).
- Added a separate db-file for apscheduler's jobstore
- Fixes #2205 
- Fixes #2025
- Fixes #1371
=> Scheduler should perhaps use a separate DB-file

flexget/plugins/input/backlog.py
Old issue
- Take an entry snapshot just before metainfo phase
- Fixes #1000 
It's a hack, but the only reason lazy lookups are causing db locks is that some of the entries were generated after input phase or injected. Any regular entry will actually have a snapshot taken during input phase and not cause any issues, hence the changes in this PR.
=> series: save entry state before metainfo phase to avoid lazy lookups during backlog (timeframe)

flexget/plugins/input/betaseries_list.py
Betaseries.com recommends the use of the HTTPS endpoint. Edited the plugin accordingly.
https://www.betaseries.com/api/requetes states the HTTPS is preferred over plain-text HTTP.
- changed API_URL_PREFIX to use HTTPS
- also changed the links to betaseries.com documentation to https.
=> Use HTTPS endpoint of Betaseries

flexget/plugins/input/rss.py, flexget/tests/api_tests/test_server_api.py, flexget/tests/api_tests/test_tasks_api.py, flexget/tests/rss_escape.xml, flexget/tests/test_rss.py
Right now some trackers (e.g. newstudio) do not eascape ampersands with `&amp;`
This commits adds logics to fix that. Option is disabled by default because it adds some processing overhead and needs to go thru whole XML content and then rebuild new XML.
```
tasks:
Newstudio:
rss:
url: '{? newstudio.address ?}'
escape: yes
```
=> Add option to escape unescaped ampersands

flexget/plugins/list/trakt_list.py
Support Trakt API route to get list of watched episodes (Only if an "account" is set up): https://discuss.flexget.com/t/delete-files-if-seen-on-trakt-tv/4327
- Set correct route if it's a watched list with type episode
- Fixes #2056
=> Support sync endpoint for watched episodes

flexget/plugins/notifiers/telegram.py
A message or message template can include links, but the user may want to disable the webpage preview feature to minimize message length.
- Adds option to disable webpage preview in config file. Default is still disable = False.
```
telegram:
bot_token: token
use_markdown: yes
disable_previews: yes
recipients:
- username: my-user-name
- group: my-group-name
- fullname:
first: my-first-name
sur: my-sur-name
```
```
2018-10-14 11:38 DEBUG    notify        telegram-test   Sending a notification to `telegram`
2018-10-14 11:38 DEBUG    telegram      telegram-test   token=xxxxxxxxxx, parse_mode=markdown, disable_previews=True, usernames=[u'xxxxxxxxxx'], fullnames=[], groups=[]
2018-10-14 11:38 DEBUG    telegram.bot  telegram-test   Entering: get_me
2018-10-14 11:38 DEBUG …
```
=> Add support for Telegram disable_web_page_preview option

flexget/plugins/input/anidb_list.py
The AniDB list plugin was simply broken. You would get a 403 because of the user-agent.
- Change the default User-Agent to something realistic
- "mode" parameter allow you to get a specific wishlist as opposed to the entire thing (#1031 old, but relevant)
- "pass" parameter to allow the user to keep their wishlist marked as private (see AniDB Settings > Permissions > Guest Password to enable the password)
- Add support for OVAs as they were always skipped over because they don't fall under "shows" or "movies"
- If there is more than one page of wishlist items, it will now load those as well
- Fixes #2219 
- Issue #1031 (they were told to move it to Feathub, but they never did)
```
anidb_list:
user_id: (no changes)
type: (added new option "ovas")
strip_dates: (no changes)
mode: (all, …
```
=> Fix and Upgrade anidb_list.py

flexget/plugins/sites/passthepopcorn.py
Ability for more reliable and finer control over passthepopcorn search results.
- Added entry fields from search results that are already present in the request, but are currently ignored and not saved. 
- If possible, I could try to map passthepopcorn qualities to current flexget qualities e.g. Blu-ray:bluray. These mapped qualities would take precedence over parsed qualities from torrent title which would result in more accurate quality mapping. However, I'm not sure how viable or even possible this would be.
=> Add more entry fields to PassThePopcorn search plugin

flexget/plugins/input/npo_watchlist.py
and then _get_series_info() does fail, with a critical error.
This fix avoids the critical error, and will just make it skip only this serie.
Original error that would sometimes occur:
``BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
flexget/plugins/input/npo_watchlist.py", line 181, in _get_series_info
'npo_name': series.find('h1').text,
AttributeError: 'NoneType' object has no attribute 'find'``
=> Sometimes the NPO-page does not return valid content

flexget/plugins/sites/passthepopcorn.py
Sometimes if there is a year discrepancy in a movie's release year between trakt (or other input sites that originally set movie_year), imdb, and passthepopcorn, it will reject the movie on passthepopcorn based on this discrepancy. This change will allow to ignore year discrepancies if we are dealing specifically with an imdb_id (no possibility of mismatches).
- Ignores year matching check in PassThePopcorn plugin if using imdb_lookup and thus dealing with imdb ids i.e. there will be no mismatches so checking the year is not necessary. 
Note that if whatever plugin produces the imdb_id produces the wrong or incorrect id, PassThePopcorn will download that movie with the imdb_id without failsafe procedure.
=> PassThePopcorn ignore movie year discrepancies if we have imdb id

flexget/plugins/parsers/parser_guessit.py, flexget/tests/test_movieparser.py
Guessit would return a list of property values; found when parsing instead of a string.
This resulted in unexpected behaviour and errors on flexget side. Most noticable erroring out in the guessit parser mappings.
- #2249
- https://discuss.flexget.com/t/unhandled-error-in-lazy-lookup-plugin-unhashable-type-list/4384/
- https://github.com/Flexget/Flexget/pull/2197
=> Force single values from guessit

flexget/plugins/clients/rtorrent.py
As described in #2239, starting with rTorrent v0.9.7. I was mistaken as to when these were taken out. They were depreciated as of v0.9.0, and then finally removed in v0.9.7.
- Wrap the `d.multicall` in a try/except catching a fault
- If the fault code is [-506](https://github.com/mirror/xmlrpc-c/blob/master/stable/include/xmlrpc-c/base.hpp#L468), call `d.multicall2` which has a slightly different definition
- Otherwise, raise the error
- Fixes #2239 
Line 4 here in this log. For reference, I am on rTorrent v0.9.7.
```
...
2018-11-12 13:55 DEBUG    task          test_rtorrent   executing test_rtorrent
2018-11-12 13:55 DEBUG    status        test_rtorrent   Adding new task test_rtorrent
2018-11-12 13:55 WARNING  task          test_rtorrent   Aborting task (plugin: from_rtorrent)
2018-11-12 …
```
=> Fix for rTorrent v0.9.7+

flexget/plugins/sites/rutracker.py
I need it because rutracker is blocked in my country.
- Use requests from task instead of importing in plugin
=> Add proxy support for rutracker plugin

flexget/plugins/input/my_anime_list.py
Allow user to filter by entry tags with the `if` plugin - example in config_usage
- Add `mal_tags` field to the entries produced by my_anime_list plugin, populated by `tags` provided by MyAnimeList API
```
if:
- '"ignored" not in mal_tags.split(", ")': accept
```
=> Add tags to my_anime_list plugin entries

flexget/plugins/sites/torrentleech.py
The torrentleech plugin didn't detect if tbe login to the torrentleech site failed. Instead it failed on every attempt to search for a series or movie with a JSON Decode error.
Check if the url of the response still has the login part in it and raise an exception in this case.
=> [fix] Show reasonable error if login to to torrentleech.org fails

flexget/tests/conftest.py
When a test fails before entering the test function, the exception is printed by conftest.py instead pytest.
caplog.text is of type unicode
- print `caplog.text` instead `caplog.text()`
```python
class TestTmp:
config = """"""
def test_tmp(self, execute_task):
execute_task('d')
```
```
( ... )
try:
mockmanager = MockManager(config, request.cls.__name__)
except Exception:
>           print(caplog.text())
E           TypeError: 'unicode' object is not callable
conftest.py:71: TypeError
```
=> Fix caplog test issue

flexget/plugins/sites/piratebay.py
Fix relative vs absolute URLs on PirateBay
also small update for https scheme support in broken torrent URLs
Current Pirate Bay plugin is broken because the links to the torrent URLs have been changed from relative to absolute and resulted in errors like:
```
RequestException HTTPSConnectionPool(host='pirateproxy.lifehttps', port=443): Max retries exceeded with url: //pirateproxy.life/torrent/xxx/xxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f37157726d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)), while downloading https://pirateproxy.lifehttps://pirateproxy.life/torrent/xxx/xxx
Failed XXX (Network error during request: HTTPSConnectionPool(host='pirateproxy.lifehttps', port=443): Max retries exceeded with …
```
=> Fix relative vs absolute URLs on PirateBay

flexget/plugins/sites/hliang.py
bt.hliang.com changed their torrent page url format.  The home page used to list torrent pages as `http://bt.hliang.com/show.php?...`, but now lists it as `http://bt.hliang.com/show-...` (e.g. `http://bt.hliang.com/show-c7fb6d575a06a80820a045903face704f4a43b3c.html`)
As a result, the urlrewrite plugin no longer returns `true` when asks if the plugin supports the hliang url, and the plugin no longer works.
- Update the url to match the latest format.
=> Update url to match current hliang url format

flexget/ipc.py, requirements.txt
Python3.7 compatibility
- updated rpyc to 4.0.2
- updated pyyaml to 3.12
- updated Daemon/ClientService to use the new rpyc Service.on_connect() signature
- Fixes #2189
```
I'm not sure what to put here
```
- add python 3.7 tests to circleci, i have no idea how to do this
=> Python 3.7 support

flexget/plugins/services/kodi_library.py
I use kodi, now on v18, automatic library updates recently broke
- use requests.post instead of requests.get
- send params with json kwarg rather then params kwarg (saves nesting in an extra dict and calling json.dumps)
- Fixes #2210 
<details>
<summary> test output </summary>
this is with #2266 #2268 #2225 #2270 merged in
```
Testing started at 12:56 AM ...
/home/max/git/Flexget/venv/bin/python /usr/share/pycharm/helpers/pycharm/_jb_pytest_runner.py --path /home/max/git/Flexget/flexget/tests
Launching pytest with arguments /home/max/git/Flexget/flexget/tests in /home/max/git/Flexget/flexget/tests
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-3.6.0, py-1.7.0, pluggy-0.6.0
rootdir: /home/max/git/Flexget, inifile: …
```
=> use requests.post in KodiLibrary to support Kodi18-Leia

flexget/plugins/filter/series.py, flexget/plugins/parsers/parser_guessit.py, flexget/plugins/parsers/parser_internal.py
Arch isnt too great at running on older python versions :smile: 
- replace all instances of time.clock with preferred_time which is either time.process_time if supported otherwise remains time.clock. This is detected by attempting to access time.process_time on module import and setting the module level variable preferred_clock accordingly
- Fixes #2265
```
i have log output in the linked issue of the behaviour before this patch, the DeprecationWarnings are no longer present after this patch is applied
```
=> fix time.clock DeprecationWarning under python3.7

dev-requirements.txt, flexget/tests/conftest.py
I like tests that pass
- changed lines 66, 204 and 212 of flexget/tests/conftest.py to use the newer test methods
- Fixes #2269 
<details>
this is with #2266 #2268 #2225 merged in
<summary>test output</summary>
```
Testing started at 6:45 PM ...
/home/max/git/Flexget/venv/bin/python /usr/share/pycharm/helpers/pycharm/_jb_pytest_runner.py --path /home/max/git/Flexget/flexget/tests
Launching pytest with arguments /home/max/git/Flexget/flexget/tests in /home/max/git/Flexget/flexget/tests
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-3.6.0, py-1.7.0, pluggy-0.6.0
rootdir: /home/max/git/Flexget, inifile: setup.cfg
plugins: vcr-1.0.1, forked-0.2collected 1310 items
test_abort.py . …
```
=> Fixes failed tests due to deprecation warnings after pytest 3.6.0

flexget/plugins/notifiers/discord.py
- Support Discord webhook for notify plugin 
- Feathub #[53](https://feathub.com/Flexget/Flexget/+53).
- I based the plugin on the already existing slack plugin
- I adapted the schema of the config to correspond to discord webhook format: https://discordapp.com/developers/docs/resources/webhook#execute-webhook
```
notify:
entries:
message: "{{series_name}} - {{series_id }}"
via:
- discord:
web_hook_url: "{? web_hook_url ?}
avatar_url: "{? avatar_url ?}
username: "Flexget"
embeds:
- title: "{{series_name}}"
description: "{{tvmaze_series_summary|default('Unknown')}}"
url: "{{tvmaze_series_url}}"
color: 0xe67e22
author:
name: "Flexget"
url: "https://flexget.com"
icon_url: "https://i.imgur.com/R66g1Pe.jpg"
fields:
- name: "Episode Name:"
value: "{{tvmaze_episode_name|default('Unknown')}}" …
```
=> [add] new notifier/Discord plugin

flexget/plugins/sites/torrentday.py
torrentday webpages seemed to be malformed. To address this issue one can skip over that portion of the webpage.
Additionally, the seeders and leechers portion of td plugin results in an error, since it is using find_all when it should use find.
- add  hack to bypass malformed portion of html
- switch from find_all to find for seeders and leechers
- Fixes #2272
- Fixes #2273
=> Erichlf torrentday

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup, flexget/tests/test_npo_watchlist.py
Changed 'id' to 'date-id' on website
Updated tests
NPO did update their website last night, this update is necessary to accommodate for the changes they made to the website
=> Update for NPO.release-1.41.4

flexget/plugins/parsers/parser_guessit.py
The guessit plugin doesn't check if the name is valid after trying to get it from the `guessit_results`
- Check if not name, if so mark it not valid. The following if was changed to elif.
- Fixes #2276.
=> check if not name, if so mark not valid

flexget/plugins/sites/descargas2020.py
Bug fixing (plugin not working)
- Simplify torrent ID location using regular expressions
- Fix base URL (_DESCARGAS2020_TORRENT_FORMAT_) for torrent download
- Use base URL to derive download link from torrent ID
- Fixes #2280  .
```
2018-12-27 19:02 VERBOSE  descargas2020 mytask Descargas2020 URL: http://descargas2020.com/descargar/serie/<redacted_tvshow>/temporada-2/capitulo-03/
2018-12-27 19:02 INFO     urlrewriter   mytask  Entry '-  <redacted_tvshow> [HDTV][2x03][Castellano][www.descargas2020.com]' URL rewritten to http://descargas2020.com/download/<redacted_link> (with descargas2020)
2018-12-27 19:02 INFO     download      mytask Downloading: <redacted_tvshow>-   [HDTV][2x03][Castellano][www.descargas2020.com]
```
=> Fix descargas2020 plugin broken

flexget/plugins/metainfo/quality.py, flexget/tests/test_qualities.py
Makes sense
- During metainfo phase, force quality str to Quality instance instead
- Fixes #2242
=> Force quality field to Quality instance during metainfo phase

flexget/plugins/list/trakt_list.py, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_get_list, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_strip_dates, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_simple, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_task, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_pagination, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_remove, flexget/tests/test_trakt_list_interface.py
I brokes it, I fixes it
- If a pagination header is retrieved and the list contains more items than the pagination limit, it will fetch 1000 items per request until it has retrieved it all
- Fixes #2254
=> Trakt list: Add pagination handling

flexget/plugins/input/next_trakt_episodes.py
Someone was asking for a way to set begin episode to next airing ep, this would facilitate that.
Adds 'aired' context to next_trakt_episodes. Allows emitting next or last aired eps based on trakt data.
```
trakt_next_episode:
account: my_account
list: my series list
context: aired
```
=> [add] trakt_next_episode - 'aired' context

flexget/tests/conftest.py
Without this change the tests fail if pytest is up to date, because `get_marker` has been removed
=> Update `get_marker` to `get_closest_marker` to fix pytest

flexget/plugins/metainfo/media_id.py
Fix possible TypeError when series_id is None
If series_id is None: 
TypeError: coercing to Unicode: need string or buffer, NoneType found
=> Fix possible TypeError when series_id is None

flexget/plugins/input/regexp_parse.py
Sometimes servers are not aware of the content encoding which they serve, thus it is necessary to give a hint to Flexget about it.
- Field **encoding** is added as _optional_ to the schema of **regexp_parse** plugin. If the value is set, it will be given to requests.Response.encoding as a hint about content encoding.
N/A
N/A
**regexp_parse** plugin schema is updated with an optional **encoding** field and documentation is updated.
```
regexp_parse:
source: http://username:password@ezrss.it/feed/
encoding: "utf-8"
sections:
- {regexp: "(?<=<item>).*?(?=</item>)", flags: "DOTALL,IGNORECASE"}
```
N/A
=> add encoding field to regexp_parse

flexget/plugins/clients/qbittorrent.py
1. maxupspeed: support to set torrent upload speed limit. Unit in KiB/s  --same as transmission
2. maxdownspeed: support to set torrent download speed limit. Unit in KiB/s --same as transmission
=> added speed limit support for qBittorrent

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistPremium.test_npowatchlist_lookup, flexget/tests/test_npo_watchlist.py
Fixes #2300 (entries without runtime)
Allows to set a filter for NPO premium content
Added respective tests
=> Add support for NPO premium filter

flexget/plugins/modify/sort_by.py, flexget/tests/test_sort_by.py
In preparation to remove internal sorting from series and discover plugins, allow sort_by plugin to sort on multiple fields.
- Allows a new config format which is a list.
- Fixes wrong behavior of just 'reverse: no' config, which previously would reverse anyway when no field was specified.
- Allows sorting of fields where some entries are missing that field (or have a None value) they will always be sorted last in this case (no matter whether 'reverse' is specified)
- Allows use of jinja expressions for field name
```yaml
sort_by:
- field1
- field2
- field: field3
reverse: yes
- quality.resolution
- title|lower
```
=> [change] Allow sort_by plugin to sort on multiple fields

flexget/plugins/input/discover.py, flexget/plugins/modify/urlrewrite_search.py, flexget/plugins/search_yts.py, flexget/plugins/sites/btn.py, flexget/plugins/sites/fuzer.py, flexget/plugins/sites/iptorrents.py, flexget/plugins/sites/limetorrents.py, flexget/plugins/sites/newtorrents.py, flexget/plugins/sites/nyaa.py, flexget/plugins/sites/piratebay.py, flexget/plugins/sites/ptn.py, flexget/plugins/sites/site_1337x.py, flexget/plugins/sites/torrentday.py, flexget/plugins/sites/torrentleech.py, flexget/plugins/sites/torrentz.py, flexget/tests/test_discover.py
Stop overriding search order returned from search plugins with discover plugin.
This should probably be released alongside #2312 so the upgrade actions can be combined. #2311 should be released either before, or with this.
- Discover plugin on longer does any sorting of entries.
- Search plugins that were filling search_sort field were all using torrent_availability as the metric. Change all those search plugins to provide that field directly, so user can sort by that if desired.
- Behavior of 'limit' option in discover plugin is now changed. Entry which urlrewrite_search returns may also change. See TODO below.
To maintain same behavior of current release, the following can be added to tasks:
```
sort_by:
field: torrent_availability
reverse: true
```
=> Remove discover sorting

flexget/plugins/filter/series.py, flexget/tests/test_reorder_quality.py, flexget/tests/test_series.py
The series plugin internal sorting means you are currently unable to prioritize certain entries when there are multiple in the task that are acceptable. Removing the internal sorting allows the user to use sort_by plugin to prioritize based on other criteria than best quality. e.g. Grab worst (acceptable) quality, grab from one tracker over another, from one input plugin over another.
This should wait for #2311, to allow duplication of current behavior.
=> Remove internal sorting from series plugin

requirements.in
If system has path.py <10.6 installed, Flexget will fail at runtime.
- Increase version of path.py dependency to 10.6
.stem property that Flexget uses was added to path.py in v10.6
https://github.com/jaraco/path.py/blob/3684c4dc4896c174852b901b033e021a6267df2e/CHANGES.rst#106
I tested with v10.4 (failure) and with v11.5 (success).
=> requirements.in: min version of path.py is 10.6

flexget/ipc.py, flexget/manager.py, flexget/options.py
The timeout on rpc connections put a hard limit on how long a cli client would stay connected to the daemon. It would abort streaming the results back after this timeout was reached (regardless of activity.)
The user should not need to specify --timeout parameter for long running client sessions. The --timeout name was also very non-intuitive as to what it did, how was one to know this was the length of time you would stay connected to daemon?
- Removes --timeout parameter from CLI
- CLI client connections to daemon may last as long as needed.
- Fixes #2319
=> Eliminate rpc timeout. Remove --timeout option

flexget/components/parsing/parsers/parser_guessit.py
I didn't read and the previous pull only fixed the first level of issues.
- Instead of checking if its a special kind of dictionary, initialize as a MatchesDict and it works like magic. Passes the tests too.
=> GuessIt Parser -- Initialize a MatchesDict()

flexget/plugins/clients/deluge.py
from_deluge plugin provides only a subset of fields from deluge, some come standard, some have to be specifically requested in config. Also, some come with a different name than deluge uses, and some come with some value manipulation from the raw deluge value.
- Provide every field, as-is from deluge as entry fields with the format `deluge_<deluge_field_name>`
- Still does some processing/renaming for a few other fields outside of deluge_ namespace which we have a 'standard' for:
- torrent_info_hash
- torrent_peers
- torrent_seeds
- content_size
- content_files
- Removes the 'keys' option from from_deluge config
- Fixes #2257
- Time based fields from deluge were previously provided in hours, they are now provided in seconds
- Several fields will now have a new name, and fields provided …
=> Standardize from_deluge fields

flexget/plugins/clients/transmission.py
Deprecate clean_transmission. Provide parity for upcoming deluge plugin enhancements (#2325, #2329) in transmission.
- Set onlycomplete default to false
- Fix onlycomplete option to make sense
- rename onlycomplete to only_complete
- Provide more fields from transmission for use in filtering
- Add underscores between words in option names. (max_up_speed, max_down_speed, max_connections, add_paused, bandwidth_priority, honour_limits)
- Fixes #1201
=> transmission overhaul

flexget/plugins/clients/deluge.py
Allow the ability to control torrents already loaded into deluge. Actions other than 'add' would (mostly) be used in a task with from_deluge as the input. This will be more useful once #2325 is merged so that all deluge fields are available and consistent for filtering on.
- Adds 'action' option to deluge plugin
- Adds underscores to all deluge options with multiple words
```
deluge:
action: <add|remove|purge|pause|resume>
```
=> deluge: add ability to remove/pause/resume torrents

flexget/components/sites/sites/descargas2020.py
- https urls are not currently supported
- self.requests in `parse_download_page` should never be `None`
- Changed regexp to accept both http and https url
- Update `self.requests` with value from `Session()`. This property when used in `parse_download_page` should never be `None`
- Fixes # .
```
```
```
```
=> Fix NoneType on self.requests. Add support to https url.

flexget/entry.py, flexget/plugins/modify/set_field.py, flexget/tests/test_misc.py, flexget/utils/template.py
If you want to manipulate a number field it is not currently possible.
- If set plugin templates evaluate to a type other than string, the type is not cast to a string.
- https://discuss.flexget.com/t/content-size-for-magnet-links-from-xml-feed/4572
```
set:
some_field: {{some_int_field/2}}
```
=> Allow `set` plugin can now set entry fields to types other than str

flexget/components/parsing/parsers/parser_guessit.py
The guessit parsing plugin doesn't recognize the "dd+5.1" audio quality, this pull request fixes that.
- when guessit audio_channels == "5.1" and guessit audio_codec == "Dolby Digital Plus" return audio quality "dd+5.1"
=> added support for dd+5.1 quality to guessit parser

flexget/components/trakt/trakt_list.py
I need that feature for myself.
Add support for `trending`/`popular` list for `trakt_list` plugin.
- Feathub #[40](https://feathub.com/Flexget/Flexget/+40).
```yml
trakt_list:
username: <trakt username>
list: popular # new values: trending, popular
type: shows  # allowed values for trending/popular list: movies, shows
```
=> add support for popular/trending list on trakt

flexget/components/sites/sites/rutracker.py
The rutracker.cr domain isn't a mirror of Rutracker anymore
- Removed rutracker.cr from mirrors list for rutracker
- Fixes #2358
=> Remove obsolete mirror from rutracker

flexget/plugins/filter/crossmatch.py
- Currently the crossmatch comparison is always case sensitive.  This will add the ability to do a case insensitive comparison with crossmatch
- Add case_sensitive to config schema - default to yes to maintain backward compatibility 
- Add case_sensitive parameter to entry_intersects function
- Add conditional to convert strings to lower case
- N/A
- Feathub #[74](https://feathub.com/Flexget/Flexget/+74).
```
crossmatch:
case_sensitive: no
```
```
flexget@vm1:/media/main/flexget$ flexget -c config.new.yml  --test execute
2019-03-27 23:06 INFO     manager                       Test mode, creating a copy from database ...
2019-03-27 23:06 INFO     manager                       Test database created
2019-03-27 23:06 VERBOSE  task_queue                    There are 1 tasks to execute. …
```
=> Add case_sensitive to Crossmatch

flexget/plugins/input/kitsu.py
Kitsu input doesn't support the types from the API, so if someone needs to add the series in one list and the movies in another one are pretty hard, this adds the `type` option similar to `my_anime_list` input.
- Adds `type` option to filter the results
- Types strings[]: 
- type.ona "ONA"
- type.ova "OVA"
- type.TV "TV"
- type.movie "movie"
- type.music "music"
- type.special "special"
=> [add] types to kitsu input

flexget/components/sites/utils.py
Currently it's not possible to find show `Travel Man: 48 Hours In...` using discovery+rarbg, because of the ending dots. I'm not sure where is better to strip them, so I've decided to do it globally in `NextSeriesEpisodes` plugin.
- if the show name contains `...` — the title without them would be added to `search_strings`
=> Remove '...' from text in sites.utils.normalize_scene()

flexget/components/sites/sites/descargas2020.py
Plugin stopped working after a feed modification
Plugin has been modified to reject a rewrite on download torrent urls 
- Fixes #2377
=> Fix descargas2020 plugin (#2377)

flexget/plugins/operate/cfscraper.py
cfscrape status is unclear. Latest changes to Cloudflare [have not been integrated](https://github.com/Anorov/cloudflare-scrape/pull/206#issuecomment-487772381) breaking cfscrape.
[Cloudscraper](https://github.com/VeNoMouS/cloudscraper) is the recommended up to date alternative and works with latest Cloudflare changes
Transparent for the user (except the dependency change of course).
=> Replace cfscrape by cloudscraper

flexget/components/trakt/trakt_list.py
Currently lists `popular` and `trending` produce TONS of items, and you need to do additional magic to get just TOP10 or so.
- added `limit` configuration parameter into `trakt_list`
=> Add limit for trakt_list

flexget/plugins/clients/transmission.py
Cleanup of torrents may remove finished, but not moved to final location torrents.
I use dedicated miniserver for downloading new torrents. Miniserver uses local storage for unfinished torrents, but move fully downloaded torrents to main NAS. Sometimes torrent cannot be moved to final location due to various reasons. Currently I cannot distiguish between completed and moved to final destination torrents and finished but failed to move to proper location torrent.
This change add `transmission_error_state` attribute with human-readable status. In particular,  error status `local_error` means that files cannot be created locally or cannot be moved to final location.
=> [add] from_transmission: Add 'transmission_error_state'

flexget/components/trakt/trakt_list.py, flexget/plugins/input/anidb_list.py, flexget/plugins/input/gazelle.py, flexget/plugins/input/inputs.py, flexget/plugins/input/kitsu.py, flexget/plugins/input/letterboxd.py, flexget/plugins/input/limit.py, flexget/plugins/input/next_sonarr_episodes.py, flexget/plugins/operate/digest.py, flexget/plugins/operate/sequence.py, flexget/task.py, flexget/tests/cassettes/test_trakt.TestTraktList.test_trakt_movies, flexget/tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_show_collected_progress, flexget/tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_show_watched_progress, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_get_list, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_strip_dates, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_simple, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_task, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_remove, flexget/tests/test_cached_input.py, flexget/tests/test_limit.py, flexget/utils/cached_input.py
We needed a way to limit entries created by trakt_list plugin #2386, #2388. We added a limit option to that plugin. This is an experiment to see if we could use a more generic approach to limit any input plugin, while still allowing the optimization of not having the input plugin request more than is necessary from its source. (i.e. limiting HTTP or database requests)
- Allows input plugins to be generators
- Adds 'limit' plugin, which takes a limit amount, as well as the configuration for another input plugin
```
limit:
amount: 5
from:
rss: http://blah.com
```
=> Limit plugin

flexget/plugins/operate/cfscraper.py
Include ordered headers to prevent CloudScraper from hitting ReCaptcha, per https://github.com/VeNoMouS/cloudscraper/issues/38#issuecomment-491100011
- Fixes #2387 .
=> [Fix] cfscraper failing to parse due to reCaptcha

flexget/plugins/clients/transmission.py
Need to kick transmission to finally move downloaded torrents data to new location.
As additional follow-up for PRs #2394 and #2410. If transmission failed to move file from 'incomplete' directory to final location, it is required to somehow push transmission to finish job.
example usage (with PR #2410 merged)
Note: `isfile('/path/transmission/incomplete/' ~ title)` will match only finished, but not moved files as for incomplete files transmission add suffix (by default).
``` YAML
kick-stalled-torrents:
from_transmission:
username: '{? trans.usr ?}'
password: '{? trans.pwd ?}'
disable: [seen, seen_info_hash]
no_entries_ok: yes
if:
- transmission_error_state == 'local_error': accept
- isfile('/path/transmission/incomplete/' ~ title): accept
transmission:
username: '{? trans.usr ?}' …
```
=> [add] transmission plugin: added ability to move torrent data to new location

flexget/utils/template.py
Sometimes transmission do not report any error when files are not moved to final location from 'incomplete' directory. Need simple check for presence of files on filesystem when cleaning completed torrents
As follow-up for PR #2394. Added `is fs_file` jinja test. Also added `fs_dir` and `fs_link` tests for additional flexibility. 
example:
``` YAML
clean-torr:
from_transmission:
username: '{? trans.usr ?}'
password: '{? trans.pwd ?}'
disable: [seen, seen_info_hash]
no_entries_ok: yes
if:
- transmission_error_state == 'local_error': reject
- transmission_progress < 100: reject
- ('/path/transmission/incomplete/' ~ title) is fs_file: reject
- transmission_date_added + timedelta(minutes=95) < now: accept
transmission:
username: '{? trans.usr ?}'
password: '{? trans.pwd ?}'
action: remove
```
=> Implemented new jinja tests

flexget/components/history/api.py
Making Total Count explicitly 0 makes it easier for me to handle infinite scroll for this plugin from the web-ui. 
- Add pagination headers in empty response from GET history api endpoint
=> [change] Add pagination headers to history api even if no items are present

README.rst
There are more chat options than gitter and irc now
- Change it to the page on the website with all the chat options.
=> Fix Chat link

flexget/components/thetvdb/api_tvdb.py
- fallback to retrieve the first episode's aired date when series's first aired date not specified
TheTVDB stopped providing the series's first aired date correctly. This fix is to fallback to getting the aired date from the first episode if it is not available.
- If `first_aired` is not set, query TheTVDB API for the first episode and use it's `first_aired` value
=> [fix] thetvdb component retrieve first aired date

flexget/plugins/clients/qbittorrent.py
I switched from Transmission to qBittorrent and I found that I couldn't add torrents in a paused state.
- Added `add_paused` token to qBittorrent configuration that allows torrents to be added in paused state
```YAML
my_qbittorrent_server:
qbittorrent:
host: 127.0.0.1
port: 8080
path: /download/
add_paused: yes
```
=> Allow to add paused torrents to qbittorrent

flexget/manager.py
Typo.
- Fix a typo: "INTERUPT".
- Use lazy string interpolation.
=> Fix typo in manager.py

flexget/components/sites/sites/yts.py
YTS site component is broken in python 3
- replace with a compatibility libraries
- No open yet
```
AttributeError: module 'urllib' has no attribute 'quote'
```
=> [fix] python 3 support to yts site component

flexget/plugins/filter/regexp.py, flexget/tests/test_regexp.py
As discovered on the forum, there are cases where the regexp 'rest' operation does not work correctly. https://discuss.flexget.com/t/accepted-entries-are-rejected/4833
There were 2 edge cases I identified and fixed:
- If the first regexp operation(s) run matched _all_ of the entries, any entries not matched by subsequent operations would be considered 'rest' (even though there should not be _any_ 'rest' in this case.)
- If there were no operations defined, and only rest was used, (stupid case I know,) the 'rest' operation would be ignored.
- Fixes https://discuss.flexget.com/t/accepted-entries-are-rejected/4833
=> [fix] regexp: Fix edge cases with 'rest' operation

flexget/plugins/input/anilist.py
Migrated my personal list from MyAnimeList to AniList
- Based off the existing MyAnimeList plugin since already had some experience with it and AniList works similarly.
- Feathub #[80](https://feathub.com/Flexget/Flexget/+80).
```yaml
anilist:
username: <value>
status:
- <current|planning|completed|dropped|paused|repeating>
- <current|planning|completed|dropped|paused|repeating>
...
release_status:
- <all|finished|releasing|not_yet_released|cancelled>
- <finished|releasing|not_yet_released|cancelled>
...
format:
- <all|tv|tv_short|movie|special|ova|ona>
- <tv|tv_short|movie|special|ova|ona>
...
```
or simplified format:
```yaml
anilist: <username>
```
which assumes the default values
```yaml
status: ['current', 'planning']
release_status: all
format: all
```
=> [add] New AniList input plugin

flexget/components/sites/sites/passthepopcorn.py
Lets user configure grouping search parameter,
as compared to default implicit 'grouping=1'
By default, passthepopcorn groups search results by movie id, influencing how results are returned using the original `order_by` parameter.
For example, searching for a movie by string, ordering by seeders, will return the first entry in the highest seeded group. So searching for 'get', sorted by seeders, returns 
'Get Out (2017)  x264 / MKV / Blu-ray / 720x302 / Scene ', rather than 
'Get Out (2017) x264 / MKV / Blu-ray / 1080p / With Commentary'
```
passthepopcorn:
grouping: no (default yes)
```
This is my first pull request for the project, feel free to let me know of any problems.
=> [add] passthepopcorn sort by individual torrents

flexget/components/sites/sites/horriblesubs.py
`horriblesubs` fail because it requires the old scraper lib as dependence, so not make sense have tow different libs to do the same, also it should use the `cfscraper` plugin to have that responsibility unify
- Remove custom horriblesubs scraper and use task request that has `cfscraper` instance
- No Yet
=> [fix] remove horriblesubs scraper in favour of cfscraper plugin

flexget/plugins/filter/exists_movie.py, flexget/tests/test_exists_movie.py
Currently `exists_movie` has a bug on movies with the same name but different year, there cases like `The Lion King (1994)` and  `The Lion King (2019)` and currently `exists_movie` reject it due has the same name, this PR fix that bug
- add the year of the movie to the key identifier to allow movie with same neam and different year
- No open issue yet
```
adding: The Lion King 1994
adding: Pokémon Detective Pikachu 2019
adding: Ant-Man and the Wasp 2018
Teen Titans Go! To the Movies 2018
2019-10-14 12:34 VERBOSE  task          copy-movies     REJECTED: `Teen Titans Go! To the Movies (2018)[1080p]` by exists_movie plugin because movie exists
Steven Universe: The Movie 2019
2019-10-14 12:34 VERBOSE  task          copy-movies     REJECTED: `steven.universe.the.movie.2019.hdrip.720p.latino` …
```
=> [fix] exists_movie support movie same name different year

flexget/components/trakt/next_trakt_episodes.py
Flexget gave an error when using the 'aired' context. This was because the wrong variables were set.
- renamed the variables to the correct names
=> correct season and episode variable for trakt aired

flexget/components/sites/sites/piratebay.py
Currently the Piratebay plugin gives errors when scanning their site, because of advertisements that are also marked as class="detLink". This change detects if the ULed user was piratebay, which indicates that it is an advertisement.
```
DEBUG    utils.requests Series-Trakt    GETing URL ... with args () and kwargs {'allow_redirects': True, 'timeout': 30}
DEBUG    plugin        Series-Trakt    decorator caught ValueError. handled traceback:
File "flexget/plugin.py", line 119, in wrapped_func
return func(*args, **kwargs)
File "flexget/components/sites/sites/piratebay.py", line 164, in search
entry['torrent_seeds'] = int(tds[-2].contents[0])
ERROR    discover      Series-Trakt    Error searching with piratebay: invalid literal for int() with base 10: …
```
=> Prevent errors on PirateBay plugin when scanning ads

flexget/tests/test_series.py, flexget/tests/test_utils.py, flexget/utils/tools.py
Handling `"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."` when trying to mix and match within `series` plugin (see addressed issue for further details)
- Added `list` to the last conditional to allow for lists to override \ be overridden if a merge is not possible.
- Fixes #2453.
=> Handle merge of lists with other types. Override instead

flexget/plugins/input/anilist.py
Bug report. Previous method was limited to 50 entries, this patch handles the pagination
- Changed query to use an object able to carry more elements (500 instead of 50)
- Handle pagination if needed
- Add optional `title_only` option to schema for slimmer result
```diff
anilist:
username: <<string | required>>
status: <<enum | optional>>
release_status: <<enum | optional>>
format: <<enum | optional>>
+ title_only: <<boolean | optional>>
```
- Fixes #2471 .
=> [fix] anilist: Larger lists no longer limited to the first 50 items

flexget/components/thetvdb/api_tvdb.py
TVDB changed the key name and type for episodes in their v3 update from `'director': 'string'` to `'directors': ['array']`
[As noted on their documentation](https://api.thetvdb.com/swagger#!/Episodes/get_episodes_id):
> Returns the full information for a given episode id. **Deprecation Warning:** The director key will be deprecated in favor of the new directors key in a future release.
Which causes the following error during episode metadata lookup:
`WARNING  api_tvdb      task     Error while updating from tvdb ('director'), using cached data.`
- Renamed field and convert list to string
=> [fix] Update TVDB Episode Schema

Dockerfile
This is the updated Dockerfile I use with success for a while. The one in develop uses python2 which is obviously not working anymore.
I am pulling the webUI v2 from the last release on respective GitHub, instead of building it. This could be changed if needed.
I don't build webUI v1 because it is deprecated.
I am using it mounting my config folder in /root/.flexget and with the command `daemon start`.
=> update Dockerfile to use python3 and add webUI v2

flexget/plugins/output/symlink.py, flexget/tests/test_symlink.py
I wanted to be able to override target name when using symlink as it can be done with move plugin.
- Add entry link_to property to set the link target name
- Add config rename in order to override target link name
- Clean target link with pathscrub
```
symlink:
link_type: hard
existing: ignore
to: /Series/{{series_name}}/Season {{series_season|pad(2)}}
rename: '{{series_name}} - {{series_id}}{{filename | pathext}}'
```
```
2019-11-23 10:40 VERBOSE  symlink       sort_series     hardlink `/download/S.W.A.T.2017.S01E21.FRENCH.720p.WEB.H264-AMB3R/s.w.a.t.2017.s01e21.french.720p.web.h264-amb3r.mkv` to `/Series/S W A T 2017/Season 01/S W A T 2017 - S01E21.mkv`
```
=> Add rename config on symlink as move plugin

flexget/logger.py
Fix crashes with some non ascii data. To reproduce:
```yaml
test_task:
series:
- בדיקה
```
<details><summary>Output</summary>
<p>
```
/Users/orcarmi/PycharmProjects/Flexget/venv/bin/python /Users/orcarmi/PycharmProjects/Flexget/flexget_vanilla.py --debug --test execute --tasks test_task
2019-11-28 00:44 DEBUG    manager                       Figuring out config load paths
2019-11-28 00:44 DEBUG    manager                       Adding virtualenv path
2019-11-28 00:44 DEBUG    manager                       Found config: /Users/orcarmi/PycharmProjects/Flexget/config.yml
2019-11-28 00:44 DEBUG    manager                       Config file /Users/orcarmi/PycharmProjects/Flexget/config.yml selected
2019-11-28 00:44 DEBUG    manager                       sys.defaultencoding: utf-8
2019-11-28 …
```
=> [fix] set utf-8 as default encoding for RotatingFileHandler

flexget/plugins/daemon/web_server.py, flexget/ui/v2/__init__.py
Webui v2 was broken if you specify a base url. This is part of the fix,  Flexget/webui#43 is the rest
- Really all that is happening is instead of spitting on html, webui webpack build generates a jinja template that will accept `{{ base_url }}`.
- Also fixes an issue so that  all webui paths should be using index.html.  (otherwise hard refreshes don't work)
- Flexget/webui#24
This can (and should) be merged before the webui pr as it's basically a noop on older builds of webui.  The other way around is not the case.
=> [fix] web server inserts base_url into webui v2

flexget/components/thetvdb/api_tvdb.py, flexget/components/thetvdb/thetvdb_lookup.py, flexget/tests/cassettes/test_series_api.TestSeriesRootAPI.test_series_lookup_param, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_lookup, flexget/tests/cassettes/test_thetvdb.TestTVDBLookup.test_no_posters_actors, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBLanguages.test_series_lookup_with_language, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBSeriesActorsLookupAPI.test_tvdb_series_lookup_with_actors, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBSeriesLookupAPI.test_tvdb_series_lookup, flexget/tests/cassettes/test_tvdb_lookup_api.TestTVDBSeriesLookupAPI.test_tvdb_series_lookup_by_id, flexget/tests/test_thetvdb.py
TheTVDB returns posters in a random order and Flexget caps the list to 5 entries. I like to use the main poster (curated to be used by the site) on my notifications and given the aforementioned actions, it's not always on the list, and when it is there is no way to determine which entry t is.
- ~~[unrelated] Changed URL for the posters CDN to the new one post TheTVDB's v3 migration. There are currently 301 redirects in place at the old URL but they did recommend changing it wherever possible.~~
- Request the main poster path from the `/series/{id}` endpoint and start the list with it
- Append up to 5 posters to the list (not 4 just in case the main one is not defined)
- Trim the list down to 5 entries
- Fixes *my OCD*.
=> [change] `tvdb_lookup` - Always have the main poster as the first entry of `tvdb_posters`

flexget/plugins/clients/qbittorrent.py
Plugin qBittorrent stopped working with qBittorrent v4.2
- Update qBittorrent WebAPIm, [Web API Documentation](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation)
- Fixes #2522
=> Support qBittorrent v4.1+, fixes #2522

flexget/components/managed_lists/lists/pending_list/api.py, flexget/components/managed_lists/lists/pending_list/db.py, flexget/components/tmdb/tmdb_lookup.py, flexget/tests/api_tests/test_pending_list_api.py, flexget/tests/conftest.py
I'm adding some bulk operation features to webui (Flexget/webui#54) so this seemed better than making a lot of requests. Eventually I want to just make graphQL or gRPC endpoints for webui to use and these batch operations will be cleaner but that's a later activity. 
- Add new endpoint `PUT /pending_list/{list_id}/entries/batch` for bulk approving, rejecting pending list entries
- Add new endpoint `DELETE /pending_list/{list_id}/entries/batch` for bulk removing removing pending list entries
=> [Add] pending list batch operation and deletion endpoint

flexget/components/notify/notifiers/gotify.py
Currently using a hack script to forward flexget emails to [Gotify](https://github.com/gotify/server) instance. We should have more FOSS notification options :smile: 
Based off of Pushbullet plugin. Gotify publishes messages via https://push.example.com/message?token=GOTIFY_TOKEN, and messages take the following format:
```
{ "title": "Some title", "message": "some message", "priority": 4 }
```
The `priority` field is optional (we use a default of 4, since the Android client mainly looks at priorities between 0 and 7, though this can be any integer.
```
notify:
task:
always_send: yes
title: "Flexget {{task.name}} summary"
via:
- gotify:
url: https://push.example.com/message
token: TOKEN
priority: 4
```
**Failed config validation (duplicate priority declared):**
```
$ flexget --loglevel …
```
=> Implement Gotify notification plugin

flexget/components/trakt/trakt_calendar.py
When setting title and url fields, `original_title` and `original_url` are set, which are used in the eq comparison.
This change delays setting title and url until they've actually been finalized.
=> trakt_calendar: correctly set title and url to avoid incorrect duplication

flexget/components/series/metainfo_series.py, flexget/components/series/series.py, flexget/plugins/filter/best_quality.py, flexget/plugins/filter/timeframe.py, flexget/plugins/filter/upgrade.py, flexget/plugins/metainfo/media_id.py, flexget/plugins/metainfo/metainfo_movie.py, flexget/tests/cassettes/test_metainfo.TestMetainfoSeries.test_jinja_tvdb, flexget/tests/test_metainfo.py, flexget/tests/test_nfo_lookup.py, flexget/tests/test_timeframe.py, flexget/tests/test_upgrade.py
None
- Automatically generate a content id based on entry type if the entry hasn't been parsed by internal or guessit
- Fixes #2071
=> auto-generate a somewhat reasonable content id if there isn't one

flexget/api/app.py, flexget/components/managed_lists/lists/entry_list/api.py, flexget/components/managed_lists/lists/entry_list/db.py, flexget/components/managed_lists/lists/movie_list/api.py, flexget/components/managed_lists/lists/movie_list/db.py, flexget/tests/api_tests/test_entry_list_api.py, flexget/tests/api_tests/test_movie_list_api.py
Add the same batch delete stuff from #2535 to entry list and movie list
=> [Add]: Movie list and Entry list batch remove endpoints

flexget/components/managed_lists/lists/movie_list/api.py, flexget/components/trakt/api.py, flexget/components/trakt/api_trakt.py, flexget/tests/api_tests/test_trakt_lookup_api.py
You really don't need a trakt  title for lookup so making it a query parameter just seemed more consistent
- add `GET /trakt/movies` and `GET /trakt/series`
- redirect `GET /trakt/movies/{title}  => /trakt/movies?title={title}`
- redirect `GET /trakt/series/{title}  => /trakt/series?title={title}`
=> [change]: Allow trakt lookup api without title

dev-requirements.txt, flexget/api/core/server.py
The old version didn't have seconds so it was messing up the Log Parser. Also pre-commit was complaining about the version of virtualenv so I upped it.
=> [Fix]: Properly parse timestamp in log api

flexget/components/trakt/trakt_calendar.py
Trakt API only allows up to 31 days.
- Automatically call the API the required number of times to get the full calendar.
=> [change] trakt_calendar: automatically handle more than 31 days

flexget/components/thetvdb/api_tvdb.py
Sometimes TVDB returns invalid firstAired dates causing
```2019-12-31 03:38:11 ERROR    lazy_lookup   SOME_TASK      Unhandled error in lazy lookup plugin: time data '5-8-6' does not match format '%Y-%m-%d'
File "/usr/local/lib/python3.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
func(self.store)
File "/usr/local/lib/python3.7/dist-packages/flexget/components/thetvdb/thetvdb_lookup.py", line 123, in lazy_series_lookup
return self.series_lookup(entry, language, self.series_map)
File "/usr/local/lib/python3.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/flexget/components/thetvdb/thetvdb_lookup.py", line 113, in series_lookup
session=session, …
```
=> Fix tvdb firstaired

flexget/_version.py, flexget/plugins/daemon/web_server.py, flexget/ui/v1/__init__.py, flexget/ui/v2/__init__.py
Instead of getting rid of webuv1 right away (#2556), I'd like to move webui_v1 to `/v1/` and v2 to `/`
- Move `/` -> `v1`
- Redirect `/v1/api` -> `/api`
- Move `/v2` -> `/`
```yaml
web_server:
run_v1: yes
```
=> Move v2 to root

flexget/api/__init__.py, flexget/api/core/schema.py, flexget/plugin.py
Add an api endpoint to get config schemas, for use by the web editor.
- Schemas are available under /api/schema/
- All `$ref`s are rewritten to the actual uri that the referenced schema is available from
- `id` fields are added to each schema with their uri
=> Api schema

.github/RELEASE.md, .github/workflows/main.yml, .github/workflows/nightly.yml
I added this to webui when we were switching over to github actions so i figured I'd  add it over in main repo as well. Basically this gives the ability to kick off a github deployment (which is super easy to do in slack) as a way to do a manual release if necessary.
=> Add manual release github actions

.gitignore, flexget/api/app.py, flexget/api/core/tasks.py
- /api/tasks/execute was erroring if you passed a loglevel because of the casing
- add task_id to the events. This is just going to make my life easier in webui
=> Add task id to the execute api streaming events and fix loglevel

flexget/components/sites/sites/lostfilm.py
Since yesterday was getting this eror in log
> 2020-01-14 12:55:04 CRITICAL plugin        LostFilm        Received not 200 (OK) status
>2020-01-14 12:55:04 WARNING  task          LostFilm        Aborting task (plugin: lostfilm)
After this modification
```
-        if rss.get('status') != 200:
-            raise PluginError('Received not 200 (OK) status')
+        status = rss.get('status')
+        if status != 200:
+            raise PluginError('Received %s status instead of 200 (OK)' % status)
```
found out that actually http code was 301.
So finally fixing URL  to use https did the trick.
=> [FIX] http -> https in URLs

flexget/components/imdb/imdb_watchlist.py
When there's no match in the watchlist (specially when you're filtering by, let's say, 'mini series')
utils/cached_input.py throws an error because it tries to iterate a NoneType
just a replacing a plain return with return []
The error:
```
2020-01-31 21:47:44 VERBOSE  imdb_watchlist import-imdb No movies were found in imdb list: watchlist
2020-01-31 21:47:44 DEBUG    input_cache   import-imdb storing entries to cache imdb_watchlist_7e30027a73709633227b63e7a3a7fc01 
2020-01-31 21:47:44 CRITICAL task          import-imdb BUG: Unhandled error in plugin imdb_watchlist: 'NoneType' object is not iterable
<snip>
File "/opt/venv/flexget/lib/python3.7/site-packages/flexget/utils/cached_input.py", line 204, in __init__
self.iterable = iter(iterable)
│ …
```
=> imdb_watchlist:  return empty list when nothing's found

flexget/plugins/clients/transmission.py
To prevent accidental downloading of magnet links which are added as paused.
On high speed connections setting paused to `False` might cause the magnet file to be downloaded event though `add_paused` was defined. This issue is noticeable especially when transmissionrpc times out.
Changing the paused status (Flexget#462) is meant to address an issue with handling `content_filename` with magnet links but there is no need to change the status if `magnetization_timeout` is zero.
Original issue:
https://web.archive.org/web/20150515004451/http://flexget.com/ticket/2911
If content renaming or selective downloading is used with magnet links, and `add_paused` is `true`, then `magnetization_timeout` must be also set to a value greater than zero.
```yaml
transmission:
add_paused: true …
```
=> [fix] Prevent accidental downloading of magnet links

flexget/components/status/db.py
Since we store the the datetimes without timezones, when they are json encoded in the api, it is assumed that they are in UTC (which they aren't). This adds the system local timezone before json encoding,  so that it will properly offset the time
=> [fix] convert to timezone aware datetime for execution time in the api

flexget/components/trakt/trakt_lookup.py
This is to fix #2583. Trakt lazy lookups could not be serialized, because they were passing functions in the parameters to the lazy lookups.
This plugin was sorta confusing, I maybe made it slightly better than it was, but there is still room for improvement.
=> Fix trakt lazy lookup serialization

flexget/components/sites/sites/filelist.py
Recently filelist changed the login procedure on the site, making the plugin unusable. 
- fetched the "validator" key that is expected for a successful login from the login page
- search method now returns a list instead of a set, this way the order_by defined in config is kept
- no issue filled yet, however it was posted on the [forum](https://discuss.flexget.com/t/filelist-ro-search-plugin-broken/5024).
=> fix login for filelist search plugin

flexget/entry.py, flexget/plugins/operate/digest.py, flexget/task.py, flexget/tests/test_digest.py
While adding some type hints, I realized there was already an `EntryState` enum, and thought maybe we should start actually using it to store entry state.
There was some hacky stuff in digest plugin regarding entry state, I didn't even try to fix that in this pull, just updated it to still work.
=> Switch to using Enum to track Entry state

Dockerfile
Current Docker image contains build deps and is unnecessary big.
- Use multi-stage building to separate build from install. The resulting image is ~300MB instead of ~800MB.
- Use official python image (based on alpine) instead of installing python on an alpine image
=> Dockerfile: multi-stage building

flexget/utils/requests.py
Limit only for get requests so cloudflare challenge gets answered timely (#2614)
Long timeout seems to reset the cloudflare challenge
- Rate limiting only for get-requests so cloudflare gets the answer directly after the challenge
=> Rate-Limit only for GET-Requests

flexget/plugins/input/anilist.py
Found out some entries in Anilist don't have a proper English title (there are a number of valid reasons), which causes a `None` entry to be added to the alternate_name list
- Evaluate if the English title is provided and not already in the alternate_name \ synonym \ a.k.a. list provided before inserting it on first position.
=> [Anilist] Evaluate if the english title is provided

flexget/__init__.py, flexget/manager.py, flexget/tray_icon.py
Making Tray icon wait for daemon to start can needlessly cause Flexget to hang until timeout is met on non daemon command. hooking manager.shutdown will make the first event trigger the tray icon check.
=> Don't make tray icon wait for daemon start

flexget/plugins/input/anilist.py
Same as #2627 but based on the latest version to avoid merging conflicts.
Started getting a crash after creating custom lists on AniList
- ~~Skip custom lists since their entries are duplicates of status lists~~
- Added optional plugin parameter to filter AniList custom lists.
- Fixes #2626 .
```diff
anilist:
user: UserName
status:
- <current|planning|completed|dropped|paused|repeating>
- <current|planning|completed|dropped|paused|repeating>
...
release_status:
- <all|finished|releasing|not_yet_released|cancelled>
- <finished|releasing|not_yet_released|cancelled>
...
format:
- <all|tv|tv_short|movie|special|ova|ona>
- <tv|tv_short|movie|special|ova|ona
...
+ list:
+   - List Name
+   - Other List Name
```
=> [add] AniList: Option to filter by custom lists

flexget/plugins/clients/pyload.py
Signed-off-by: Stefan Bischoff <stefan.bischoff@9plus.de>
Fixes #2641 
packaging is now optional. if not found, the pyload plugin assumes, the old api should be used
=> Make pyload plugin work without packaging installed

flexget/components/tmdb/api.py
"imdb_id" is already an optional parameter for lookup in TMDB API but is not included in the parser and so is never passed to the function.
Seems to be a copy-paste error with "tmdb_id" showing twice.
- add "imdbID" in the parser for TMDB API
- remove duplicate "tmdbID" in the parser for TMDB API
- "imdbID" from an API call is never parsed and not usable by function
=> Correcting TMDB api preventing "imdb_id" parsing

flexget/plugins/clients/transmission.py
Currently there is no way to differentiate between a tracker error due to temporary downtime, vs permanent deletion of the torrent, making it difficult to automate cleanup tasks.
- Adds [`errorString`](https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt#L195) to the whitelist of Transmission RPC fields to be populated on entries.
=> [add] from_transmission: Add 'transmission_errorString'

flexget/components/imdb/db.py, flexget/components/imdb/imdb_lookup.py, flexget/components/imdb/utils.py, flexget/tests/test_imdb_parser.py
This is the highest voted request on Feathub and social distancing is super boring.
- Add a imdb_plot_keywords to imdb_parser
- Add required table and FK mappings to the DB/ORM
- N/A
- Feathub https://feathub.com/Flexget/Flexget/+50.
This is simply a new field in the entry.
`--dump` output
```
-- Accepted: ---------------------------
title            : The Usual Suspects
url              : "http://fake.url"
original_url     : "http://fake.url"
accepted_by      : if
imdb_actors      : {'nm0000286': 'Stephen Baldwin', 'nm0000321': 'Gabriel Byrne', 'nm0001125': 'Benicio Del Toro', 'nm0001629': 'Kevin Pollak', 'nm0000228': 'Kevin Spacey', 'nm0001590': 'Chazz Palminteri', 'nm0000592': 'Pete Postlethwaite', 'nm0000751': 'Suzy Amis', 'nm0002064': 'Giancarlo Esposito', 'nm0000445': 'Dan Hedaya', …
```
=> Add IMDB top 5 plot keywords to imdb_lookup

flexget/tray_icon.py, requirements.in, requirements.txt
Pillow needs compilation which hurts Flexget's compatibility.
- Removed `pillow` and `pystray` from deps. If someone wants to run the tray icon, they can install them manually.
- Fixes #2651
=> [fix] Removed pillow and pystray as dependencies

flexget/plugins/input/torznab.py
The search should use the search_strings in discovery if available.
- Added search_strings to the search query
=> Use search_strings in search if available

flexget/components/sites/sites/newznab.py
Newznab indexers won't accept wrong parameter
The Newznab plugin is sending the wrong parameter for the IMDB id in it's request. Newznab is expecting to receive _imdbi_ but this plugin is sending it as _imdb_id.
Here the url to the newznab api: https://newznab.readthedocs.io/en/latest/misc/api/?highlight=imdbid#movie-search
- Just changed the parameter for the request to _imdbid_
=> rewrite imdb_id to imdbid

.github/workflows/main.yml, .github/workflows/release.yml
Currently the release script isn't working, hopefully this fixes. 
I think the issue has been that for whatever reason, skipped steps used to not show up in the checks list but they've started show up. And the way the deployment API works, deploys will fail if there are unsuccessful checks on the PR (and with the release skipped check showing up on every commit, that's considered not passing). We're not seeing this problem over on webui because webui release script is a seperate workflow. The reason it wasn't on this repo, was to make sure that we ran the tests before making a release. This made since prior to the change to using the deployment API, but it's not necessary now. So hopefully this fixes. the issue
=> Fix deploy

flexget/components/ftp/sftp.py, flexget/components/ftp/sftp_client.py
The original SFTP plugin is a bit of a spaghetti code mess. I've split it into a couple of classes to more make it easier to follow.
- Create a SftpClient class and move inline PySftp node handlers into their own class as well.
SFTP Upload
```
2020-05-10 19:00:34 DEBUG    manager                       Figuring out config load paths
2020-05-10 19:00:34 DEBUG    manager                       Found config: /Users/password/Flexget/../config.yml
2020-05-10 19:00:34 DEBUG    manager                       Config file /Users/password/Flexget/../config.yml selected
2020-05-10 19:00:34 DEBUG    manager                       sys.defaultencoding: utf-8
2020-05-10 19:00:34 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-05-10 19:00:34 DEBUG    manager …
```
=> Refactor SFTP plugins to be more maintainable

flexget/plugins/filter/crossmatch.py
Avoids running the from input plugin if no entries to check. This is very useful if, for example, the from is using the "from_task" plugin. This will avoid running the task in the "from_task" if no entries exists to be matched.
- Check the len of the entries iterator before running the from in crossmatch
=> Avoids running crossmatch from if no entries

flexget/api/app.py, flexget/api/core/authentication.py, flexget/api/core/cached.py, flexget/api/core/plugins.py, flexget/api/core/tasks.py, flexget/components/irc/api.py, flexget/components/pending_approval/api.py, flexget/components/seen/api.py, flexget/components/series/api.py, flexget/components/status/api.py, flexget/components/thetvdb/api.py, flexget/components/tmdb/api.py, flexget/components/trakt/api.py, flexget/components/tvmaze/api.py, requirements.in, requirements.txt
Flask-RESTPlus is abandoned, and is no longer compatible with the latest version of  werkzeug, on which it depends. The community has forked the project, and created Flask-RESTX, which seems to be a drop-in replacement.
- change `flask-restplus==0.10.1` out for `flask-restx==0.2.0` (the latest stable release of flask-restx).
- change all references to `flask_restplus` to `flask_restx`
- Fixes https://github.com/Flexget/Flexget/issues/2681 .
- The API test `test_crash_logs_without_crash_log` fails, but the same seems to happen with `develop`, so I think that test was already broken
=> Switch from flask-restplus to flask-restx

requirements.in, requirements.txt
Solving dependency conflict between Flexget and CloudScraper
- Updated `pyparsing==2.2.0` to `pyparsing==2.4.7` on `requirements.in` and `requirements.txt`
- Fixes #2666 .
=> Compatibility update for CloudScraper 1.2.40

flexget/components/sites/sites/site_rutracker.py, flexget/tests/test_urlrewriting.py
Get magnet url from rutracker.org topics.
- get torrent hash from topic id: uses https://api.t-ru.org to get topic data
- use it to reconstruct a magnet link
rutracker.org has an atom feed: http://feed.rutracker.cc/atom/f/0.atom 
I added a test in `tests/test_urlrewriting.py`. Not sure it's the best way to do it (and it requires online access: don't know if we want to mock the network call nor how to do it.
=> [add] rutracker.org topic pages urlrewrite

flexget/components/sites/sites/filelist_api.py
Fixes a crash in the new `filelist_api` plugin:
```
File "/usr/lib/python3.8/site-packages/flexget/task.py", line 535, in __run_plugin
result = method(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/flexget/event.py", line 22, in __call__
return self.func(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/flexget/plugins/input/discover.py", line 294, in on_task_input
return self.execute_searches(config, entries, task)
File "/usr/lib/python3.8/site-packages/flexget/plugins/input/discover.py", line 134, in execute_searches
search_results = search.search(task=task, entry=entry, config=plugin_config)
File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 127, in wrapped_func
return func(*args, **kwargs)
File …
```
=> [fix] filelist_api: NameError: name 'valid_extras'

dev-requirements.txt, flexget/api/app.py, flexget/api/core/authentication.py, flexget/api/core/user.py
* Currently we use the version endpoint to determine whether or not you are logged in on webui. This initial call will block rendering of everything until resolved. The version endpoint has to call out to PyPy which is not great in places that it takes a while to resolve. So instead i made a dedicated endpoint to use for this purpose that doesn't really do anything at all other than check auth. 
- #2725 (not fixed as i still have to make webui changes)
=> [add] /user/token to check if you are logged in

flexget/components/sites/sites/ettv.py
ETTV has moved
- add ettvcentral.com to the list of ETTV domains
=> add ettvcentral.com domain to ettv rewriter

flexget/plugins/internal/api_rottentomatoes.py, update-changelog.py
- Use raw strings for regexp
- Use `==` for comparison with literrals
Also:
- add `search_string` initialization to suppress some (false positive) linter warnings for possible unbound use.
- Convert some strings using `.format()` to [f-strings](https://www.python.org/dev/peps/pep-0498/), for readability
-
- 
- Fixes #2662 .
```
```
```
```
=> Fix python3.8 deprecation warnings

flexget/plugins/input/anilist.py
Discovered that site entries could have empty fields, usually ones added from very early announcements or teasers. That would result in exceptions due to parsing errors since some fields were taken for granted.
- Replaced most direct references to dict keys with `dict().get()`
- Convert to string before performing case operations to avoid `NoneType` exceptions
- Changed `al_links` output:
- From Dicts inside a List: `[{'site': '*site_name*', 'url': '*site_url*'}, ... ]`
- To single Dict: `{'*site_name*': '*site_url*', ... }`
- Alphabetize `Entry()` fields to improve code readability
=> [fix] `anilist`: Exception if field is not set on the site

flexget/manager.py
I found this case when installing the latest version of flexget. 
It defaults to an empty string instead of, I presume, the previous default of `None`.
I'm not sure if it's worthwhile keeping the `None` as a case but figured it was the 
"safer" option just in case. Also feels like `if not self.database_uri` should be just enough as well?
Failing to start flexget from a fresh install from the latest version on Pypi
=> Handle both old and new case for database_uri

flexget/components/bittorrent/torrent_scrub.py, flexget/utils/bittorrent.py, flexget/utils/cache.py, flexget/utils/cached_input.py, flexget/utils/database.py, flexget/utils/json.py, flexget/utils/log.py, flexget/utils/qualities.py, flexget/utils/requests.py, flexget/utils/serialization.py, flexget/utils/template.py, flexget/utils/tools.py
Continuation of #2751, utils module
- Added type annotations to api module
- Changed some docstrings to better conform to [PEP257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)
- Renamed some variables that shadowed built-ins (checked usages to make sure nothing broke)
- `bitorrent.py`: Changed `decode_item()` to use the iterator from `tokenize()` rather than a partial `next()` callable (more readable IMHO)
- `requests.py`: Removed `**kwargs` from call of super (`requests.Session`), as it expects nothing
- `template.py`: Changed `locale.format()` to `locale.format_str`, as the format is deprecated
- `tools.py`: Refactored `convert_bytes` implementation to a more concise and readable one (IMHO)
- `simple_persistence.py`: Skipped, as deprecated
Note: in `tools.py`, …
=> Add type annotations to utils module

flexget/components/sites/sites/torrentz.py
torrentz due long request string return Bad request response and change dead [.eu](https://torrentz.eu) domain with [.pl](https://torrentz.pl).
Looks like between more requests/searches keep adding more `%20` spaces
- Remove/prevent unnecessary extra request spaces when have `extra_terms` configuration
- Change dead `.eu` domain with `.pl`
N/A
N/A
```
from:
- torrentz: 
reputation: good
extra_terms: lat
```
```
2020-10-24 12:04:28 ERROR    discover      download-movies-spanish Error searching with torrentz: Error getting torrentz search results: 403 Client Error: Bad Requests for url: http://torrentz2.is/feed?f=Kiki%27s%20Delivery%20Service%20%281989%29%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20latino
```
=> Fix extra spaces on torrentz with extra terms and change .eu domain

Dockerfile
There is a line with Python version in Dockerfile for deploying the web UI. `python:3-alpine` is now Python 3.9, this updates it accordingly.
=> Update dockerfile to Python 3.9

flexget/plugins/clients/qbittorrent.py
#2764 
- Added optional `skip_check` flag to skip hash checking.
- Defaults to false per [qBT API](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent)
- Fixes #2764 .
```diff
add_paused: yes
+ skip_check: yes
```
=> [add] qBittorrent: Optional `skip_check` flag

flexget/plugins/clients/transmission.py
Currently it's not possible to bypass the transmission queue
Added option to start torrents immediately
```
transmission action gets additional key 'start now'
```
=> [add] transmission - Added possibility to bypass queue in transmission

flexget/components/managed_lists/lists/sonarr_list.py
Handle when the title or id is not found in the entry object which means a match is not found.. However the lookup of shows in sonarr returns a show that already exists.
=> [change] Sonarr - Handle when the title or id is not found in the entry object

flexget/components/imdb/utils.py, flexget/components/managed_lists/lists/pending_list/pending_list.py, flexget/tests/test_pending_list.py
Add ability to include items which are pending approval to preform tasks such as
1.clean-ups if older then x days.
2. For shows/movies released on netflix the rating/score on imdb can be empty meaning some end up in pending approval. A few days later people have voted, if it is a high voted movie then having the ability to filter on "pending approval" items will allow you to auto approve if the rating changes.
```
list_get_pending:
pending_list:
list_name: "test_list"
include: "pending"
list_get_approved:
pending_list:
list_name: "test_list"
include: "approved"
list_get_all:
pending_list:
list_name: "test_list"
include: "all"
```
=> Pending list filter option

requirements.in, requirements.txt
fix warning when installing flexget via pip for yanked version of feedparser
- update feedparser version 6.0.1->6.0.2 in requirements file
- Fixes # [2775](https://github.com/Flexget/Flexget/issues/2775)
=> update feedparser version

flexget/api/app.py, flexget/api/core/authentication.py, flexget/api/core/cached.py, flexget/api/core/database.py, flexget/api/core/format_checker.py, flexget/api/core/plugins.py, flexget/api/core/schema.py, flexget/api/core/server.py, flexget/api/core/tasks.py, flexget/api/core/user.py, flexget/config_schema.py, flexget/manager.py, flexget/plugin.py
Continuation of #2751, `api` module
- Added type annotations to api module
- Changed "rel" links generation in `pagination_headers()` (equivalent results, obviously). To me, it's more readable compared to the template parameter replacement method, but, as it's just my opinion, I can revert it if you wish
- [`TypedDict`](https://docs.python.org/3/library/typing.html#typing.TypedDict) usage is wrapped inside `if TYPE_CHECKING` blocks, as it's available on versions >= 3.8.
- Adding `Session` annotation for API methods introduced "new" mypy warnings like the following (previously ignored, as inferred type was `Any` cause of missing annotations):
```Item "None" of "Optional[Session]" has no attribute "query"```
Should all go away when typing decorators that mess with the arguments is …
=> [change] API - Add type annotations to api module

flexget/plugins/input/torznab.py
Torznab can receive None value in child.text which leads to generating entry
with None value in description.
Unfortunately `entry.get('description', '')` construct which is used almost
everywhere can't return default value when 'description' key exists in entry but
its value is None.
I believe that better option would be to use different method to handle
defaults and don't count on input plugins to provide correct values, but it
would take major effort to fix everywhere.
=> [fix] torznab: Fix None value in description

flexget/plugins/clients/transmission.py
Very simple fix of broken `from_transmission` plugin by removing leftovers of `transmissionrpc` (`transmission-rpc` uses another structure).
- Fixes #2794 .
=> clients/transmission.py: fixed `from_transmission` plugin

Dockerfile
Pull correct transmission dependency as a followup to #2791 
- Replaces transmissionrpc by transmission-rpc on pip commands
- Explicitly specify the pulling registry of the base image while we are at it
=> Dockerfile transmission-rpc

flexget/components/ftp/sftp.py, flexget/components/ftp/sftp_client.py
I'm using the format `Series Name (Year)/{{Season Number}}/Series Name(Year).ext` to rename my series and upload them to the media server with the `sftp_upload`plugin.
All was working fine until a a new series appeared and the content wasn't uploaded because of the file `[Errno 2] No such file`. Another issue is that the original file was deleted from the origin computer
- Whenever there is a sftp file upload error, return before checking for the file deletion flag
- Check if parent directories of the file exist, and if not, create them
N/A. Let me know if an issue is needed and I can create it.
- N/A
```yaml
sftp_upload:
host: "{? sftp.host ?}"
username: "{? sftp.username ?}"
to: "{? sftp.tv_path ?}/{{ tvdb_series_name }}/S{{ tvdb_season | pad(2) }}"
delete_origin: yes
```
Before PR
``` …
```
=> Fix sftp_upload

flexget/ipc.py
There is a small typo in flexget/ipc.py.
Should read `timeout` rather than `timout`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, timout -> timeout

flexget/components/series/series.py, flexget/tests/test_series.py
In case a season pack was not using the main code path, its number was not added to the exclusion list and other episode from the same task would be accepted as well.
- Add an acceptance hook to all entries early in the filtering phase so any accepted entry which is a season pack will go through the logic of adding its number to exclusion list.
- Fixes #2849
=> [fix] series - Added hook to add season to accepted season on any entry acceptance

flexget/plugins/clients/transmission.py
- Extra files are not skipped when main_file_only is set
- files_wanted and files_unwanted need to provide indices. Previously, these were providing the File objects themselves from the file_list, which Transmission can't recognize.
- No issue raised. Noticed in my own environment.
- **May** fix #2806 - haven't tested as I don't use skip_files
None
None
Added debug line to verify. Previous:
```
2021-04-05 10:53:51 DEBUG    transmission  movies          applying changes {'files_unwanted': [File(name='Collateral.2004.1080p.BluRay.x265-RARBG/Collateral.2004.1080p.BluRay.x265-RARBG.mp4', size=2005951858, completed=0, priority='normal', selected=True), File(name='Collateral.2004.1080p.BluRay.x265-RARBG/RARBG.txt', size=30, completed=0, priority='normal', selected=True), …
```
=> [fix] Transmission file skipping with main_file_only

flexget/components/sites/sites/lostfilm.py
According to changes of rss feed we need to change regex to set poster id properly.
```
<?xml version="1.0" encoding="utf-8" ?>
<rss version="0.91">
<channel>
<title>LostFilm.TV</title>
<description>Свежачок от LostFilm.TV</description>
<link>https://www.lostfilm.tv/</link>
<lastBuildDate>Wed, 21 Apr 2021 00:34:19 +0000</lastBuildDate>
<language>ru</language><item>
<title>Город на холме (City on a Hill). Слишком белые и слишком глупые. (S02E04)</title>
<description><![CDATA[<img src="//static.lostfilm.win/Images/437/Posters/image.jpg" alt="" /><br />]]></description>
<pubDate>Wed, 21 Apr 2021 00:34:18 +0000</pubDate>
<link>https://www.lostfilm.win/mr/series/City_on_a_Hill/season_2/episode_4/</link>
</item></channel>
</rss>
```
- start using more generic regex …
=> [fix] [Lostfilm Plugin] Upd ate regex according to new feed version

flexget/components/series/series.py
As stated in the bug report:
Series setting from configure_series and series to be merged together
The main issue was on the merging of the configs, we where using the native dict update method, this updates all the properties, but also updates the lists, replacing them. So the solution was simple:
- Replace "update" with the "merge_dict_from_to" from flexget.util 
- Fixes #2863
- None
```
tasks:
test:
from:
mock:
- url: 'mock://127.0.0.1/item1'
title: "Show"
configure_series_alternate_name: ['ECSAN']
settings:
identified_by: sequence
alternate_name: ['SAN']
series:
- Show:
alternate_name: ['AN']
begin: 1
discover:
what: 
- next_series_episodes: yes
from:
- flexget_archive: yes
release_estimations: ignore
```
```
2021-04-26 12:46:48 VERBOSE  discover      test …
```
=> Merge configs from series dict

flexget/components/sites/sites/lostfilm.py
lostfilm.tv is banned in Russia. This patch allow to use [proxy](https://flexget.com/Plugins/proxy) plugin with LostFilm component.
Added ProxyHandler to feedparser handlers 
```
2021-04-23 21:52:58 VERBOSE  proxy         LostFilm        Setting proxy to {'https': 'http://login:password@proxy.server:8080'}
```
=> Added proxy support for feedparser

flexget/plugins/clients/transmission.py
Avoid flexget crash when rpc client raises exception
- The rpc client converting a json request and handling the decode erro, he does this raising a ValueError exception, added a handler to that. 
- Fixes #2811
```
tasks:
transmission_test:
from_transmission:
port: 9091
username: myusername
password: mypassword
```
```
2021-04-28 11:01:36 ERROR    transmission-rpc transmission_test Error: Expecting value: line 1 column 1 (char 0)
2021-04-28 11:01:36 ERROR    transmission-rpc transmission_test Request: "{"tag": 0, "method": "session-get", "arguments": {}}"
2021-04-28 11:01:36 ERROR    transmission-rpc transmission_test HTTP data: "<h1>403: Forbidden</h1><p>Unauthorized IP Address.</p><p>Either disable the IP address whitelist or add your address to it.</p><p>If you're …
```
=> [fix] transmission: Handle rpc client exception

flexget/tests/conftest.py, flexget/tests/test_pluginapi.py
Get rid of pytest warning
- sed yieild_fixtures to flxture
- Warning
=> Address pytest yield_fixures depecation warning

flexget/components/notify/notifiers/telegram.py
The chats sometimes can migrate to a new ID, for example when a group chat is converted to superchat, this would not allow to send more messages. 
- Handle the ChatMigrated exeption and capture the new chat ID, delete the old chat ID from the database and add the new one. Send the message to the new id
- Fixes #2771
```
tasks:
notify:
disable:
- seen
- retry_failed
notify:
entries:
title: "My Title"
message: "My Message"
what: accepted
via:
- telegram:
bot_token: "<<token>>"
parse_mode: html
recipients:
- { group: "<<group>>" }
```
```
2021-04-29 14:32:49 DEBUG    telegram.vendor.ptb_urllib3.urllib3.connectionpool notify          https://api.telegram.org:443 "POST /<<toke>>/sendMessage HTTP/1.1" 400 154
2021-04-29 14:32:49 DEBUG …
```
=> [fix] telegram notifier: Handles chat migrations

flexget/plugins/clients/qbittorrent.py
Handles qbittorrent existing torrent and returns a warning. Avoids plugin crash
- Return torrent hash and search it in qbittorrent, if exists return a warning and skip torrent adding. ~~Please note that this will not work with magnet links, they can be turn off with "magnets: no"~~
- Fixes #2701
```
tasks:
qbittorrent_test:
filesystem: /home/user/torrent
disable:
- seen
- retry_failed
qbittorrent:
path: /media/disk/downloads/
label: tv
port: 8080
```
```
2021-04-29 03:24:56 VERBOSE  task          qbittorrent_test ACCEPTED: `Black.Bear.2020.1080p.WEB.h264-RUMOUR` by accept_all plugin
2021-04-29 03:24:56 INFO     download      qbittorrent_test Downloading: Black.Bear.2020.1080p.WEB.h264-RUMOUR
2021-04-29 03:24:56 VERBOSE …
```
=> [fix] qbittorrent: handle existing torrent

flexget/plugins/internal/api_bluray.py
Flexget would crash if connection to blu-ray.com failed when trying to update movie data such as release date.
- Enclosed the request line in a `try:`
```diff
+            try:
-            movie_info_response = requests.get(self.url).content
+                movie_info_response = requests.get(self.url).content
+            except (requests.RequestException, ConnectionError) as e:
+                raise LookupError('Couldn\'t connect to blu-ray.com. %s' % self.url)
+                break
```
- Fixes #2462 .
=> [fix] Handle exception when api_bluray fails to get content

flexget/plugins/clients/pyload.py
Pyload is currently not working with packaging installed (on both stable and ng)
and it is probably not working on pyload-ng with or without packaging installed.
This PR should fix #2711 
What is wrong
=============
For stable
-----------
GET method for /getServerVersion will not work as we have to be logged in. This
returned completely wrong data which were later acted on.
For pyload-ng
-------------
This was working only when packaging was installed. In #2642 there was attempt
to work without packaging, but IMHO it simply turns the version checking off and
pyload is always considered non ng.
How to fix it
=============
I chose rather simple approach. We currently don't really need exact pyload
version. We only need to know if we are on stable or ng. And we can easily
detect it by …
=> Fix pyload with packaging installed and/or with using pyload-ng

flexget/plugins/clients/pyload.py
RSS plugin allows to use `group_links` option to generate one entry with multiple
URLs, but Pyload wasn't using it.
I was fighting with this for months before I checked the source code and have been using pyloads parsing feature instead. It never cross my mind that it wouldn't be implemented at all.
- Simply load `urls` from `entry` when present.
=> [change] Pyload: Support for Group Links

Dockerfile
avoid upstream break changes
install rpc library with `transmission-rpc>=3.0.0,<4.0.0`
=> add transmission-rpc version range

flexget/plugins/output/subtitles_subliminal.py
The last version of subliminal has an indentation issue in `addic7ed` and will be disable in the next release due a captcha error
https://github.com/Diaoul/subliminal/issues/1005#issuecomment-629037571
https://github.com/Diaoul/subliminal/issues/966#issuecomment-623117304
- Update subliminal fallback providers
- Remove `addic7ed` from fallback provider
- N/A
- N/A
```
N/A
```
```
2020-10-24 11:59:36 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)
```
=> Remove addic7ed from subliminal fallback providers

flexget/components/sites/sites/alpharatio.py
Better hande of invalid values in alpharatio
- handle invalid ints with try, try to replace invalid ',' with '.' if present
- Fixes #2812
=> [fix] alpharatio: handle invalid values

flexget/components/sites/sites/lostfilm.py
(Relatively) slow processing by current plugin version.
Errors in processing.
* Refined regexps to support episode names with brackets,
* Added several fallback options for parsing,
* Flexget "quality" is supplemented by audio and video codecs, rip source types (now all `quality` members are filled correctly),
* Clear errors report in case of the site authenticated error,
* Smaller `try:` blocks,
* Added direct configuration option for authentication on the site instead of
using 'head: cookie...' task parameter (the old way is still supported),
* Better logging (including 'trace', 'debug', and 'verbose' levels),
* Corrected entry attribute names `series_name_eng` -> `series_name_org` (LostFilm uses original language names, not English ones),
* Pre-filter results to avoid making two HTTP …
=> sites/lostfilm: heavy update

flexget/components/thetvdb/api_tvdb.py
Some errors my occur (I detected this because I had this error) if no name is detected in tvdb. The method _update_search_strings will try to make lower() and this will make the system crash
- Add if series and series.name to vaidate is existes before updating the search strings
```
2021-02-27 03:48:21 ERROR    lazy_lookup   AutoExtract>t_AutoExtract_GetFiles Unhandled error in lazy lookup plugin: 'NoneType' object has no attribute 'lower'
File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/utils/lazy_dict.py", line 41, in __getitem__
callee.func(self.store, *(callee.args or []), **(callee.kwargs or {}))
File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/thetvdb/thetvdb_lookup.py", line 122, in lazy_series_lookup …
```
=> Tvdb NoneType Name Error

flexget/utils/qualities.py
Hi, now that HDR is becoming more and more common, is it time to create a new component called color range
- quality.py - Add support to color range
**BREAKING CHANGES:** Removed 10bit from codecs
- Fixes #2835
```
tasks:
quality_test:
disable:
- seen
- retry_failed
quality: hdrplus+
```
```
flexget execute --inject "My Movie UHD 2160P HDR+ DTS-HD" --dump
2021-04-29 01:07:30 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-04-29 01:07:30 VERBOSE  details       quality_test    Summary - Accepted: 0 (Rejected: 0 Undecided: 1 Failed: 0)
2021-04-29 01:07:30 WARNING  task          quality_test    Task doesn't have any output plugins, you should add (at least) one!
-- Undecided: …
```
=> [add] quality: add color range

flexget/components/imdb/imdb_watchlist.py
imdb_watchlist fails to retrieve list 'ratings' because soup is unable to detect correct total_item_count. Different div classes are used for 'ratings' and 'lsXXXXXXXXX'.
- Update parser to locate correct total_item_count on both lists.
- Fixes list: ratings. All lists should now work as expected.
This is the log when retrieving list: ratings from imdb_watchlist
```
C:\Users\tuant\PycharmProjects\Flexget\venv\Scripts\python.exe C:/Users/tuant/PycharmProjects/Flexget/flexget_vanilla.py --loglevel=debug -c test-imdb_watchlist.yml execute --discover-now --now --no-cache
2020-08-04 16:58:01 DEBUG    manager                       Figuring out config load paths
2020-08-04 16:58:01 DEBUG    manager                       Found config: C:\Users\tuant\PycharmProjects\Flexget\test-imdb_watchlist.yml …
```
=> [fix] Fix error while retrieving imdb_watchlist ratings

flexget/components/sites/sites/solidtorrents.py
- Add support for solidtorrent search
- None.
- None.
```
solidtorrents: yes
OR
solidtorrent:
url: https://solidtorrents.net/
category: Video
sort_by: seeders
reverse: no
remove_potentially_unsafe: yes
```
=> [add] support for Solidtorrents searches

flexget/components/sites/sites/lostfilm.py
Plugin crashed when download failed
Relevant log part:
``` log
During handling of the above exception, another exception occurred:
File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
self._bootstrap_inner()
|    -> <function Thread._bootstrap_inner at 0x7f683666ce50>
-> <Thread(task_queue, started daemon 140084510713600)>
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
|    -> <function Thread.run at 0x7f683666cb80>
-> <Thread(task_queue, started daemon 140084510713600)>
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
|    |        |    |        |    -> {}
|    |        |    |        -> <Thread(task_queue, started daemon 140084510713600)>
|    |        |    -> …
```
=> Fixed crash of the LostFilm plugin when page download failed

flexget/plugins/input/from_piratebay.py, flexget/plugins/input/piratebay_list.py
Enable discovery of fresh and trending torrents from ThePirateBay using its API
```
from_piratebay:
url: https://apibay.org
category: HD - Movies
list: top
rank: all
OR:
from_piratebay:
category: HD - Movies
```
- Add docs.
#2979 renamed from piratebay_list to from_piratebay
=> [add] INPUT from_piratebay

flexget/components/sites/sites/lostfilm.py
LostFilm site is moving from one location to another and have troubles from time to time when accessed via some specific addresses.
* Implemented the list of URLs instead of the single site address
* All URLs are tried one-by-one, in the specified order
* The first working URL is used for all requests during the session / task
* If the URL is failed, all URLs are re-used again including previously failed as the last options
* The list of URLs can be customised via plugin parameters
* A single address could be used in parameters, efficiently disables multi-URL feature
* Custom RSS URL option is removed, RSS is accessed as site URL + '/rss.xml'
This plugin can handle only RSS feed from lostfilm site. The relative address is always the same, there is no need to customize it. The site address …
=> lostfilm plugin: updated to support the latest site changes

flexget/tests/test_jinja_filters.py, flexget/utils/template.py
A clean way to split the year from the title with jinja, that is equal to the logic applied in flexget
- add jinja filter strip_year
- add jinja filter get_year
- add test cases to Jinja filters (can accommodate more filters in the futer, to avoid multiple files per filter)
```yaml
tasks:
stripyear:
mock:
- {"title":"The Matrix (1999)", "url":"mock://local1" }
- {"title":"The Matrix", "url":"mock://local2" }
- {"title":"The Matrix 1999", "url":"mock://local3" }
- {"title":"2000", "url":"mock://local3" }
- {"title":"2000 (2020)", "url":"mock://local4" }
- {"title":"2000 2020", "url":"mock://local5" }
set:
name: "{{title|strip_year}}"
year: "{{title|get_year}}"
```
```yaml
name: The Matrix
year: 1999
name: The Matrix
year: None
name: The Matrix
year: 1999
name: 2000
year: …
```
=> [add] jinja split year: Jinja split name and year

flexget/plugins/clients/rtorrent.py
This commit adds `timestamp_finished` as default field to `from_rtorrent` which is time when torrent has completed.
If torrent has not completed, it has value of `datetime.datetime(1970, 1, 1, 1, 0)`.
`from_rtorrent` currently does not provide information about time when torrent completed downloading. This information is useful for keeping seeding torrent for a set period of time before moving/deletion of data files.
- Add `timestamp_finished` to default fields.
- Converts epoch value received from rTorrent to `datetime.datetime` value.
```
tasks:
debug:
from_rtorrent:
uri: "{? rtorrent ?}"
fields:
- timestamp_finished
```
```
title            : Shadow.in.the.Cloud.2020.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.HYBRID.REMUX-FraMeSToR.mkv
url              : …
```
=> Add `timestamp_finished` to `from_rtorrent`

flexget/components/archives/utils.py
Decompress is erroneously logging an object's location in memory rather than anything useful. 
For example:
```
Extracted: <rarfile.Rar3Info object at 0x7fe34c2b8860>
```
New log output:
```
Extracted: foo/bar to baz/bar
```
- Move the log message and use string paths instead of trying to print a file-like object.
=> Fix verbose log message in decompress

flexget/plugins/clients/transmission.py
- Fix #3084 
- Use offset-aware `now` instead of offset-naive one.
- Fixes #3084.
=> Use timezone aware now in transmission.py

flexget/components/series/series_forget.py, flexget/components/series/series_remove.py
Was looking for a way to remove a show from `series` plugin from within a task (akin to CLI command `flexget  series <remove | forget> <show_name> [episode]` and bumped into this undocumented plugin.
- Brought its functionality more in line with the `flexget series <remove | forget>` CLI command:
- Episode is now optional
- Despite the plugin name, originally it would just remove the show, added option to forget.
```diff
series_forget: yes
+ series_forget:
+   forget: yes
```
=> [change] `series_forget`: Episode identifier is now optional. Optional `forget` parameter (originally would just remove)

flexget/plugins/input/from_piratebay.py
- Bugfix.
- 
- Fixes the incorrect torrent ranks which causes from_pirateby to crash when it encounters an unknown rank (such as `moderator` or `helper`).
=> [fix] Correct from_piratebay torrent ranks

.github/workflows/docker-image.yml, Dockerfile
flexget current has a `Dockerfile`, but no docker image available.
new workflow will release a docker image as `ghcr.io/flexget/flexget` on [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
- for `develop` branch, docker image will be tagged as `ghcr.io/flexget/flexget:develop`
- for a tag `v1.2.3`, docker image will be tagged as `1.2.3`, `1.2`, `1` and  `latest`
On pull-request, a docker image will be built but won't be pushed to registry.
- add a ci to build and push docker image
=> ci: build and push docker image to github docker registry

flexget/components/managed_lists/lists/imdb_list.py, flexget/config_schema.py
Imdb is always changing login system, keeps breaking the possibility to authenticate. I always used the cookies to login, even in new databases I ended up adding the cookies directly to the database, and they never changed! Allowing me to keep using imdb.
- Removed password from the schema (BREAKING CHANGE)
- Added cookie via
- dict
- string (json)
- load file (json) 
- Fixes #2663
```yaml
imdb_list:
imdb_list:
login: myemail@email.com
cookies:
ubid-main: <<from browser cookie>>
at-main: <<from browser cookie>>
list: watchlist
```
```yaml
imdb_list:
imdb_list:
login: myemail@email.com
cookies:  '{"ubid-main": "<<from browser cookie>>","at-main": "<<from browser cookie>>"}'
list: watchlist
```
```yaml
imdb_list:
imdb_list:
login: …
```
=> [add] imdb_list: change authenticate to cookies

flexget/components/parsing/plugin_parsing.py
When parsing plugin is used nested (from_task for example), or for example in a global template, the selection is cleared in on_task_exit, returning to the internal by default 
- added a nested control to the selection, so that it's only removes the running task config.
``` yaml
templates:
global:
parsing:
movie: guessit
series: guessit
tasks:
task_input:
disable:
- seen
- retry_failed
get_guess_it:
disable:
- seen
- retry_failed
mock:
- { "title": "My.Series.S01E01.iNTERNAL.720p.x265-ZMNT" }
from:
mock:
- { "title": "My Series (2021)" }
settings:
parse_only: yes
```
=> [fix] parsing: nested parsing select

flexget/plugins/input/anilist.py
Needed the airing dates (start and end) for additional filtering in my config.
Could also use other databases' IDs - AniDB in particular - to optimize Plex matching by automatically generating `anidb2.id` files for ASS\HAMA upon entry acceptance)
- Additional fields on existing GraphQL request
- New request to API that crossmatches different Databases
- Renamed `al_idMal` field for more sensible `mal_id`
```diff
- {{al_idMal}}
+ {{mal_id}}
+ {{al_date_start}} {{al_date_end}}
```
=> [add] `anilist`: Include more metadata (`al_date_start`, `al_date_end`, `mal_id`)

flexget/plugins/clients/qbittorrent.py
Qbittorrent has a tag feature which is not yet supported by Flexget's qbittorrent-plugin.
- Added Tags to be passed by Qbittorrent-plugin to Qbittorrent. 
- Renders entry specific tags as well as static tags from config.
Optional config if tags are to be used.
```
templates:
qbt:
qbittorrent:
tags:
- Flexget
tasks
Testtask:
template:
- qbt
set:
tags:
- '{{quality.resolution}}'
- Test
```
```
2021-12-06 21:30:05 INFO     qbittorrent   test-qbt        Would add torrent to qBittorrent with:
2021-12-06 21:30:05 INFO     qbittorrent   test-qbt        File: None
2021-12-06 21:30:05 INFO     qbittorrent   test-qbt        Label: None
2021-12-06 21:30:05 INFO     qbittorrent   test-qbt        Tags: Flexget,1080p
2021-12-06 21:30:05 INFO     qbittorrent   test-qbt        Paused: true
```
=> [add] qbittorrent: Pass tag(s) when adding torrents to client

flexget/plugins/input/anilist.py
Fix errors introduced on anilist plugin at v3.2.5
- anilist: fix unhandled error on partial date
- anilist: Fix error for unmapped anime
- Fixes #3301
=> Anilist fixes

flexget/plugins/input/anilist.py
Plugin would generate crash reports when the AniList API was down, caused by raising an exception while handling an exception
- Convert all logger calls to f-strings
- Don't raise exceptions to avoid crash reports.
```
CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
File "github/flexget/flexget/plugins/input/anilist.py", line 119, in on_task_input
json={'query': req_query, 'variables': req_variables},
File "github/flexget/lib/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "github/flexget/flexget/utils/requests.py", line 271, in request
result.raise_for_status()
File "github/flexget/lib/site-packages/requests/models.py", line 953, in …
```
=> Improve AniList Logging

flexget/plugins/output/dump.py, flexget/plugins/output/dump_config.py, flexget/terminal.py
Make --dump output prettier, and nicer to use.
For console api:
- flexget.terminal.console is now a [rich console](https://rich.readthedocs.io/en/latest/console.html)
- It can still be called like a function for backwards compatibility.
- Small tweak to rich's `console.rule` which allows 'indent' property, to make rules with titles look better.
For --dump:
- tables are used to make sure all fields/values line up no matter length
- tables format long values better for easier reading
- Sections for different entry states have prettier dividers with colors.
- Entry fields that aren't strings have colors
- list/dict entry fields get pretty printed for easier parsing
- _url entry fields are clickable links
For --dump-config:
- section off each task config better
- syntax highlight the config …
=> Upgrade console tools, and --dump

flexget/plugins/operate/free_space.py
free_space plugin incorrectly uses password instead of key pair to access remote server.
- Use keyword arguments to pass key_filename to fix where the password was incorrectly used to access a remote server
- Fixes # 3323
```
2022-01-22 13:46:22 DEBUG    urlrewriter   chdbits         Checking 6 entries
2022-01-22 13:46:22 DEBUG    paramiko.transport                 starting thread (client mode): 0x208c6550
2022-01-22 13:46:22 DEBUG    paramiko.transport                 Local version/idstring: SSH-2.0-paramiko_2.9.2
2022-01-22 13:46:23 DEBUG    paramiko.transport                 Remote version/idstring: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
2022-01-22 13:46:23 INFO     paramiko.transport                 Connected (version 2.0, client OpenSSH_8.2p1)
2022-01-22 13:46:23 DEBUG …
```
=> [fix] free_space: Use keyword arguments to pass key_filename #3323

flexget/components/archives/decompress.py, flexget/components/archives/utils.py
Decompress plugin was not checking if the rarfile was installed, ignoring and keeping all entries accepted. This would accept all entries and the user would not be notified.
- Check in task start if rarfile is installed
- Created a wrap method to do the check
=> [fix] decompress: check module exists

flexget/_version.py, flexget/plugins/clients/transmission.py
Using the dates produced by from_transmission was annoying, because you have to compare them to `now.astimezone()` since they are timezone aware. (Here's the issue from when they flipped that on https://github.com/Flexget/Flexget/issues/3084) transmission-rpc just adds the local timezone, even though it doesn't know the timezone for the transmission server, so I don't think it actually adds any value.
Additionally, we were setting transmission_date_done ourselves in some cases to fix another issue, and weren't setting it as tz aware, so the datetimes weren't even consistently having tz info.
- Just strips tz info in any from_transmission fields
```
if:
- transmission_date_added > now.astimezone() - timedelta(hours=3): accept 
- transmission_date_added > now - timedelta(hours=3): accept …
```
=> from_transmission: Strip timezone info from datetimes

flexget/plugins/input/anilist.py
Make sure `ids` is declared even when the call to relations.yuna.moe fails.
- Fixes #3363 .
=> [fix] anilist: fix crash when yuna.moe is unreacheable

flexget/components/sites/sites/lostfilm.py
When plugin is aborted by exception, then next scheduled run of plugin is not clean.
As the lostfilm site could be unavailable for one or another reason, it makes sense to just log error and return `None` instead of raising exception.
Replaced exception with error in log.
Also updated the list of site mirrors.
=> Lostfilm fix

flexget/components/ftp/sftp.py, flexget/components/ftp/sftp_client.py
In situations where releases are structured in their own directory, processing the individual files (ie a directory of rar's) is unnecessary.  Adding this check to skip files (`dirs_only`) can speed up this list process considerably.
- Add `dirs_only` to exclude files from being turned into potential entries.
- This is implemented very similarly to the existing `files_only` option.
- A very rough benchmark gives a 30% speed improvement in using `sftp_list` with `dirs_only: True` with large directories.
```
sftp_list:
host: example.com
username: Username
private_key: /Users/username/.ssh/id_rsa
recursive: True
dirs_only: True
dirs: 
- '/path/to/list/'
- '/another/path/'
```
```
n/a
```
=> [feature] sftp_list - add dirs_only option to exclude files from processing

requirements.txt
I was unable to do a clean install from `master` due to some changes in #3401.  After running `bin/pip install -e .` and trying to run `bin/flexget -V` the error was:
```
pkg_resources.DistributionNotFound: The 'jaraco-text==3.7.0' distribution was not found and is required by FlexGet
```
Changing the `jaraco-*` dependency naming back to `jaraco.*` looks to fix this issue.
- This is a similar change/revert like in 1604012738f1c011e50313b1605cfd029670d5d6
=> Fix jaraco lib names in requirements.txt

flexget/components/notify/notifiers/gotify.py
Gotify notifications are plain text by default but [they support markdown](https://gotify.net/docs/msgextras#clientdisplay).  With markdown support, notifications can be enriched with images, bold text, etc which make them easier to read/highlight important information.
- Add option `content_type` to gotify notifier.
- Default value is `text/plain` for backwards compatibility 
```
notify:
task:
always_send: yes
title: "test!"
template: gotify.template
via:
- gotify:
url: "https://redacted-site.net/"
token: "nope"
priority: 1
content_type: "text/markdown"
```
=> [add] gotify: add support for setting content_type

flexget/components/notify/notifiers/ntfysh.py
User in #3445 requested support for ntfy.sh - it seems like a decent zero-config notification option for people wanting a simple solution.
- Add support for ntfy.sh notifications.  
- #3445 
```
tasks:
seen1:
mock:
- { "title": "Big.Buck.Bunny.1080p.BluRay.x264-GRP", "url": "mock://local1" }
notify:
entries:
title: Download from task {{task}}
template: message.template
via:
- ntfysh:
url: "https://ntfy.sh/"
topic: "flexget-test-topic"
priority: 5
delay: 30s
tags: poop,train
```
Some of the notification implementations have this line in the example:
```
Configuration parameters are also supported from entries (eg. through set).
```
I couldn't find an example of how this is done.  Can provider specific configuration options be set via the entry somehow?
=> [add] ntfy.sh notification support

pyproject.toml
- add python 3.10 to black config
- black now supports python 3.10
=> add python 3.10 to black

flexget/components/scheduler/scheduler.py
Attempting to address the issue raised in #3444.  The tldr is that `pytz` is being deprecated and there is now a more 'supported' way to get local `tzinfo`.
```
PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
```
- Use `datetime` to determine the running systems `tzinfo`.
- According to the `datetime` [docs](https://docs.python.org/3.6/library/datetime.html#datetime.datetime.astimezone) this method might only be reliable in Python >= 3.6.  I've tested this using 3.10 locally and it seems to be working.  I'll let the CI builds kick off to test the other versions.
- #3444
- Turns our time zones in general are a bit of a …
=> [fix] use datetime to detect running systems tzinfo

flexget/components/bittorrent/convert_magnet.py
Fixes #3472 
- Torrent names can contain characters that are not allowed in URLs.  This results in `urllib.request.urlopen` raising an exception when downloading a torrent file generated by the `convert_magnet` plugin.
- When generating the url for the entry in the `convert_magnet` plugin, ensure that it is quoted to avoid these issues by future consumers.
- Fixes #3472
=> [fix] convert_magnet - ensure generated url is quoted

.github/workflows/changelog.yml, .github/workflows/main.yml, .github/workflows/no-prs-to-master.yml, .github/workflows/stale.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

flexget/terminal.py
Make colorizing markup when writing to console opt-in, rather than opt out. fix #3469
The new `rich` based console could crash when we were printing unsatitized text that looked like rich markup. Make it so the markup flag has to be set explicitly when markup behavior is desired, and the caller will be responsible for escaping user input.
e.g. `console("[red]my text[/red]", markup=True)`
To protect against problems in unknown text:
```python
from rich.console import escape
console(f"[bold]remember to escape unsafe text {escape(entry['title'])}[/bold]", markup=True)
```
=> Don't crash when writing markup like text to console

flexget/plugins/input/medusa.py
#3490 - medusa plugin unable to authenticate to service due to change in HTTP header used to send bearer token.
It looks like pymedusa have changed the header used for the Bearer token from `authorization` to `x-auth`.  This updates the Flexget medusa plugin to match.
- Fixes #3490
=> [fix] medusa - use correct header for bearer token

flexget/components/notify/notifiers/telegram.py, requirements.in, requirements.txt
When running tests/using the Telegram notify plugin, the following deprecation warning appears in python 3.10:
```
.../flexget/components/notify/notifiers/telegram.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils.version import LooseVersion
```
- Use `packaging` modules `version` function to do version comparison.
=> [fix] Telegram notify - fix distutils deprecation warning

flexget/tests/test_decompress.py
Running tests against a clean virtualenv (Python 3.10.4) results in failed tests in `flexget/tests/test_decompress.py` due to missing `rarfile` dep.  Virtualenv was setup (following the docs) by running:
```
pip install -e .
pip install -r dev-requirements.txt
```
- Some tests in `test_decompress.py` are skipped if `rarfile` is missing, but some haven't been configured to use the `pytest.mark.skipif` decorator.  
- This change adds the decorator to the whole test suite, as all uses of `decompress` require the `rarfile` module.
```
=== 1349 passed, 34 skipped, 4 xfailed, 5 xpassed, 543 warnings in 32.60s ===
```
=> [fix] skip all test_decompress tests if rarfile module missing

flexget/plugins/clients/aria2.py
- Add support  for JSON-RPC 
- Add configs: 
- scheme: http(default)/https
- rpc_mode: xml(default)/json
- rpc_path: rpc(default)
- JSON-RPC client
- Fixes #3460 .
- N/A
```
web_server:
bind: 0.0.0.0
port: 5050
web_ui: yes
tasks:
SPYxFAMILY:
rss: https://******
aria2:
server: ******
port: ******
scheme: https
secret: ******
rpc_mode: json
rpc_path: jsonrpc
path: /downloads/Flexget
schedules:
- tasks: '*'
interval:
minutes: 10
```
flexget:
```
2022-07-31 03:46:43 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2022-07-31 03:46:43 INFO     web_server_daemon                 Initiating API
2022-07-31 03:46:43 INFO     web_server_daemon                 Registering WebUI v2
2022-07-31 03:46:43 INFO     web_server                    Web server …
```
=> Aria2 jsonrpc support

.github/workflows/docker-image.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

flexget/plugins/input/kitsu.py
Kitsu.io API returns 500 when including `media`. The app uses `anime` relationship instead, which works fine.
This breaks Kitsu input plugin, making it unable to configure series plugin.
- Update API call to load less data and use new filter defitinions
- Allow use of `user_id` directly instead of name lookup. Lookup call likes to fail a lot
- Fetch only used fields from the API
- Fixes #3483 
```
kitsu: 
lists: 
- current
- planned
user_id: "107833"
```
=> Fix Kitsu.io plugin failures

flexget/plugins/clients/aria2.py
The value of option must be a `string`, not `integer`.
- allow `string` `number` `boolean` type for `options`
- auto convert non-string type to string for options before sending to aria2
> In the option struct, the name element is the option name (without the preceding `--`) and the value element is the argument as a **string**.    ——[Options - aria2 documentation](https://aria2.github.io/manual/en/html/aria2c.html#id3)
As document says, option value should be a string. If other types are used such as integer, the option will not take effect (already tested in aria2 v1.36.0).
Now option can be a boolean or number directly. Writing option as a string is also allowed. See the config below.
```yaml
aria2:
path: "/downloads"
options:
max-upload-limit: 0
bt-stop-timeout: "2400"
seed-time: 66 …
```
=> [fix] Use "string" type for Aria2 options

Dockerfile
allow setting timezone for docker via environment variable
- add tzdata package to image
- defaults to UTC
```
environment:
- TZ={TIMEZONE}
```
```
docker run -e TZ={TIMEZONE}
```
Use name from tz database name [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
=> [add] docker: tzdata for timezone support via env

.github/workflows/docker-image.yml
fix docker release build workflow
- typo on dev build caching
- metadata action already includes latest tag when using semver, remove explicit latest tag
=> [fix] docker: typo on develop caching, extra latest tag on releases tag

.github/workflows/changelog.yml, .github/workflows/docker-image.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/stale.yml
clear out warnings of deprecated action versions (node 12->16) on various workflows
- checkout v2->v3
- setup-python v2->v4
- github-script v0.9.0->v6
- stale v3->v6
- build-push v2->v3
- warnings of deprecated node 12. various dependency updates
=> [bump] actions versions

flexget/components/notify/notifiers/bark.py
Change to the consistent identifier naming convention with the project
- replace options
- automaticallyCopy: string -> automatically_copy: boolean
- isArchive: string -> is_archive: boolean
- add enum
- level: 'active', 'timeSensitive', 'passive'
- Flexget/wiki#11
- N/A
```
notify:
entries:
what: rejected  #only for test
title: |
{{task}}
message: |
{% if series_name is defined %}{{series_name}}{% if series_id is defined %} - {{series_id}}{% endif %}{% if trakt_ep_name is defined %} - {{trakt_ep_name}}{% endif %}
{% elif imdb_name is defined%}{{movie_name}}
{% else %}{{title}}
{% endif %}
via:
- bark:
server:  https://******
device_key: ******
level: passive
automatically_copy: true
is_archive: true
```
```
```
- N/A
=> Change the configuration format of the notifier Bark

.github/workflows/docker-image.yml
output variable typo fails docker build since tags and labels are not read correctly
- output->outputs
=> [fix] docker: typo on tags and labels

.github/workflows/release.yml
github releases have empty body with no notes or changelog on new versions
- replace run step with changelog builder action
- verify github release notes
- test changelog workflow for wiki changelog
=> [fix] release: add changelog to release body with changelog-builder-action

Dockerfile
Python 3.10 is supported by Flexget, no reason to keep using 3.9
- change image version to use python 3.10
=> Dockerfile: switch to python 3.10

flexget/components/sites/sites/newznab.py
Some newznab sites provide other id searches than tvrage. Use those too and prefer them.
- check if tvdb_id is set and search using the `&tvdbid=${tvdb_id}` parameters
- if not set, try with `trakt_id`
- if not set, try with `tmdb_id`
- and so on
Additionally a small fix to the logging has been added, it used to log "no results" if there were any results. :exploding_head: 
- N/A
N/A,
=> Newznab support more ids

flexget/components/parsing/parsers/parser_guessit.py, flexget/tests/test_metainfo.py, flexget/tests/test_seriesparser.py
Series plugin support season pack for `identify_by ep` and Internal parsing have partial support even guessit more capabilities and support season packs in more cases than internal guessit, so this PR add support of pack for guessit in flexget 
- Update guessit parser to support series pack
- Fix check by country that was rejecting valid cases like `Dark (2022)`
- N/A
- N/A
```
discover:
what:
- next_series_seasons:
from_start: yes
backfill: yes
from:
- 1337x:
order_by: seeders
from:
entry_list: watchlist_series
settings:
identified_by: ep
tracking: backfill
exact: yes
season_packs: only
```
```
```
=> Add series pack support for guessit parser

Dockerfile
allow running image as non-root user by using non protected folder /config. WORKDIR set to /config so the current directory is detected first for config location
~~add tzdata to support timezones via env~~
- change config folder location from /root/.flexget to /config
~~- install tzdata to allow timezone setting~~
=> [add] docker: run as non-root user

flexget/components/imdb/utils.py
Changing the User-Agent to identify itself as a browser and not as a bot. Seems that IMDB fails with `403` error when bots are requesting from the site. Including the correct User-Agent solved the issue.
- Fixes #3612
=> User-Agent fix for the imdb lookup

flexget/components/notify/notifiers/matrix.py
Matrix is a secure msging platform that allows for updates via a REST call
Addition of matrix.py to the notifiers folder. 
- Fixes # .
- Feature request.
- Matrix support
```
Sample config:
entries:
via:
- matrix:
server: 'https://matrix.org'
token: 'SECRETKEY-dsarasfaFASZgo'
roomid: '!ufPOdHzBzMRGDSASgf:matrix.org'
```
```
2022-08-23 14:32:49 VERBOSE  notify        sort-stuff     Successfully sent a notification to `matrix`
```
=> adding matrix notifier

flexget/components/notify/notifiers/toast.py
`pync` package cannot handle empty string as an argument for `open`, so is `url` isn't configured for *toast*, no notification was displayed.
=> Fix handling of empty `url` in *toast* on macOS

flexget/components/notify/notifiers/toast.py
FlexGet's favicon is installed to `<FLEXGET-UI-PATH>/v1/app/favicon.ico`, but `toast` plugin expects it at `<FLEXGET-UI-PATH>/src/favicon.ico`
=> Fix icon path in `toast` notifier plugin

.gitignore, flexget/components/sites/sites/iptorrents.py
As detailed in #3624 IPTorrents has been observed returning `429 Client Error: Too Many Requests for url` errors for long lists of series with `alternate_name` configurations.
- Adds a configurable `search_delay` parameter to the `iptorrents` search plugin. This takes a `timedelta` string which is then used to create a `requests.TimedLimiter` to add to the task's `requests.Session` instance. It will default to `"1 seconds"`.
- Modifies the `requests.get` calls to use `task.requests.get` instead, so that any additional modifications made to the task outside of this plugin are respected.
- Adds some additional docstring documentation.
- Updates the `.gitignore` to exclude asdf's `.tool-versions` file and VS Code's `.devcontainer` directory.
- Fixes #3624 
```
discover:
what:
- …
```
=> Add configurable search_delay to iptorrents search plugin

flexget/components/sites/sites/magnetdl.py
magnetdl search returns error 404 every time the search term contains a special character because magnetdl.com search path can only contains [a-z0-9] and slashes/-. Current implementation is not good enough.
- Unicode characters are normalized to ASCII first before all invalid chars are stripped to construct a valid search URL
- For example, search term "Pépé le Moko (1937)" should now be constructed as https://www.magnetdl.com/p/pepe-le-moko-1937
Magnetdl.com should return 200 even when there is no matches but it returns error 404 due to malform URLs
```
2022-12-27 12:44:24 WARNING  magnetdl      download-movie-queue Url https://www.magnetdl.com/s/sample-movie-(2001)/ returned 404
2022-12-27 12:44:23 WARNING  magnetdl      download-movie-queue Url …
```
=> [Fix] magnetdl error 404 when search string contains a special character

flexget/components/scheduler/scheduler.py
Fix #3603.
Since the change in #3453, the code was passing a non-pytz timezone, causing #3603.
All we want to do is to tell appscheduler to use the local timezone, and as seen in the documentation for [appscheduler.schedulers.base][1], the local timezone is already the default value, so there is no need to pass this option.
[1]: https://apscheduler.readthedocs.io/en/3.x/modules/schedulers/base.html#module-apscheduler.schedulers.base
- Fixes #3603.
=> Don't override default timezone in the scheduler

flexget/components/sites/sites/nzbgeek.py
I use nzbgeek for searching and ran into problems using newznab and search_rss.
I copied newznab.py and renamed it nzbgeek.py with the following modifications.
```
9c9
< __author__ = 'deksan and rlwmmw'
---
> __author__ = 'deksan'
11c11
< logger = logger.bind(name='nzbgeek')
---
> logger = logger.bind(name='newznab')
14c14
< class Nzbgeek:
---
> class Newznab:
16c16
<     Nzbgeek search plugin
---
>     Newznab search plugin
21c21,23
<         nzbgeek:
---
>         newznab:
>           url: "http://website/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxx&t=movie&extended=1"
>           website: https://website
48,50d49
<         if 'website' not in config:
<           config['website'] = 'https://api.nzbgeek.info'
<
53c52,54
<                 config['url'] = …
```
=> Nzbgeek search plugin

flexget/plugins/output/rss.py
make_rss throws error when evaluating links for entries where lookup fails
- Not only check for existance of a field, but also check, whether it's filled
```
File "/home/stefan/arbeit/privat/flexget/flexget/plugins/output/rss.py", line 258, in on_task_exit
hasher.update(db_item.link.encode('utf8'))
│      │      │       └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f0083be8ef0>
│      │      └ <flexget.plugins.output.rss.RSSEntry object at 0x7f008144b950>
│      └ <method 'update' of '_hashlib.HASH' objects>
└ <sha1 _hashlib.HASH object @ 0x7f0082650a90>
```
after:
```
2023-02-12 22:30:49 TRACE    make_rss      offer_series    Adding Top Gun into rss flexget.rss
2023-02-12 22:30:49 VERBOSE  make_rss      offer_series    Writing output rss to flexget.rss
```
=> Fix for empty lazy field

flexget/plugins/clients/pyload.py
pyload-ng is throwing an exception when pushing contents
- pyload is using ast.parse_literals when parsing the inputs, so, argements have to be encoded accoringly.
before:
```
File "/home/stefan/arbeit/privat/flexget/flexget/plugins/clients/pyload.py", line 45, in post
return self.requests.post(self.url.rstrip("/") + "/" + method.strip("/"), data=data)
│    │        │    │    │   │                   │      │                └ {'html': '" http%3A//some.url.com/12345"', 'url': ''}
│    │        │    │    │   │                   │      └ <method 'strip' of 'str' objects>
│    │        │    │    │   │                   └ 'parse_urls'
│    │        │    │    │   └ <method 'rstrip' of 'str' objects>
│    │        │    │    └ 'http://localhost:8000/api'
│    │        │    └ …
```
=> Fix for pyload ng

flexget/components/ftp/sftp.py
`sftp_list` configurations that do not set `host_key` via Flexget are currently broken.
- #3641 introduced the `host_key` configuration that allows the setting of the SFTP server host key via Flexget rather than relying on the system lookup.
- The `host_key` config key is defaulted to `None` and no check is currently done to ensure its populated before accessing sub-keys.  This causes an exception: `TypeError: 'NoneType' object is not subscriptable`.
- Fixes the above mentioned issue.
n/a
This is challenging to test, which is probably the whole point of #3641 doing the refactor (and adding the new config options) to make this more testable.
=> [fix] sftp_list - check host_key before accessing keys of dict

flexget/plugins/clients/transmission.py
I need this
- Add the support of 'labels' for Transmission.
- Fixes #3520 
```
transmission:
labels: 
- test
- flexget
```
```
transmission_isStalled         : False
transmission_labels            : ['test', 'flexget']
transmission_leftUntilDone     : 0
```
=> Add the support of 'labels' for Transmission.

flexget/__init__.py, flexget/log.py, flexget/manager.py, flexget/options.py, flexget/plugins/output/memusage.py
In certain cases the startup log buffer could be left installed, and start consuming large amounts of memory.
Turns out that case was when the startup log buffer was the first log sink to be registered. (Which happened with flexget-headless, since there was no console to log to.)
- Makes sure the startup log buffer is always uninstalled
- Cleaned up the logging init/startup logic to be all called from `__init__.py` directly, so that it's easier to reason about.
- Removed some old python 2 compatibility code `unicode_argv` since argv is always unicode on python 3.
- Moves some more of `Manager` variable initialization to actual `__init__` rather than be delayed, so that logging and lock file variables are filled earlier.
- Possibly related to #2781
=> [fix] Memory leak when there is no sys.stderr

flexget/plugins/clients/transmission.py
- no need to encode torrent content to base64, removed in new transmission-rpc version
- Fixes # .
=> fix: transmission-rpc deprecated base64 torrent content

flexget/plugins/input/torznab.py
This is needed for under some environments with many sources on the torznab, the answer will take more than 30 seconds.
Let the user configure this to adapt according to their needs.
- Added a new timeout parameter to the torznab input plugin.
```
timeout : 120s
```
=> Torznab: Add timeout parameter

flexget/components/ftp/sftp_client.py
pysftp hasn't been updated in a while, and doesn't handle Ed25519Key and ECDSAKey key types, this monkey patches the _set_authentication method to add handling for these keys.
Ideally Flexget should move directly to using Paramiko but this in itself would be quite a large change.
Unfortunately this is a difficult change to test other than trying it locally.
=> Handle additional SSH Key types

flexget/tests/test_jinja_filters.py, flexget/utils/template.py
Some of the plugin, for example `rss` does not produce the `torrent_size` entry field, but for some sites, it actually contains human-readable size like `114.5MB`, `14GB`, or `1.91TB` in the torrent title.
In some cases, we need to filter out the torrents that are larger or smaller than we expected size. In this case, a filter to parse human-readable string to actual bytes number is necessary.
- Added a jinja filter `parse_size`  to support parse the string like `114.5GB` to `122943438848` bytes int
```yaml
tasks:
download_filtered_size:
rss: https://example.com/?token=xxxx
no_entries_ok: yes
if: # rejects torrents size which are larger than 100GB
- "title|re_search('\d+(\.\d+)?\s*\w+B')|parse_size > 100 * (1024**3)": reject
```
Current PR is a proof of concept, if you …
=> Add template filter to parse human-readable file size to bytes

flexget/plugins/output/download.py
After change to make our requests session not stream by default, (to make sure we don't leave requests open,) download plugin started loading entire downloaded file contents into memory. This could cause issues with large files and/or low memory systems. #3762 
- Turns on stream mode for the request and uses a context manager to make sure to close it
- Switch to a context manager when opening the file on disk
- Fixes #3762
=> [fix] download: Fix streaming downloads to disk

flexget/plugins/clients/transmission.py
Fix transmission deprecation warnings
Warning suppressed by this PR:
```
/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py:137: DeprecationWarning: use .seed_ratio_limited
if session.seedRatioLimited:
/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py:138: DeprecationWarning: use .seed_ratio_limit
seed_limit_ok = torrent.upload_ratio >= session.seedRatioLimit
/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py:256: DeprecationWarning: use .activity_date
value = getattr(torrent, field)
/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py:256: DeprecationWarning: use .added_date
value = getattr(torrent, field)
/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transm …
```
=> Fix transmission deprecation warnings

flexget/plugins/clients/pyload.py
Adding packages to pyload-ng doesn't work. There are several issues that prevent adding packages:
- Typo in variable `set_package_data_command`
- Parameter name for package_id changed in pyload-ng
- Key for folder name changed in pyload-ng
- Fix typo in set_package_data_command: set_package_dat**a** (instead of set_package_dat**e**)
- Different name for package_id parameter (pyload stable: `pid`, pyload-ng: `package_id`)
- Different name for folder key (pyload stable: `folder`, pyload-ng: `_folder`)
Without these changes, adding a package to pyload-ng fails with error:
```
500 Server Error: INTERNAL SERVER ERROR for url: http://x.x.x.x:8000/api/set_package_date
```
=> [fix] pyload: Fix pyload-ng api support

flexget/plugins/clients/transmission.py
`content_filename` doesn't work in my config and I'm seeing multiple `{title} did not magnetize before the timeout elapsed, file list unavailable for processing` even though the torrent has been magnetized and the file list should be available.
- update `torrent_info` before `get_files()`, because `get_files()` will not update file list automatically and will instead return the status when the torrent object is created
```
tasks:
test:
text:
url: https://archlinux.org/download/
entry:
url: "\"(magnet:.*)\""
title: "(Arch Linux)"
transmission:
port: 9091
magnetization_timeout: 120
content_filename: "renamed title"
```
Transmission correctly rename the file
=> Fix transmission file list not getting updated

flexget/tests/test_sftp_server.py, flexget/tray_icon.py
This fixes two small typos in a couple of method docstrings.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!
=> Fix small typos in documentation

.gitignore, flexget/plugins/clients/rtorrent.py, flexget/tests/test_rtorrent.py
rTorrent has the ability to work with named custom fields, but flexget only exposes the builtin custom1...custom5 fields. This PR is to expose the functionality of named custom fields to flexget for both the `rtorrent` and `from_rtorrent` plugins.
- Modify existinf functions of rtorrent client to work with custom fields
Implements #3806 
`from_rtorrent`
```
from_rtorrent:
uri: '{? rtorrent.uri ?}'
username: '{? rtorrent.username ?}'
password: '{? rtorrent.password ?}'
custom_fields:
- foo
- bar
- foobar
```
`rtorrent`
```
rtorrent:
uri: '{? rtorrent.uri ?}'
username: '{? rtorrent.username ?}'
password: '{? rtorrent.password ?}'
custom1: 'ubuntu'
custom_fields:
foo: 'This is a test value from a variables file: {? test_set.foo ?}'
bar: 'down total: {{down_total|default(-1)}}'
foobar: …
```
=> Issue 3806 - Add ability to work with rTorrent named custom fields

flexget/plugins/clients/rtorrent.py, flexget/tests/test_rtorrent.py
rTorrent currently supports adding, updating, and removing a torrent from rTorrent. However, it does not support removing the torrent and the torrent data. This PR adds the ability to specify a `purge` action for the rTorrent plugin that will both remove the torrent data and remove the torrent from rTorrent
- `RTorrent` class
- Add `purge_torrent` method
- 'RTorrentOutputPlugin' class
- Update the `action` schema enumeration to include `purge`
- Add a purge action handler to the `on_task_output` method
- Add a `purge_entry` method for the purge action handler to call that handles the call to the `RTorrent` class' purge_torrent method
- Add tests for the rTorrent purge functionality
```
tasks:
rtorrent_purge:
from_rtorrent:
uri: scgi://localhost:5000
rtorrent:
uri: …
```
=> rTorrent purge action

flexget/components/notify/notifiers/discord.py
I needed to use Jinja expressions to contextually set the embed color.
Rate-limit was overly cautious
- Added STR as an allowed value for embed color
- Parse the STR and convert it to Hexadecimal Int. Gracefully drop it with a warning if fails (invalid value) rather than raising exception
- Switched requests from fixed time rate to token based. Numbers from own responses since the one in the [API docs](https://discord.com/developers/docs/topics/rate-limits#rate-limits) (50 hits/second) would always trigger the rate-limit way before reaching them.
- Added a handler for the rate-limit response header anyways.
- My own
- Fully backwards compatible
=> [Discord] Changes to Rate-Limit and Embed Color

flexget/plugin.py, poetry.lock, pyproject.toml
pkg_resources is deprecated. Switch to importlib_metadata (or importlib.metadata on python 3.10+ for loading plugins installed via pip)
- Uses the entrypoint api from importlib.metadata. To avoid using deprecated interfaces in the new package, importlib_metadata >=3.6 is required for python <3.10
=> Use importlib.metadata to replace deprecated pkg_resources

flexget/ui/v1/__init__.py, flexget/ui/v1/load.failure.html, flexget/ui/v1/src/components/home/home.tmpl.html
Error message for Web-UI had a broken URL
- Find http://flexget.com/wiki/Web-UI and Replace for https://flexget.com/Web-UI
=> Fix URL for Web-UI instructions

flexget/components/sites/sites/passthepopcorn.py
Current plugin impersonates a user with their primary credentials and uses complicated cookie refresh auth. This is in violation of current site rules and can cause an auto ban. Current site rules require all scripts to use apiuser / apikey auth generated by the user as separate credentials.
- removed username / password / cookie auth
- added apiuser / apikey header auth
- added some mappings for odd quality values from ptp to make the quality plugin match more often
- added search parameter for year if input has a movie year and NO IMDB ID
- plugin should raise an error if search fails.
- changed the schema default for the grouping parameter as it seems to provide better matches
- schema replaced username and password with apiuser and apikey
- Fixes authentication / user getting banned …
=> FIX PTP plugin to use apiuser and apikey authentication and some improvements to search and match

flexget/components/status/db.py, flexget/utils/sqlalchemy_utils.py
The index `ix_status_execution_task_id_start_end_succeeded` is almost 93% the size of the actual table. An index on just `task_id` should be similarly performant but much smaller.
- Add DB util functions to manage indexes
- Update DB migration to drop `ix_status_execution_task_id_start_end_succeeded` if it exists and then create the new index
- Fixes # .
```
```
```
```
=> Replace status index with something smaller

.github/workflows/main.yml, flexget/tests/test_rtorrent.py, pyproject.toml
Support python 3.12
- Start testing against python 3.12
- Fix rtorrent tests:
- they weren't actually calling asserts properly
- they were asserting the wrong things in some cases
=> [add] Python 3.12 support

flexget/components/sites/sites/alpharatio.py
the movie-list plugin that uses imdb adds certain special characters to the search, which alpharatio can't handle, like parentheses and colon. This commit makes sure that only alphanumerical characters is used.
Top Gun: Maverick (2023)
South Park: Not Suitable for Children (2023)
Will now work since this commit will strip the colon and the parentheses.
- 
- Fixes # .
```
```
```
```
=> Removed special characters from alpharatio.py search

flexget/utils/parsers/series.py, flexget/utils/qualities.py
Entries with `(Season 1) ... [HEVC x265]` in the title being misidentified as s1e265 instead of a Season Pack
- Replaced Space or EOL character with Word Boundary in the Season Pack RegEx
- Split `HEVC` and `[hx].?265` into separate entities so if an entry uses both they get properly cleaned up. That fixes leaving a stray `x265` to be misidentified as episode 265 later.
- Added `NVENC` as a lower quality codec. Although it's not strictly its own codec, the encoder renders with lower quality h264+ in exchange for speed.
- Added `AV-1` as a codec above `H265`. "The future is now, old man"
- Fixes #3901
=> Identify `(Season 1)` as season_pack

flexget/entry.py, flexget/plugins/input/anilist.py, flexget/tests/test_misc.py, flexget/utils/template.py
Some of the changes to add timezone aware datetimes weren't fully backwards compatible as intended with 3.11.0. This hopefully fixes those issues and reverts a dubious decision:
- Dates are no longer cast to datetimes when added as entry fields. Instead, for convenience, the user is allowed to compare a date to a datetime, and at that point the date will be considered to be a datetime at midnight.
- Anidb reverted to set plain dates, rather than datetimes in tokyo time.
- `now` and `utcnow` template variables are now the special datetimes that allow comparison with naive datetimes and dates.
=> Tweak some of the new pendulum behavior

flexget/components/notify/notifiers/discord.py, flexget/utils/requests.py
`ReadTimeout` has no response attribute and has to be handled separately
`ReadTimeout` has no response attribute and will therefore crash the plugin instead of logging and exiting gracefully.
Added separate `except`-block for `ReadTimeout` in `DiscordNotifier`
- Fixes #3909 
Output of `pytest tests/notifiers`
```
============================= test session starts ==============================
platform darwin -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/axel/Documents/Projects/forks/Flexget
configfile: pyproject.toml
plugins: cov-4.1.0, xdist-3.5.0
collected 7 items
tests/notifiers/test_notify_abort.py ..                                  [ 28%]
tests/notifiers/test_notify_entry.py .                                   [ 42%]
tests/notifiers/test_notify_task.py ... …
```
=> Handle `ReadTimeout` exception in `DiscordNotifier`

flexget/api/app.py, flexget/api/core/schema.py, flexget/config_schema.py, flexget/tests/test_config_schema.py
As of jsonschema version 4.18.0 `jsonschema.exceptions.RefResolutionError` is deprecated and we should catch/raise `referencing.exceptions.Unresolvable` instead
RefResolver usage was also switched to use the new referencing.Registry
Simple 1-for-1 replacements
=> Fix deprecated use of jsonschema library

flexget/utils/qualities.py
Releases using only AVC to identify h264
- Added a new alias to also account for cases where both are used simultaneously (e.g. 1080p AVC h264 AAC)
- Fixes [Issue brought up on Discord](https://discord.com/channels/536690097056120833/536690097496784906/1195774164183818291)
N/A
N/A
=> [fix] Added AVC as an alias for h264

flexget/plugins/clients/transmission.py
3.11.12 update broke transmission since pip version was updated was updated but not the version check
- update version check in transmission module
- check if other areas need updating (pyproject.toml, requirements-docker.txt, etc)
=> [fix] transmission: update version check

flexget/plugins/clients/transmission.py
transmission client version check still broken
- fix version specifier, can't have 2 boundaries with '='
=> [fix] transmission: invalid version specifier

flexget/plugins/input/next_sonarr_episodes.py
The currently used API url is no longer working.
* I just added the `v3` version to the URL.
=> [fix] sonarr: update API version to v3

flexget/components/bittorrent/convert_magnet.py
As mentioned in the Issue, the problem got introduced after the libtorrent version bump last year. Magnet links were causing an error and task crash. 
- Adding an explicit definition of the `save_path` parameter
- Fixes #3781
=> [fix] adding save_path parameter to the convert_magnet module

flexget/utils/qualities.py
`<hdr` was not working as intended in the `quality` plugin
- Changed the order of a single item in the `color_ranges` list
- I'd assume the order would be irrelevant given the numeric value but that doesn't seem to be the case
- Fixes #3952
N/A
Simple task for test, `Too Good` should not be accepted since it does not meet either of the criteria defined in `quality`:
```yaml
tasks:
test:
mock:
- title: Bland 4k 8-bit.mkv
- title: Small 1080p HDR.mkv
- title: Too Good 4k HDR.mkv
quality:
- <2160p
- <hdr
```
Output before:
```
VERBOSE  details       test            Produced 3 entries.                                       
VERBOSE  task          test            ACCEPTED: `Bland 4k 8-bit.mkv` by accept_all plugin       
VERBOSE  task          test            ACCEPTED: `Small …
```
=> Fix HDR quality order

flexget/plugins/metainfo/nfo_lookup.py
Latest version of jellyfin stopped generating .nfo with same name of movies, and is using movie.nfo instead.
Added a fallback to search for movie.nfo if same name .nfo not found.
=> [nfo_lookup] Fallback to movie.nfo if same name .nfo not found

flexget/components/notify/notifiers/telegram.py
Flexget is crashing when `python-telegram-bot` package is not installed, per https://github.com/Flexget/Flexget/pull/4003#issuecomment-2179346431
- Revert part of the changes introduced in https://github.com/Flexget/Flexget/pull/4003
=> [fix]: Wrap telegram imports to avoid runtime crashes

flexget/components/notify/notifiers/telegram.py
Flexget started to crash after loosening the allowed `python-telegram-bot` versions
- Pass the value for `parse_mode` directly instead of reading from the dependency as newer versions store the constant on a separate module.
- N/A
```
N/A
```
=> Telegram: Don't rely on constants

flexget/components/notify/notifiers/discord.py
Wanted to have a notification go out when something is grabbed and another go out when it's available, but didn't want to be notified that it was grabbed, only that it was available; without creating two separate channels.
- Added new property called `silent` onto discord notifier plugin.
- Check if `silent` is true, set property `flags` onto web_hook object with the suppress notification bitfield set.
```
notify:
task:
message: <message>
via:
- discord:
web_hook_url: <web_hook_url>
silent: true
```
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params
=> [add] Discord Notifier: silent notification property

flexget/components/notify/notifiers/telegram.py
#4016 introduce a unintended behavior change where non-formatted messages were no longer allowed and assumed to be HTML instead.
- Make the `parse_mode` definition conditional on config again.
- Introduce the [`markdown_legacy`](https://core.telegram.org/bots/api#markdown-style) formatter
- Addresses a report on the Discord server
=> Telegram: Fix behavior change from #4016

flexget/plugins/input/mock.py
Having to type the Dict-structure for every entry is kind of annoying, especially pasting the titles from elsewhere
- Added a simple `string` option to the accepted formats for each of the  list's entries and assume it's the title
- None, just indulging my own laziness
```diff
mock:
- {title: foobar, url: http://some.com }
- {title: mock}
+       - MockTitle
```
```
VERBOSE  details       test            Produced 3 entries.
VERBOSE  task          test            ACCEPTED: `foobar` by accept_all plugin
VERBOSE  task          test            ACCEPTED: `mock` by accept_all plugin
VERBOSE  task          test            ACCEPTED: `MockTitle` by accept_all plugin
```
=> [Change] Add simpler string-only format to mock plugin's schema

flexget/plugins/clients/qbittorrent.py
In qbittorrent 5 the add_paused option has changed to add_stopped. To handle this I have added stopped to the form data that is entered when adding torrent to qbittorrent. form_data['paused'] is still there to handle older versions of the webapi.
This change follows the same as had been done with label/category for different versions earlier
- Fixes # .
```
```
```
```
=> add stopped to add_paused for qbit5

flexget/api/core/tasks.py, flexget/options.py
cgi and cgitb modules were deprecated, and removed in python 3.13
- Changes to use `email` module to parse content-disposition header in download plugin
- Removes `--bugreport` cli flag. This was using cgitb module, but is not needed now, because loguru shows the extra information in tracebacks by default.
- Fixes #3939
=> Remove deprecated use of cgi module

flexget/plugins/clients/qbittorrent.py
This adds config options for specifying ratio and seeding time limits.
- Adds two config options: `ratio_limit`, and `seeding_time_limit`
None.
```
qbittorrent:
label: some-label
path: /home/user/download
ratio_limit: 1.5
seeding_time_limit: 10
```
`ratio_limit` is a float, and `seeding_time_limit` is in minutes.
=> qBittorrent: add options for ratio limit and seeding time limit

.github/workflows/main.yml, pyproject.toml
Move pytest configuration so developers can run tests locally with the same configuration as GitHub Actions.
=> Move pytest configuration so developers can run tests locally with the same configuration as GitHub Actions.

Dockerfile
"ENV key=value" should be used instead of legacy "ENV key value" format
More info: https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
=> Legacy key/value format with whitespace separator should not be used

flexget/plugins/filter/content_filter.py, flexget/tests/test_content_filter.py
Wanted to reuse a list for `crossmatch` in `content_filter`
- Added list plugins to schema under the `from` key to keep consistency with other plugins
- Fixes my use-case :P
```yaml
content_filter:
[regexp_mode: yes]
require:
- '*.avi'
- '*.mkv'
reject:
from:
- regexp_list: my-rejections
- mock: ['forbidden_file.ext']
```
```
$ pytest -v test_content_filter.py
=========================================================================================================== test session starts =========================================================================================================== platform win32 -- Python 3.11.4, pytest-7.4.4, pluggy-1.5.0 -- Flexget\Scripts\python.exe
cachedir: .pytest_cache
rootdir: Flexget
configfile: pyproject.toml
plugins: anyio-4.4.0, base-url-2.1.0, …
```
=> [Change] Accept Input Plugins in `content_filter`

Dockerfile
Confirmed fix - container starts and no longer segfaults. 
It needed to be pinned in two places - 257af95 was only a partial fix.
=> [fix] Properly pin alpine version in docker image to fix segfault with pendulum - fixes #4085

flexget/utils/parsers/series.py
Year in entrie's title being parsed as Season and Episode. 2025 > s20e25
- Added another expression to the restrictions list
- Fixes #4102
```
Not changed
```
=> [Change] Strictly ignore 19xx-20xx from episode parsing

flexget/components/estimate_release/estimators/est_series_tvmaze.py, flexget/components/imdb/imdb.py, flexget/components/notify/notifiers/telegram.py, flexget/components/pending_approval/cli.py, flexget/components/pending_approval/pending_approval.py, flexget/components/seen/db.py, flexget/components/series/db.py, flexget/components/series/internal_estimator.py, flexget/components/series/next_series_episodes.py, flexget/components/series/series.py, flexget/components/status/cli.py, flexget/plugins/internal/api_rottentomatoes.py, flexget/tests/api_tests/test_seen_api.py, flexget/tests/test_trakt.py, pyproject.toml
Enable the E711/E712 rules and use the `noqa` marker for lines related to SQLAlchemy, because comparisons to `True`/`False`/`None` are valid for sqlalchemy.
E711: https://docs.astral.sh/ruff/rules/none-comparison/
E712: https://docs.astral.sh/ruff/rules/true-false-comparison/
=> Enable the E711/E712 rules and use the `noqa` marker for lines related to SQLAlchemy.

flexget/__init__.py, flexget/api/__init__.py, flexget/api/app.py, flexget/components/bittorrent/convert_magnet.py, flexget/components/ftp/sftp.py, flexget/components/ftp/sftp_client.py, flexget/components/notify/notifiers/xmpp.py, flexget/components/sites/sites/awesomehd.py, flexget/manager.py, flexget/plugins/input/filmweb_watchlist.py, flexget/plugins/input/twitterfeed.py, flexget/plugins/output/sns.py, flexget/plugins/output/subtitles_periscope.py, flexget/plugins/output/subtitles_subliminal.py, flexget/tests/conftest.py, flexget/tests/test_sftp_server.py, flexget/utils/json.py, flexget/utils/parsers/__init__.py, flexget/utils/serialization.py, flexget/utils/tools.py, pyproject.toml
Suppressing all diagnostics can hide issues in the code.
Blanket `noqa` annotations are also more difficult to interpret and maintain, as the annotation does not clarify which diagnostics are intended to be suppressed.
PGH rules: https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh
=> Enforce the PGH rules to prevent the indiscriminate use of `noqa`

.github/workflows/changelog.yml, .github/workflows/docker-image.yml, .github/workflows/release.yml
When switching to uv, I noticed during testing of the Docker and release pipelines that some adjustments were needed:
- The name and email of FlexGet-Bot should not be considered secret, as they can be directly seen in the Git history. This PR makes them more straightforward and thus less configurations are required for forked versions of FlexGet to PyPI or Docker Hub.
-  The Docker image name should not be hardcoded.
This PR simplifies the process of releasing forked versions of FlexGet to PyPI or Docker Hub.
If you feel that displaying your email here is inappropriate, you can also consider showing it as `github-actions`.
=> More fork-friendly

.github/workflows/autofix.yml, .github/workflows/test.yml
Currently, Github Actions only checks the consistency between `uv.lock` and `pyproject.toml`.
This PR automatically performs `uv lock`, so even if you forget to do it, it won't matter.
=> automatically perform `uv lock`

.github/workflows/autofix.yml, renovate.json
At present, `autofix.yml` can't handle `uv.lock` outdated problem caused by a `uv` version bump within a PR because the version of `uv` used during execution comes from the `autofix.yml` in the current `develop` branch, not the uv version in a PR as the `pull_request_target` event is based on the base branch.
See discussions in https://github.com/Flexget/Flexget/pull/4169#issuecomment-2596135030
=> Resolve the issue of not being able to handle `uv.lock `outdated problem caused by a `uv` version bump within a PR

.github/workflows/release.yml, flexget/config_schema.py, flexget/plugins/operate/template.py, flexget/task.py
Multiple editors allow editing a yaml file with completion/hints based on a json schema. This adds an export-schema cli command to get the schema for the current version of flexget which can be used with such tools. It also will publish the json schema for each version as a release artifact, so that we can register the flexget config file on https://www.schemastore.org/json/
Here's the kind of feedback/completions that are possible shown in vs code.
I feel like perhaps more of how the schemas work should be rewritten with this sort of output in mind, but this solution is a bit less intrusive for a quick fix.
=> Add export-schema cli option

flexget/components/ftp/sftp.py, flexget/components/notify/notifiers/email.py, flexget/components/notify/notifiers/mqtt.py, flexget/components/notify/notifiers/slack.py, flexget/components/series/series.py, flexget/config_schema.py, flexget/manager.py, flexget/plugins/daemon/web_server.py, flexget/plugins/filter/regexp.py, flexget/plugins/input/from_telegram.py, flexget/plugins/input/plex.py, flexget/plugins/input/regexp_parse.py, flexget/plugins/input/text.py, flexget/plugins/operate/free_space.py, flexget/plugins/operate/template.py, flexget/plugins/output/download_auth.py, flexget/plugins/output/exec.py, flexget/plugins/output/subtitles_subliminal.py, flexget/tests/conftest.py, flexget/tests/test_config_schema.py
- Stay up to date with json schema versions
- Get on same version of json schema as pydantic generates to allow for possible use of pydantic models (#4208)
- Allows us to extend the metaschema to check for typos in our schemas
- 'definitions' section of schemas changed to '$defs'
- 'dependencies' split up into 'dependentRequired' and 'dependentSchemas'
- strict testing of our schemas to make sure there are no unrecognized keywords
- fixed typos in schemas
=> Update our JSON schemas to draft 2020-12

flexget/plugins/filter/exists_movie.py
The following `exists_movie` config 
```yaml
exists_movie:
allow_different_qualities: better
type: files
path:
- /media/Movies/
```
didn't behave as expected because it doesn't support the following folder structure.
```
/media/Movies/
├─── Cool Movie [2025]
│   ├─── Cool.Movie.2025.BluRay.2160p.HDR.x265.AAC.mkv
```
Because it wouldn't look into the folders themselves that contain the files, so the `allow_different_qualities: better` and `type: files` would never match, causing no entries to be rejected and duplicates being downloaded on every run.
- Changed the `iterdir` call for a `rglob` that does look recursively into the path if the new `recursive` boolean parameter is set to `true`.
- Personal gripe
```diff
exists_movie:
path: /path/to/movies
[type: {dirs|files}] …
```
=> [Change] Make `exists_movie` recurse subfolders

flexget/components/imdb/imdb_watchlist.py
I realised that, in my previous PR, I wrongfully set the default value of `kind` to "predefinedList" instead of "list".  
"predefinedList" is used for IMDB's watchlist only, other list use the "list" key so it should be the default `kind`.
My bad!
=> Fix default value for list kind in imdb_watchlist

flexget/components/imdb/imdb_watchlist.py
Thanks to @ranirahn, I noticied that releaseYear is actually a dict that contains the `year` field.
And in addition, use float instead of int for more accurate rating
- use `item['listItem']['releaseYear']['year']` instead of `item['listItem']['releaseYear']`
- use `float(..)` instead of `int(...)` for imdb_user_score
=> Fix year being nested in releaseYear (imdb_watchlist)

flexget/__init__.py, flexget/api/core/server.py, flexget/components/ftp/sftp_client.py, flexget/components/managed_lists/lists/imdb_list.py, flexget/components/managed_lists/lists/ombi_list.py, flexget/components/managed_lists/lists/plex_watchlist.py, flexget/components/seen/cli.py, flexget/components/series/api.py, flexget/components/series/db.py, flexget/components/sites/sites/ncore.py, flexget/components/status/db.py, flexget/config_schema.py, flexget/db_schema.py, flexget/plugin.py, flexget/plugins/cli/win32_service.py, flexget/plugins/clients/aria2.py, flexget/plugins/input/kitsu.py, flexget/plugins/input/npo_watchlist.py, flexget/plugins/input/regexp_parse.py, flexget/tests/api_tests/test_series_api.py, flexget/tests/api_tests/test_tmdb_lookup.py, flexget/tests/api_tests/test_trakt_lookup_api.py, flexget/tests/test_config_schema.py, flexget/tests/test_series.py, flexget/tests/test_sns.py, flexget/tests/test_sort_by.py, flexget/utils/cached_input.py, flexget/utils/database.py, flexget/utils/tools.py, pyproject.toml
The `N` rules ensure our code adheres to the [PEP 8](https://www.python.org/dev/peps/pep-0008/) naming conventions, which we should follow.
All fixes have been applied manually.
For more information on the `N` rules, refer to the documentation: [Ruff PEP 8 Naming Rules](https://docs.astral.sh/ruff/rules/#pep8-naming-n).
=> Adopt the `N` rules

flexget/components/imdb/imdb_watchlist.py
Since most *_list plugins have it, adds strip_dates property to imdb_watchlist
Also adds more Entry fields when parsing items.
- add `strip_dates` property
- append the date to the title depending on the config
- add `imdb_url`, `imdb_original_name`, `movie_name`, `series_name`, `movie_year`, `series_year`, `imdb_score` and `imdb_votes`
=> Add strip_dates property and more Entry fields to imdb_watchlist

flexget/components/imdb/imdb_watchlist.py
`json.loads` parses `"releaseYear": "None"` to `"releaseYear": None`, no to a string containing the word "None", so `if 'year' in item['releaseYear']` statement is wrong... my bad!
=> Fix releaseYear being`None` when unavailable

flexget/plugins/clients/transmission.py, flexget/tests/test_transmission.py, pyproject.toml, uv.lock
I have a task that adds labels to a torrent and another one that reads labels from torrents, expecting them to be in the same order they were added. Currently, because a regular set is used, the order in which they are defined in the config is not repected.
- Used a dictionary instead of a set, since it preserves insertion order. Alternatively, it could be done with a list and an inclusion check.
- Fixes # . Didn't create an issue for this, but can do so if needed
Added a unit test that was failing and now passing. Although the random nature of the set could eventually make it pass
```
...
flexget/tests/test_transmissiontorrent.py::TestTransmissionTorrentPlugin::test_output_labels_order
<redacted>/__init__.py:3142: DeprecationWarning: Deprecated call to …
```
=> preserve transmission labels order

flexget/components/imdb/imdb_lookup.py, flexget/components/seen/seen_info_hash.py, flexget/components/seen/seen_movies.py, flexget/components/series/db.py, flexget/options.py, flexget/tests/test_misc.py, pyproject.toml
Considering that pylint is no longer used, we should remove the unused pylint pragmas.
=> Remove unused pylint pragmas

flexget/components/ftp/ftp_list.py
The encoding used for directories and filenames on an FTP server may differ from the default 'utf-8'.
May fix #4325
```yaml
tasks:
ftp:
ftp_list:
...
encoding: utf-8
...
```
=> [add] Add encoding option for the `ftp_list` plugin

scripts/build_locked_extras.py
Errors occurred in the deployment workflow after updating `uv`. Updated related code to be compatible with `uv` changes.
=> Fix release pipeline

scripts/build_locked_extras.py
We can remove this if uv starts checking the existence of groups itself.
- https://github.com/astral-sh/uv/issues/10882
=> `uv` has started checking the existence of groups itself

.github/workflows/test.yml
This allows PR authors to discover all issues at once, rather than encountering new errors only after fixing the ones from "Run tests not requiring optional dependencies".
=> Even if "Run tests not requiring optional dependencies" fails, still run "Run tests requiring optional dependencies".

README.rst, pyproject.toml
#4307 enabled new Ruff rules, while the files added in #4326 violate these rules. Due to the simultaneous merging of two PRs, the `develop` branch failed checks after the merge, even though both PRs had passed all checks individually.
To completely resolve the issue where both PRs pass all checks individually, but the `develop` branch fails checks after merging both, consider [enabling merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
The simplest explanation of merge queues is that once enabled, every PR will be tested as if it had already been merged with the latest changes from the base branch before actually being merged. **This means PR authors no longer need to manually …
=> Fix the ruff check

.github/workflows/autofix.yml, .github/workflows/docker-image.yml, .github/workflows/test.yml
To completely resolve the issue where all PRs pass all checks individually, but the `develop` branch fails checks after merging them, we should [enable merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
The simplest explanation of merge queues is that once enabled, every PR will be tested as if it had already been merged with the latest changes from the base branch before actually being merged. **This means PR authors no longer need to manually merge the latest changes into their PRs to avoid failing checks on the `develop` branch after merging.**
**Benefits of enabling merge queues:**
- Ensures the base branch (e.g., `develop`) always stays green by testing the actual merge …
=> Enable GitHub Merge Queues

flexget/_version.py
Previously, there was an error during deployment, but a new release has already been published on PyPI. Therefore, we need to manually bump the version number to avoid a failure during the next release.
=> Bump the version number to avoid a failure during the next release

.pre-commit-config.yaml
The latest version of `renovate-config-validator` cannot run on pre-commit.ci.
=> Disable `renovate-config-validator` on pre-commit.ci

flexget/config_schema.py
A nonexistent path will cause the entire schema to fail validation. This can be super annoying.
- Change `is_path` to log a warning rather than raise a ValueError
=> Make a missing path log a warning rather than causing a fatal error

flexget/components/archives/archives.py, flexget/components/archives/decompress.py, flexget/components/archives/utils.py, flexget/components/bittorrent/torrent_match.py, flexget/components/ftp/ftp_list.py, flexget/components/ftp/sftp.py, flexget/components/ftp/sftp_client.py, flexget/components/managed_lists/lists/subtitle_list.py, flexget/entry.py, flexget/plugins/clients/deluge.py, flexget/plugins/clients/transmission.py, flexget/plugins/filter/abort_if_exists.py, flexget/plugins/input/filesystem.py, flexget/plugins/metainfo/content_size.py, flexget/plugins/metainfo/nfo_lookup.py, flexget/plugins/metainfo/subtitles_check.py, flexget/plugins/output/download.py, flexget/plugins/output/file_operations.py, flexget/plugins/output/sabnzbd.py, flexget/plugins/output/subtitles_periscope.py, flexget/plugins/output/subtitles_subliminal.py, tests/test_abort_if_exists.py, tests/test_exec.py, tests/test_jinja_filters.py, tests/test_regex_extract.py, tests/test_subtitle_list.py, tests/test_torrent_match.py
```
tasks:
task:
filesystem:
path:
- "/home/k/test"
mask: '*.torrent'
retrieve: files
exec:
auto_escape: yes
on_output:
for_accepted:
- rm -f -- "{{ location }}"
- echo "location {{location}}"
- echo "pathbase {{location|pathbase}}"
- echo 'pathdir {{location | pathdir}}'
- echo "pathbase {{location|pathdir|pathbase}}"
set:
label: "tv-{{location | pathdir | pathbase }}"
```
In the above configuration, the bug occurred because `entry['location']` was of type `str`, while `filter_pathdir()` expected a `Path` type parameter. To resolve this, `entry['location']` is now stored as a `Path` type.
=> Change `entry['location']` to use the `pathlib.Path` type

flexget/utils/template.py
This PR only includes the fix for #4329. The change of `entry['location']` to use the `Path` type will continue in #4333.
=> Change the jinja filters to accept both `PathLike` and `str`

flexget/_version.py, flexget/plugins/input/filesystem.py
According to https://docs.python.org/3/library/stat.html#stat.ST_CTIME, `stat.ST_CTIME` is the “ctime” as reported by the operating system. On some systems (like Unix) is **the time of the last metadata change**, and, on others (like Windows), is the creation time (see platform documentation for details).
Since `ctime` is not always the creation time, renaming the "created" field to "ctime" can help avoid misunderstanding.
Closes #4150
=> The "created" field is renamed to "ctime".

flexget/plugins/input/my_anime_list.py
Suggestion from discussion #4395
- Returns more JSON fields into the entries as:
- `mal_id`
- `mal_genres`
- `mal_demographics`
- `mal_episodes`
- `mal_airing_status`
- `mal_name_eng`
- `mal_start_date`
- `mal_end_date`
- Closes #4395
Not changed
=> Return more MAL fields

flexget/config_schema.py, tests/api_tests/test_format_checker_api.py
This makes it clear that even a non-existent path will pass validation.
=> Return true even if a path doesn't exist

flexget/plugins/input/filesystem.py
I forgot to update the other parts when I modified the `timestamp` field earlier.
Fix #4409
=> Fix unhandled error in plugin filesystem: 'timestamp'

.github/codecov.yml, .github/workflows/test.yml, README.rst, pyproject.toml, uv.lock
This PR integrates [Codecov](https://about.codecov.io/) to track and report test coverage in this repository.
Originally, Flexget used [Codacy](https://www.codacy.com/) for coverage reporting, but it no longer works. Moreover, [Codecov](https://about.codecov.io/) is the mainstream choice in the Python open-source community. For example, [the pytest repository](https://github.com/pytest-dev/pytest) itself also uses [Codecov](https://about.codecov.io/).
https://github.com/Flexget/Flexget/blob/c2f0ffdb0f6f84db57e5c484eb65f82964866785/README.rst?plain=1#L10-L15
**Benefits**:
* **Visibility**: Automatically reports how much of the codebase is covered by tests, helping us identify untested areas.
* **Quality Control**: Encourages writing tests for new features and prevents untested code from …
=> Add Codecov for Test Coverage Reporting

.pre-commit-config.yaml
This commit migrates our pre-commit configuration from using the legacy `ruff` hook ID to the new `ruff-check` ID.
The `ruff` project has updated its pre-commit hook definitions. The simple `ruff` ID is now considered a "legacy alias," and `ruff-check` is the new, explicit ID for the linter hook. This was observed today when running the pre-commit hooks locally.
The hook ID in `.pre-commit-config.yaml` has been changed:
```diff
- id: ruff
+ id: ruff-check
```
This change aligns our configuration with the official [ruff documentation](https://github.com/astral-sh/ruff-pre-commit) and prevents potential warnings or breakages in future releases. It has no impact on the hook's functionality.
=> fix(pre-commit): Migrate from legacy 'ruff' hook ID to 'ruff-check'

tests/cassettes/test_subtitle_list.TestSubtitleList.test_subtitle_list_subliminal_success, tests/test_filesystem.py, tests/test_subtitle_list.py
The test `[tests/test_subtitle_list.py::test_subtitle_list_subliminal_success]` was experiencing instability, not in its pass/fail status, but in its effect on code coverage metrics. The coverage would fluctuate between CI runs.
The root cause was that the test makes a network request but was missing the `@pytest.mark.online` decorator. Consequently, our test runner did not use the corresponding VCR cassette to mock the network interaction.
Even though the test could pass with a live network connection, the code paths executed would differ slightly, leading to inconsistent coverage data.
This PR resolves the issue by adding the `@pytest.mark.online` decorator to the test.
This change ensures that the VCR cassette is correctly used for every run, which:
- Makes the test fully …
=> fix: Stabilize test and fix coverage fluctuations by marking it as `online`

flexget/utils/qualities.py, tests/test_qualities.py
User requests on the referenced issues
- Added new `hybrid-hdr` color space Quality above `dolbyvision`
- Included a couple of tests
- Closes #4042
- Fixes #4043
- Fixes #4074
```
quality: hybrid-hdr
```
```
$ pytest tests\test_qualities.py
=========================================================================================== test session starts ============================================================================================
platform win32 -- Python 3.11.4, pytest-8.3.4, pluggy-1.5.0
rootdir: Flexget
configfile: pyproject.toml
plugins: anyio-4.8.0, cov-6.0.0, mockito-0.0.4, xdist-3.6.1, time-machine-2.16.0
collected 158 items
tests\test_qualities.py ............................................................................................................................. …
```
=> [Add] `hybrid-hdr` Quality for Color Range

.github/codecov.yml, docs/conf.py, tests/sftp/test_sftp_server.py
The strict patch coverage check requires that all new and modified lines in a PR are accompanied by tests. Given the project's currently low overall test coverage, this often forces developers to write a substantial number of new tests even for minor changes, which creates a high barrier for contributions.
To unblock the development workflow, this change sets the patch coverage check to "informational". This means the check will now always pass, but it will continue to report on the coverage of each commit and pull request, providing valuable feedback to developers without halting the release process.
Crucially, the project-level coverage check remains active and blocking. Any PR that causes a decrease in the total project coverage will still fail the build.
=> chore(ci): Make patch coverage check non-blocking

flexget/config_schema.py
The variable is named `error`, but it's being logged as a `warning`. This can be a bit confusing for future readers, as the name `error` typically implies a more severe issue that might halt execution (corresponding to `logger.error` or an exception).
The current code uses an f-string to create the log message. For logging, it's a best practice to use the logger's own substitution mechanism instead.
As the **[ruff documentation on `G004`](https://docs.astral.sh/ruff/rules/logging-f-string/)** explains, the logging module uses "lazy" or "deferred" formatting. This means it only constructs the full message string *if* the message's level (e.g., `WARNING`) is high enough to actually be processed by a handler.
When you use an f-string, the string is formatted *immediately*, even if the log …
=> refactor: Fix a minor flaw in the path validator code

.github/workflows/docker-image.yml, .github/workflows/test.yml
When a pull request is merged via the merge queue, it triggers two separate CI workflow runs for the same commit:
1. One for the `merge_group` event.
2. A second, redundant one for the `push` event to the base branch.
This duplication consumes unnecessary CI minutes and slows down the feedback loop.
This commit adds a conditional `if` statement to our CI jobs. The jobs will now be skipped if the event is a `push` and the actor is `github-merge-queue[bot]`, which is the user responsible for merge queue merges.
This ensures that only the `merge_group` check is executed for commits entering the develop branch via the merge queue, thereby improving CI efficiency and saving resources.
=> ci: Skip redundant push builds after `merge_group` checks

flexget/utils/qualities.py
- Disabled `strip_all` property from `color_space` so the list can remain in natural order
- Fixes #4445 .
```
$ pytest tests\test_qualities.py
============================= test session starts =============================
platform win32 -- Python 3.11.4, pytest-8.3.4, pluggy-1.5.0
rootdir: Flexget
configfile: pyproject.toml
plugins: anyio-4.8.0, cov-6.0.0, mockito-0.0.4, xdist-3.6.1, time-machine-2.16.0
collected 158 items
tests\test_qualities.py ................................................ [ 30%]
........................................................................ [ 75%]
......................................                                   [100%]
============================== warnings summary ===============================
.venv\Lib\site-packages\flask_restx\api.py:19 …
```
=> Fix color space evaluation order

flexget/components/notify/notify.py, pyproject.toml, tests/cassettes/test_telegram.TestTelegramNotifier.test_chat_migrated, tests/notifiers/test_telegram.py, tests/test_file_operations.py, tests/test_rottentomatoes.py, tests/test_seriesparser.py, tests/test_tmdb.py, tests/test_trakt.py
This commit changes all instances of `pytest.mark.xfail` to `pytest.mark.skip` for tests that are currently broken or non-functional.
The `skip` marker is more appropriate for broken tests for the following reasons:
- **Performance:** `xfail` still executes the test code, consuming time and resources. `skip` prevents the test from running entirely, making the test suite faster.
- **Clarity of Intent:** `xfail` should be used for tests that cover a specific, known bug that you expect to fail. `skip` clearly signals that a test is temporarily disabled and should not be run at all, often because it's incomplete or its dependencies have changed.
- **CI Stability:** An `xfail` test that unexpectedly passes (XPASS) can clutter reports or even fail the build if `xfail_strict=true` is set. `skip` …
=> refactor: Replace xfail with skip for broken tests

.github/workflows/docker-image.yml, scripts/bundle_webui.py
The Docker image build process has been suffering from sporadic failures, a key cause of which has been identified and is addressed herein.
When fetching metadata for the latest Flexget webui release, the unauthenticated API call was susceptible to GitHub's IP-based rate limits. If the GitHub Actions runner's IP had exhausted its request quota, the build would fail. This commit remedies this vulnerability by leveraging a `GITHUB_TOKEN` to perform an authenticated API request.
This approach utilizes the significantly more generous rate limit granted to authenticated tokens, thereby circumventing the IP-based restriction and bolstering the overall stability and resilience of the build process.
A clear example of this failure mode can be observed in the following workflow run: …
=> fix(ci): Fortify Docker build against API rate-limiting errors
