flexget/plugins/urlrewrite_serienjunkies.py
The URL will only be updated if the language matches the requirements
=> update URL on language match only

flexget/plugins/parsers/parser_guessit.py
This should fix http://flexget.com/ticket/2775 and it was also discussed in https://github.com/Flexget/Flexget/pull/389
I am creating this pull request as the other one hasn't been changed in a while. I think it's time fix this, so the subliminal plugin can work correctly.
=> ParserGuessit changes

flexget/plugins/plugin_deluge.py
enables the changes made in https://github.com/Flexget/Flexget/pull/351 (605b5cc)
=> Pass on the hide_sparse_files and keep_subs options

flexget/logger.py, flexget/manager.py, flexget/task.py, flexget/task_queue.py
This implements writing separate crash report logs, always with debug level logging and tracebacks.
http://flexget.com/ticket/2876
=> Separate crash report logs. fix #2876

flexget/plugins/api_trakt.py
This should add the name/year search for the id's
=> Added name/year id lookup

flexget/plugins/urlrewrite_piratebay.py
=> update TPB to new TLD and search API

flexget/plugins/urlrewrite_torrent411.py
=> [t411] Fix and update WebRip subcategories

flexget/utils/qualities.py, flexget/utils/trakt.py, tests/cassettes/test_trakt.TestTraktList.test_trakt_movies, tests/test_qualities.py
New 720 definition was asked for.
=> Added new Subset of 720 definition "720HD"

flexget/plugins/filter/series.py
@gazpachoking Is this what you had in mind? Any more changes?
And while we're at it. Have you thought about the sorting we talked about?
=> cleaning up alternate name in series

flexget/plugins/urlrewrite_torrent411.py
The tracker changed hostname from t411.me to t411.io
=> rewrite .me to .io

flexget/plugins/input/trakt_list.py, flexget/plugins/search_btn.py, flexget/utils/trakt.py
Fixed BTN search to allow for non strict searching on the api since some episodes have the episode name attached to the series_id.
=> Fixed BTN Search to allow for non strict searching

flexget/plugins/search_rarbg.py
RarBG seems pretty decent and while their releases also float around on Torrentz etc. I think their site is a lot less noisy.
One thing though. They have some weird bot detection. If the cookie does not contain `'7fAY799j': 'VtdTzG69'`, then it will get caught by the bot filter after the ~5th consecutive request.
I'm not entirely sure they'd appreciate this plugin then, but their RSS feed sucks. Their anti-bot captcha is also extremely easy to circumvent with OCR.
=> [WIP] search plugin for rarbg

flexget/plugins/operate/sleep.py
Operate it in any phase for the specified number of seconds.
=> Make sleep more flexible

flexget/plugins/operate/sleep.py
I'm not sure how I left these out the first time, but here they are.
=> Add additional phases of execution to sleep plugin

flexget/plugins/output/utorrent.py
I'm new to Python, so I'm not sure why the download will fail on private trackers. It gives the "maybe a login page" error.
I'm using the same config file I used on my router (with transmission plugin) and it failed. I'm currently running FlexGet on Windows. The task has form plugin.
=> Updated to use the download plugin

flexget/plugins/plugin_sftp.py
SFTP plugins patterned after ftp_list and ftp_download. This plugin requires the pysftp Python modules and its dependencies.
=> Plugins to download from SFTP

flexget/plugins/modify/path_select.py, tests/test_path_select.py
-Types in path_select tests
-Will now abort a path cannot be selected
=> plugin path_select tests fix

flexget/plugins/input/couchpotato.py
This plugin allows retrieval of the couchpotato wanted movie list
example usage:
```
queue_movies_couchpotato:
couchpotato:
base_url: http://localhost
port: 5050
api_key: <your key here>
movie_queue: add
```
=> add couchpotato plugin

flexget/plugins/plugin_rtorrent.py, tests/test_rtorrent.py
This is a WIP branch of an rTorrent output plugin. 
Example config:
```yaml
rtorrent:
uri: 'scgi://localhost:5000'
directory: '/path/default_dest/'
custom1: '/path/{{ series_name }}'
```
=> rTorrent output plugin

flexget/plugins/plugin_rtorrent.py, tests/test_rtorrent.py
-Fix bug with renaming to a folder with spaces
-Fix bug with spaces in customX fields on load
-Fix bug with spaces in path
=> RTorrent plugin bug fixes

flexget/plugins/plugin_rtorrent.py
Sorry for making alot of commits.. fixing a few bugs
=> better detect is a folder is changing and requires move

flexget/plugins/input/sonarr.py
add 2 options to sonarr plugin
* include_ended includes ended shows from sonarr (defaults to true)
* only_monitored excludes unmonitored shows (defaults to false)
=> add options to sonarr plugn

flexget/plugins/input/sickbeard.py
Added include_ended and only_monitored option to plugin
=> Added more options to sickbeard plugin

flexget/plugins/output/pushalot.py
=> Pushalot support

flexget/plugins/input/couchpotato.py
=> Fixed property error

flexget/plugins/input/couchpotato.py, flexget/plugins/input/sickbeard.py, flexget/plugins/input/sonarr.py
Test mode logging for easier future dev & testing
=> Added test mode logging to CP/SB/Sonarr plugins

flexget/plugins/urlrewrite_divxatope.py
Added handling of relative redirected links (url=torrent/... instead of url=http://divxatope/torrent) to reflect recent changes on the page
Minor edits to comply with PEP8
=> adding support of relative redirect links

flexget/plugins/input/sickbeard.py
=> sickbeard.py spelling fix

flexget/plugins/urlrewrite_serienjunkies.py
This Version has better language recognition and allows multiple download urls (usable with pyload plugin)
=> Extended Serienjunkies UrlRewriter

flexget/plugins/output/pushbullet.py
Adds the ability to use multiple API keys in the Pushbullet output plugin, also the addition of email address destinations for messages.
Squashed version of my previous PR with fixes and cleanups.
=> Pushbullet - support multiple api keys and email destinations.

flexget/plugins/input/sickbeard.py
Actually added the correct parameter to the plugin this time
=> Fixed missing parameter

flexget/plugins/plugin_sftp.py
Add SFTP socket timeout to fix hung SFTP sessions; a couple of other minor tweaks.
=> Add SFTP socket timeout

flexget/plugins/input/couchpotato.py, flexget/plugins/input/sickbeard.py, flexget/plugins/input/sonarr.py, flexget/plugins/input/sonarr_emit.py
Added ability to set show quality via Sonarr's 'cutoff' quality parameter.
Also changed the default of only_monitored to true
=> Added include_data parameter & changed only_monitored default to true

flexget/plugins/urlrewrite_torrent411.py
Just passing by :)
The format of the inputs on t411.io has changed since jul 8th approx.
This PR is to reflect these changes.
Keep up the good work!
=> T411.io: Adapted SUB_CATEGORIES to the new site inputs

flexget/plugins/input/trakt_emit.py
Responsible for testing is qvazzler.
=> Fixes in trakt_emit: unused imports, UnboundLocalError of var `eps` #3033

flexget/plugins/input/sickbeard.py, flexget/plugins/input/sonarr.py
Fix logging level for entry error sonarr & SB plugins. Also minor PEP8 fixes
=> Fix logging level for entry error sonarr & SB plugins

flexget/plugins/output/pushbullet.py
pushbullet v2 api allows for pushing to custom channels created by users. useful for better organisation of pushes.
=> added channel tags to pushbullet plugin

flexget/plugins/metainfo/subtitles_check.py, flexget/plugins/output/subtitles_subliminal.py
Updated to work with the current stable version of subliminal (1.0.1)
This solves this problem http://flexget.com/ticket/3047
=> Fix subtitles to work for current stable version of subliminal (1.0.1)

pavement.py
Fallout from http://flexget.com/ticket/3064
=> Make Flexget dependent on Path 6.2 or higher

flexget/plugins/output/pushalot.py
Multiple tokens were not configured properly in schema
=> Bug fix for multiple token support in Pushalot plugin

flexget/plugins/plugin_sftp.py
Plugin to upload files to an SFTP server.
=> sftp_upload plugin

flexget/plugins/output/exec.py
EscapingDict should inherit from Entry, not MutableMapping
=> http://flexget.com/ticket/3083

flexget/plugins/input/dynamic_imdb.py
- Removed regex matching and switched to string matching
- Split items_by_entity method to seperate methods for each object type
(person, character and company)
- Improved items_by_character accuracy
- Added some missing job types
- Fixed remarks
- Minor tweak to schema
=> Some refactoring to dynamic_imdb plugin

flexget/plugins/input/dynamic_imdb.py
Forgot some debugging stuff...
Sorry
=> Forgot some debugging stuff in dynamic_imdb plugin

flexget/plugins/output/pushover.py
Added try catch block for request
=> Fix for pushover plugin 

flexget/plugins/input/trakt_emit.py
Check for json key before interating. Fix #3075
=> Trakt input fix

flexget/plugins/api_tvrage.py
Suppressed ParseError exception from tvrage with LookupError
=> Suppressed ParseError exception and replace it with LookupError in api_tvrage.py

flexget/plugins/urlrewrite_piratebay.py
=> Updated hostname in urlrewrite_piratebay.py

flexget/plugins/input/dynamic_imdb.py
Complete refactor, more efficient and readable.
Major bug fix when selecting a female person (yeah, seriously)
Added ability to use multiple IDs
=> Refactor for dynamic_imdb plugin

flexget/plugins/output/move.py
see http://flexget.com/ticket/3104
=> The move plugin is not using the "filename" option

flexget/plugins/input/whatcd.py
A few updates to the what.cd input plugin. See commits for details.
=> Whatcd updates

flexget/webserver.py
=> webui: fix typo "avaliable" => "available"

flexget/plugins/plugin_sftp.py
Fix to sftp_plugin, missing vars assignments and pep8 fixes
=> Fix to sftp_plugin, missing vars assignments and pep8 fixes

flexget/plugins/output/pyload.py
Plugin gained the option to send a predefined password for a package to pyload.
=> Config packagePassword added

flexget/plugins/input/sonarr.py, flexget/plugins/input/sonarr_emit.py
Sonnar & Sonnar_emit will return TVMaze ID if present
=> Sonnar & Sonnar_emit will return TVMaze ID if present

flexget/plugins/output/pushover.py
Added ability to use jinja2 with 'sound' and 'priority' values in Pushover plugin
=> Jinja2 capabilities for more fields in pushover plugin

flexget/plugins/estimators/est_release_series_tvmaze.py
Error message and episode number are not supplied in the correct order.
=> Fix log message in tvmaze estimator

flexget/plugins/output/pushover.py
Fix error due to missing 'priority' field default
=> Fix error due to missing 'priority' field default

pavement.py, rtd-requirements.txt
Requires latest version of pytvmaze. Fixes #662
=> Requires latest version of pytvmaze. Fixes #662

flexget/plugins/output/notify_sns.py, jenkins-requirements.txt, tests/test_plugin_output_notify_sns.py
It struck me that a notification engine that pumps out SNS messages might be cool to have.
=> Add an SNS notification plugin

flexget/plugins/output/pushover.py
Pushover output refactor and enhancements:
- Complete refactor
- All fields are now Jinja2 render-able
- Added support for level 2 priority, emergency priority
=> Pushover output refactor and enhancements

flexget/plugins/api_trakt.py, tests/cassettes/test_trakt.TestTraktList.test_trakt_movies, tests/cassettes/test_trakt.TestTraktMovieLookup.test_lookup_actors, tests/cassettes/test_trakt.TestTraktMovieLookup.test_lookup_sources, tests/cassettes/test_trakt.TestTraktMovieLookup.test_search_results, tests/cassettes/test_trakt.TestTraktShowLookup.test_absolute, tests/cassettes/test_trakt.TestTraktShowLookup.test_date, tests/cassettes/test_trakt.TestTraktShowLookup.test_lookup, tests/cassettes/test_trakt.TestTraktShowLookup.test_lookup_actors, tests/cassettes/test_trakt.TestTraktShowLookup.test_lookup_name, tests/cassettes/test_trakt.TestTraktShowLookup.test_search_fail, tests/cassettes/test_trakt.TestTraktShowLookup.test_search_results, tests/cassettes/test_trakt.TestTraktShowLookup.test_unknown_series, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_collected_lookup, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_collected_movie_lookup, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_watched_lookup, tests/cassettes/test_trakt.TestTraktWatchedAndCollected.test_trakt_watched_movie_lookup, tests/test_trakt.py
Added new test for low scoring matches to fail.
=> Reworked trakt_api scoring comparison.

flexget/plugins/urlrewrite_torrent411.py
I'm no expert in Python, I've seen this working at home though...
=> Setting user agent consistently for all requests

flexget/plugins/api_tvmaze.py, tests/cassettes/test_tvmaze.TestTVMazeShowLookup.test_episode_without_air_date_and_air_stamp, tests/test_tvmaze.py
Better attribute detection and much more readable.
=> Changed how tvmaze sets attribute

flexget/plugins/api_tvmaze.py, flexget/plugins/metainfo/tvmaze_lookup.py, pavement.py, rtd-requirements.txt, tests/cassettes/test_tvmaze.TestTVMazeShowLookup.test_show_with_non_ascii_chars, tests/test_tvmaze.py
Several changes:
* TVMaze episode summary support, fixes #682 
* Changed series.rating type to float, fixes #689 
* Non ASCII show support, fixes #680 
* Added tests
=> TVMaze episode summary support

flexget/plugins/output/send_telegram.py
per the discussion in http://discuss.flexget.com/t/new-plugin-telegram-cli-telegram-bot/1655/26?u=tsnoam
=> send_telegram: add support for markdown template

flexget/plugins/urlrewrite_iptorrents.py
Added more categories for iptorrents url checks.
=> Added more categories

flexget/plugins/input/anidb_list.py
An input plugin that generates a list of movie entries from user's AniDB (http://anidb.net) wishlist. The wishlist must be public.
=> Input plugin for AniDB wishlist

pavement.py
=> help tracking requirements in pavement

pavement.py, rtd-requirements.txt
=> allow beautifulsoup4 4.4.x

flexget/plugins/output/send_telegram.py
fix bug described in http://discuss.flexget.com/t/crash-reports-log/1883
=> send_telegram: adhere to python-telegram-bot ver. 3.1.0 api

flexget/plugin.py, flexget/plugins/api_tvdb.py, flexget/plugins/cli/series.py, flexget/plugins/daemon/scheduler.py, flexget/plugins/filter/series.py, flexget/plugins/input/emit_series.py, flexget/plugins/input/ftp_list.py, flexget/plugins/input/twitterfeed.py, flexget/plugins/input/whatcd.py, flexget/plugins/operate/free_space.py, flexget/plugins/output/ftp_download.py, flexget/plugins/output/subtitles.py
Fix errors found by landscape.
=> [dev][tweaks] Fix errors found by landscape

flexget/plugins/filter/movie_queue.py
Should clean up any badly formed movie titles that got added to movie queue while imdb parser was broken.
=> [fix] Clean malformed titles in movie queue. fix #729

flexget/plugins/output/send_telegram.py
All other config options are with an underscore, change to harmonize
=> Change use-markdown to use_markdown

flexget/plugins/parsers/parser_common.py, flexget/plugins/parsers/parser_guessit.py, pavement.py, rtd-requirements.txt, tests/test_qualities.py, tests/test_seriesparser.py
It's been a long time I didn't not performed a commit here but ...
I've rewriten guessit from scratch in version 2. Currently guessit 2 is in Beta, but it's working quite well and is far easier to maintain.
This PR should not be merged because it's a work in progress ! I'll let you know when it's ready :)
=> Update guessit to 2.0

flexget/utils/search.py
Add's some special cases to clean_title and removes all special characters
=> Add's some special cases to clean_title

flexget/plugins/plugin_transmission.py
Transmission plugin ignores addpaused for magnet links
=> Fix for issue #705

flexget/utils/imdb.py
The movie title H1 tag no longer contains a span with itemprop='name'
the H1 tag has an attribute itemprop='name'
fixes https://github.com/Flexget/Flexget/issues/824
=> Fixes imdb changes introduced 2016-01-26

flexget/plugins/api_t411.py, flexget/plugins/plugin_torrent411.py
=> [T411] Fix issue #833

flexget/plugins/input/anidb_list.py
As title says, added some functionality to anidb_list plugin.
=> Supported TV series entries and date stripping in anidb_list

flexget/plugins/search_kat.py
Removes special charters from KAT search
=> Strips Special Charters from KAT

flexget/plugins/input/rss.py
Else python will complain that ascii won't be able to decode
special characters.
=> Use a byte string to compare aginst data which is a byte string 

flexget/plugins/output/slack.py
This is my first attempt at contributing to this project. I wanted a way to notify my private Slack channel when a new download started. I based most of the code off of the Pushbullet plugin (thanks to whoever wrote that!).
Please let me know if I need to fix anything up -- and thanks!
=> Add Slack output plugin

flexget/plugins/api_trakt.py
http://docs.trakt.apiary.io/#reference/authentication-devices
=> [WIP] Added device authorization and deprecated PIN auth

flexget/plugins/api_t411.py, flexget/plugins/urlrewrite_torrent411.py, tests/cassettes/test_t411.TestRestClient.test_auth, tests/cassettes/test_t411.TestRestClient.test_error_message_handler, tests/cassettes/test_t411.TestRestClient.test_malformed_search_response, tests/cassettes/test_t411.TestRestClient.test_retrieve_categories, tests/cassettes/test_t411.TestRestClient.test_retrieve_terms
Hi :) 
first pull request, hope i'm doing it right 
t411 change the domain  from t411.in to t411.ch 
so i update  api references to the new domain.
sorry for differents commits, i've update files online and haven't find how to modify all in one commit.
=> T411 domain changed from t411.in to t411.ch

flexget/plugins/input/npo_watchlist.py
This plug-in creates entries for a user's watchlist entries on npo.nl (Dutch public television). 
The entries can for example be downloaded
using https://bitbucket.org/Carpetsmoker/download-npo
=> Add input plug-in for npo.nl watchlist

flexget/plugins/input/apple_trailers.py, tests/cassettes/test_input_sites.TestInputSites.test_apple_trailers, tests/test_input_sites.py
It works again. Did it have tests?
=> [fix] Updated apple_trailers fixes #916

flexget/plugins/urlrewrite_torrent411.py
Hello,
This pull request just fix one missing domain change from PR https://github.com/Flexget/Flexget/pull/906
This fixes url rewrite error on my system
=> Fix missing domain change from t411.in to t411.ch

flexget/plugins/filter/exists_movie.py, flexget/plugins/plugin_cookies.py, flexget/utils/cached_input.py
=> Fix race condition with TimedDict in @cached decorator.

flexget/utils/simple_persistence.py
pickle sucks a bit, json is a nicer serialized format, switch simple_persistence to using it. Also allows for use on py2 and 3.
Not tested too much.
=> Switch simple_persistence to serialize using json rather than pickle

flexget/utils/qualities.py
Fixing support for 1080p50. Still needs a test.
=> Fixing 1080p50

flexget/plugins/plugin_torrent411.py
Fix a type mistake introduced by last commit
=> [t411] Fix search for non-series

flexget/plugins/input/npo_watchlist.py
After site changes, a CSRF token is now required.
=> npo_watchlist: Fix watchlist removal

flexget/plugins/api/entry_list.py, flexget/plugins/cli/entry_list.py, flexget/plugins/cli/movie_list.py, flexget/plugins/list/entry_list.py
Enable `entry_list` CLI operations.
=> Entry list CLI

flexget/db_schema.py
Preperation for backup tool (among other potential uses) that will need to associate an existing DB to a flexget version
=> Put flexget version in DB

tests/test_seriesparser.py
Fixed correct date in test_date_options::yearfirst
=> [FIX][TEST] Correct date for yearfirst.

flexget/plugins/list/imdb_list.py
Fix imdb_lists crash from ConnectionError
=> [FIX]Fix# 1058 Add ConnectionError handling to request

flexget/plugins/plugin_urlrewriting.py
should update rss urls list with rewritten url.
=> [FIX] update entry['urls'] with rewritten entry['url'] #1104

flexget/plugins/output/subtitles_subliminal.py
Already supported by the subliminal API, patch just adds a config option for it.
Fixes #1062
=> [subliminal] Add option to save to another directory

flexget/plugins/filter/seen.py, flexget/plugins/filter/seen_movies.py, tests/test_seen.py
- Fixes #1148
- So, it turned out that that scope: local was not getting passed to seen.py's on_task_learn()
- Add tests for seen_movies scope: local
=> [seen] Fix seen_movies scope: local (2nd attempt)

flexget/plugins/plugin_transmission.py
=> add queue position to transmission

flexget/plugins/list/imdb_list.py, tests/cassettes/test_imdb_list_interface.TestIMDBList.test_imdb_list_add, tests/cassettes/test_imdb_list_interface.TestIMDBList.test_imdb_list_remove
IMDB blocks login attempts after a certain number, thus preventing using `imdb_list`.
By caching login cookies, user ID & list ID, we can directly retrieve IMDB list without having to re-login, circumventing the issue
- ~~Using SimplePersistence to create dict with the following data: KEY is `config['login']`, JSON value is `{"watchlist": "ls032578336", "cookies": "cookie_dict, "user_id": "ur65953086"}`~~ Using dedicated tables
- Multiple logins are cached
- Multiple list IDs per login are cached
- Fixes #1109 
First run:
```
C:\Python27\python.exe C:/Flexget/flexget_vanilla.py -L debug execute --tasks imdb_list_test
2016-05-26 14:58 DEBUG    manager                       Figuring out config load paths
2016-05-26 14:58 DEBUG    manager                       Found config: …
```
=> Enabled imdb_list to cache credentials per login name

flexget/plugins/search/morethantv.py, flexget/plugins/search/mtv.py
@qvazzler
- New search plugin for morethantv
```
mtv:
username: blabla
password: blabla
category: TV
tags: [adventure, action]
all_tags: yes  # must match all tags
```
=> added morethantv search plugin

flexget/plugins/modify/manipulate.py
It makes sense to me that manipulation can take place in the `modify` phase
=> Allow manipulate to run in modify phase

flexget/plugins/filter/seen.py, flexget/tests/test_seen.py
Nonsensical to have a variable change type depending on config.
=> [fix] 'local' is now strictly a boolean

flexget/options.py, flexget/plugins/cli/entry_list.py, flexget/plugins/cli/movie_list.py, flexget/plugins/cli/seen.py, flexget/plugins/cli/series.py, flexget/plugins/filter/remember_rejected.py, flexget/plugins/filter/retry_failed.py, flexget/plugins/list/movie_list.py, flexget/plugins/output/history.py, flexget/tests/test_series.py, requirements.txt
Our current way of outputting CLI tables is hard coded, not readable and non consistent through various CLI plugins. This enables a solution to all those issues.
- Fixes #1303
- Using the [terminaltables](https://github.com/Robpol86/terminaltables) dep. 
- Colors using the [colorclass](https://github.com/Robpol86/colorclass) dep. 
- Created the `CLITable` class in `options`.
- Created a parent ArguementParser to be used when needed
Parser `--table-type` arguments currently takes 5 options: `plain` ,`single` ,`github`, 'porcelain' and `double`, each matches a table style currently imlemented by `terminaltables`. `single` is default:
```
C:\Flexget>python flexget_vanilla.py -c config2.yml movie-list all
┌───┬─────────────────┐
│ # │ List Name       │
├───┼─────────────────┤
│ 1 │ main …
```
=> Pretty CLI table

flexget/plugins/input/html.py
Bug report
- Explicitly handle magnet uri's. The name is usually after the string '&dn=' until it reaches another ampersand.
- Fixes #1250
=> [fix] Retrieving title from magnet, fixes #1250

flexget/plugins/list/imdb_list.py, flexget/tests/cassettes/test_imdb_list_interface.TestIMDBListTypes.test_imdb_list
Correction IMDb login fails
use _session.headers.update to not overwrite header.
add _session.headers.update({reference : http://...}) For better browser simulation
and also post the URL from the action attribute of the form.
- Fixes #1321
```
tasks:
import_from_imdb:
imdb_lookup: yes
imdb_list:
login: ********
password: ********
list: watchlist
list_add:
- movie_list: from_imdb
```
```
2016-08-12 15:31 DEBUG    task          import_from_imdb executing import_from_imdb
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb fetching items from IMDB
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb user credentials not found in cache or outdated, fetching from IMDB
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching …
```
=> Correction IMDb login fails #1321

flexget/plugins/estimators/est_released_movies.py, flexget/plugins/estimators/est_released_movies_bluray.py, flexget/plugins/internal/api_bluray.py, flexget/plugins/metainfo/bluray_lookup.py
=> API, lookup and estimator for Blu-ray.com

flexget/plugins/sites/iptorrents.py
A change in HTML-code at iptorrents
- Fixes #1368 
```
2016-08-25 03:37 VERBOSE  discover      search_movies   Searching for `The Captive (2014)` with plugin `iptorrents` (1 of 1)
2016-08-25 03:37 VERBOSE  details       search_movies   Produced 15 entries.
```
=> Fix plugin iptorrents, fixes #1368

flexget/plugins/operate/max_reruns.py, flexget/task.py, flexget/tests/test_discover.py, flexget/tests/test_next_series_episodes.py
Need something to limit the number of reruns
- Changed tests to use max_reruns
- Changed max_reruns to set the old value properly
=> Fix max_reruns

flexget/plugins/internal/api_trakt.py, flexget/plugins/list/trakt_list.py, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_simple, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_task, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_remove, flexget/tests/test_trakt_list_interface.py
Adding episodes to a trakt_list required a lookup which is unnecessary.
- Reverted aaf1a69384586dc5bd18e42462693ac4d37b2bcb and fixed the bugs in a saner way.
=> Fix trakt_list submit

flexget/plugins/modify/convert_magnet.py
Just needed some small changes
- Changed the original plugin to use add_magnet_uri
```
convert_magnet: yes
```
```
convert_magnet: 
timeout: 60 seconds
```
=> New plugin convert_magnet

flexget/plugins/output/pyload.py
Beats me
- Messy plugin. Tried making it prettier/better.
- Use json.dumps to make sure every post parameter is properly formatted.
- Changed the schema to make sense (`pyload: yes`???)
- Fixes #1136
=> Fix pyload plugin

flexget/api/__init__.py, flexget/api/plugins/tmdb_lookup.py, flexget/plugins/internal/api_tmdb.py, flexget/plugins/metainfo/tmdb_lookup.py, flexget/tests/api_tests/test_tmdb_lookup.py, flexget/tests/cassettes/test_tmdb.TestTmdbLookup.test_tmdb_lookup, flexget/tests/cassettes/test_tmdb.TestTmdbUnicodeLookup.test_unicode, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_backdrops_params, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_by_title, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_no_params, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_posters_params, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_year_param
Trakt images are going bye bye, need to replace images on UI.
- Added `/tmdb/movies/` endpoint
- `api_tmdb` schema changes (removed unused `certifications`, added `backdrops`)
- Removed the hard limit of 5 posters per movie (added it to `tmdb_lookup` task plugin).
- Some bug fixes with `api_tmdb`
=> TMDB lookup API

flexget/api/__init__.py, flexget/api/app.py, flexget/api/plugins/irc.py, flexget/plugins/cli/irc.py, flexget/plugins/daemon/irc.py
Monitor and manage IRC plugin connections
- Added `/connections/` 
- Added `/restart/` 
- Added `/stop/`
=> IRC API endpoint 

flexget/plugins/output/exec.py
bug fix
- Fixed the encoding issues (mostly)
- Fixes #1295
One problem with this solution is that Windows is still really awful. Mostly when using Python 2. Question is, should the entire thing be wrapped in try-except and raise taskabort? @gazpachoking
=> better string encoding in exec

flexget/api/__init__.py, flexget/api/app.py, flexget/api/core/tasks.py, flexget/api/plugins/movie_list.py, flexget/api/plugins/status.py, flexget/plugins/operate/status.py, flexget/tests/api_tests/test_status_api.py
Could be very nice in UI
- Added `/status/` endpoint. Replicated under `/tasks/status/` as well.
- Executions endpoints: `/status/<ID>/executions/`
Wondering if I should implement deletion as well. @paranoidi
=> Tasks status API

flexget/plugins/services/myepisodes.py
Flexget was bombing when it attempted to verify a succesful login to the myepisodes.com website
- I added an explicit translation of the return page to fix it
=> myepisodes refactor

flexget/api/plugins/status.py, flexget/plugins/cli/status.py, flexget/plugins/operate/status.py, flexget/tests/api_tests/test_status_api.py, flexget/ui/src/plugins/status/status.component.js, flexget/ui/src/plugins/status/status.service.js, flexget/ui/src/plugins/status/status.tmpl.html, flexget/ui/src/plugins/status/status.tmpl.scss
UI needs to paginated and sorted on server side
- Added pagination to `/status/` endpoint
- Added `last_execution_time` property to `StatusTask`
- Added `last_execution_time` to Status CLI
- Added index to `status_executions` table
=> Status plugin changes

flexget/plugins/input/imdb_watchlist.py
People need imdb watchlist apparently
- Improved the old imdb_list plugin
```
fill_movie_list:
imdb_watchlist:
user_id: urXXXXXXXX
list: watchlist
list_add:
- movie_list: whatever
```
=> New old imdb_watchlist

flexget/plugins/operate/formlogin.py
This is a resubmission of https://github.com/Flexget/Flexget/pull/123 by @skasi7, updated for the current codebase. It adds HTML sanitization for the `formlogin` plugin.
=> Improve form plugin in case of malformed HTML

flexget/plugins/internal/api_t411.py, flexget/plugins/sites/torrent411.py, flexget/tests/cassettes/test_t411.TestRestClient.test_auth, flexget/tests/cassettes/test_t411.TestRestClient.test_error_message_handler, flexget/tests/cassettes/test_t411.TestRestClient.test_malformed_search_response, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_categories, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_terms
New domain name
- Change dot ch to dot li
- Fixes #1567  .
```
flexget t411 add-auth <username> <password>
Credential successfully updated
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5620008
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5620007
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5620006
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5619994
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5619985
2016-12-17 10:46 INFO     t411_plugin   serie-vf        Lookup torrent details for 5619973
```
=> T411 - Update domain url

flexget/plugins/sites/bakabt.py
just trying to help
from .com to .me
- Fixes #1591
=> [fix] bakabt changed TLDs

flexget/plugins/sites/nyaa.py, flexget/tests/test_urlrewriting.py
just trying to help
- from .eu to .se
- Fixes #1594
=> [fix] nyaa changed TLD

flexget/plugins/sites/piratebay.py
Single quotes weren't matching anything; just replace with whitespace
=> Support searching for titles which contain quotes

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_info_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_info_lookup, flexget/tests/test_npo_watchlist.py
NPO API has changed
- What used to be e.g. http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?category=broadcasts is now http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?media_type=broadcast
- Without this fix, also other video objects, like small snippets of episodes are fetched
=> NPO parameter has changed for only showing full episodes

flexget/plugins/sites/rutracker.py
Update login and download links
Links has been changed
- Update login link
- Update download link
- Fixes #1656
=> Update rutracker_auth plugin

flexget/plugins/internal/api_tvmaze.py
When searching for shows using the TVmaze API, Flexget does not escape any query parameters.  This leads to incorrect searches.  My log file showing the error is linked below.  You can see that Flexget attempted to search for "Law & Order: Special Victims Unit", but the "&" was not escaped.  If you go to the requested URL you will see that the received search term was just "Law", resulting in the plugin returning Newton's Law instead of Law & Order SVU.
- Pass any query parameters to requests as a dictionary so they are properly escaped.
https://gist.github.com/anonymous/460c9231e44062b6ce0d9c354fbc6ea4
=> Escape tvmaze URL query parameters

flexget/plugins/sites/newpct.py
Addead search options based on divxatope
- Search NewPCT
```
discover:
what:
- movie_list: wanted_movies
from:
- newpct: yes
```
```
2017-02-08 13:38 INFO     urlrewriter   bajar_pelis     Entry 'Passengers  DVDRIP-AC3 5.1' URL rewritten to http://www.newpct1.com/download/27486_passengers---.torrent (with newpct)
2017-02-08 13:38 INFO     download      bajar_pelis     Downloading: Passengers  DVDRIP-AC3 5.1
2017-02-08 13:38 INFO     transmission  bajar_pelis     "Passengers  DVDRIP-AC3 5.1" torrent added to transmission
```
=> NewPCT added search feature

flexget/plugins/notifiers/pushsafer.py
- add Pushsafer Notification Service
-  add flexget/plugins/notifiers/pushsafer.py
=> Add Pushsafer Notification Service

flexget/plugins/sites/rutracker.py
- Checking available domain from list
- Nothing changed
=> [add] mirrors for rutracker plugin

flexget/plugins/input/npo_watchlist.py, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npo3_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npostd_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup
NPO.nl site has been updated; the schema.org URL has been updated
- changed http to https in the schema.org URL
- updated the tests
=> Update NPO.nl schema.org URL

flexget/plugins/sites/lostfilm.py
On site has been changed link
- changed regexp for search tv show's id
=> lostfilm plugin. link changed on site

flexget/plugins/internal/api_t411.py, flexget/plugins/sites/torrent411.py, flexget/tests/cassettes/test_t411.TestRestClient.test_auth, flexget/tests/cassettes/test_t411.TestRestClient.test_error_message_handler, flexget/tests/cassettes/test_t411.TestRestClient.test_malformed_search_response, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_categories, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_terms
Hi,
If i did it right ... change all t411 reference  from .li  to .ai
=> Fix t411 official domain from .li to .ai

flexget/plugins/internal/api_t411.py, flexget/tests/cassettes/test_t411.TestRestClient.test_auth, flexget/tests/cassettes/test_t411.TestRestClient.test_error_message_handler, flexget/tests/cassettes/test_t411.TestRestClient.test_malformed_search_response, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_categories, flexget/tests/cassettes/test_t411.TestRestClient.test_retrieve_terms
T411 modify api to respond only to https (http fallback to https)
without modification the api cannot retrieve json
=> Update t411 api to https

flexget/plugins/filter/crossmatch.py
I want it
- Added `all_fields` option that enforces all fields to match between two entries
=> Crossmatch: all_fields option, require all fields to match

flexget/tests/api_tests/test_tmdb_lookup.py, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_year_param, flexget/tests/cassettes/test_trakt.TestTraktMovieLookup.test_lookup_translations, flexget/tests/cassettes/test_trakt.TestTraktShowLookup.test_lookup_translations, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_get_list, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_strip_dates, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_simple, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_add_episode_task, flexget/tests/cassettes/test_trakt_list_interface.TestTraktList.test_trakt_remove, flexget/tests/test_imdb_list_interface.py, flexget/tests/test_imdb_parser.py, flexget/tests/test_input_sites.py, flexget/tests/test_npo_watchlist.py, flexget/tests/test_rss.py, flexget/tests/test_t411.py, flexget/tests/test_trakt.py, flexget/tests/test_trakt_list_interface.py, requirements.txt
.
- Mostly skipped the broken tests. Fixed a few tests that needed it.
- Still not sure what to do about trakt list tests. How to automatically save the new token when it refreshes?
=> Fix online tests again

flexget/plugins/output/symlink.py, flexget/tests/test_symlink.py
I like hardlinks and Plex doesn't
- Changed Symlink plugin to take a 'type' param ('soft' or 'hard').
=> Symlink: Added support for hardlinking files and dirs

flexget/plugins/input/npo_watchlist.py
=> Fix missing grid-favourite bug in npo_watchlist

flexget/plugins/filter/series_premiere.py, flexget/plugins/metainfo/series.py, flexget/tests/test_series_premiere.py
=> Fix series_premiere + series pairing

flexget/tests/test_seriesparser.py, flexget/utils/titles/series.py
Shit's annoying
- Fall back to episode parsing if season pack parsing was invalid.
- Fixes #1986
=> Fix for invalid season pack parsing

flexget/api/app.py, flexget/api/plugins/tmdb_lookup.py, flexget/plugins/internal/api_tmdb.py, flexget/plugins/metainfo/tmdb_lookup.py, flexget/tests/cassettes/test_tmdb.TestTmdbLookup.test_tmdb_lookup, flexget/tests/cassettes/test_tmdb.TestTmdbUnicodeLookup.test_unicode, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_backdrops_params, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_by_title, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_posters_params, flexget/tests/cassettes/test_tmdb_lookup.TestTMDBMovieLookupAPI.test_tmdb_movies_lookup_year_param
People use languages other than English. Go figure...
- Added ability to query TMDB using different languages
- Added support via `tmdb_lookup`
- Added support via API
- Feathub #[10](https://feathub.com/Flexget/Flexget/+10).
```yaml
tmdb_lookup:
language: de
```
=> Added ability to lookup with language in TMDB

.circleci/config.yml, .circleci/images/python36/Dockerfile, flexget/_version.py, flexget/manager.py, flexget/utils/sqlalchemy_utils.py
Add support for python 3.6
- ~Added to `.travis.yml`~
- Added to CircleCI
- Added explicit commit after adding a new column due to change in [python API](https://docs.python.org/3/whatsnew/3.6.html#changes-in-the-python-api) in 3.6: `sqlite3 no longer implicitly commits an open transaction before DDL statements.`
=> Python 3.6 compatibility

flexget/plugins/filter/series.py, flexget/plugins/operate/configure_series.py, flexget/utils/tools.py
If 100's of series exist flexget's performance can suffer when parsing.
=> Series performance improvements

flexget/plugins/filter/crossmatch.py, flexget/plugins/filter/torrent_match.py, flexget/plugins/input/discover.py, flexget/utils/tools.py
Bored
- Extracted a loop into a function
=> Refactor discover, crossmatch etc inputs

flexget/plugins/output/symlink.py
I want to be able to create hardlinks for files in directories which not exists.
=> Create directories recursively for hardlinks

flexget/plugins/sites/newpct.py
fix urlrewriter for newpct1 (web format changed), search url  and normalize special characters
Errors downloading from newpct1
- regexp changed
=> [fix] newpct1 urlrewriter

flexget/plugins/input/imdb_watchlist.py
imdb_watchlist plugin did not return any entries any more. See issue #2035 .
- added new function to parse the new JSON code used by a new React widget. The new widget was introduced by imdb on watchlist pages early December 2017. Interestingly, the react widget uses an openly accessible api that returns JSON code which is easier to parse than the html code
- updated the existing code to parse other user lists, where imdb changed the layout (but does not use the react widget)
- Fixes #2035 .
new JSON parser:
```
2017-12-30 15:56 VERBOSE  imdb_watchlist IMPORT_TEST_W   Retrieving imdb list: watchlist
2017-12-30 15:56 DEBUG    imdb_watchlist IMPORT_TEST_W   Requesting: http://www.imdb.com/user/ur25395647/watchlist {u'Accept-Language': u'en-us'}
2017-12-30 15:56 DEBUG    utils.requests …
```
=> imdb_watchlist plugin fixed issue #2035

flexget/plugins/sites/newpct.py
Now Newpct1 and Newpct share torrent urlrewrite.
Changes in newpct1
- newpct1 and newpct share code
=> [FIX] More web changes Newpct1

flexget/plugins/list/imdb_list.py
dunno
- Updated login to fit the new layout
- Changed imdb types to match latest changes
- Fixed csv parsing
- Fixes #2052 
- Partial fix for #1421
=> Fix imdb_list

flexget/plugins/sites/argenteam.py
aRGENTeaM is a great spanish content provider, especially for the latin community. Added a search plugin to download episodes and movies.
- subtitles: [yes]/no
Search for releases that include subtitles (or not)
```
templates:
tv:
series:
settings:
HDTV:
timeframe: 12 hours
target: hdtv
quality: hdtv+
HDTV:
- The Blacklist
torrent:
transmission:
port: 9091
username: 'transmission'
password: 'transmission'
ratio: -1
main_file_only: yes
path: /volume2/Descargas/transmission/downloads
addpaused: no
skip_files:
- '*.nfo'
- '*.sfv'
- '*[sS]ample*'
- '*.txt'
tasks:
nuevas_series:
template: [tv,torrent]
discover:
what:
- next_series_episodes:
from_start: yes
from:
- argenteam:
force_subtitles: yes
interval: 1 hour  # Search for expected episodes again every hour
max_reruns: 1
```
=> Added Argenteam search plugin

flexget/api/app.py, flexget/api/core/server.py, flexget/tests/api_tests/crash_report.2017.12.06.163120482503.log, flexget/tests/api_tests/crash_report.2017.12.21.095530581138.log, flexget/tests/api_tests/test_server_api.py
Having an ability to remotely view crashes would be nice
- Added `/server/crash_logs/` endpoint
=> Crash logs API

flexget/plugins/sites/piratebay.py, flexget/tests/test_urlrewriting.py
Fixes #2068 for piratebay reverse-proxies
~~Cassettes for testing should be updated, but I can't run those tests against the original domain, because for me it is blocked~~
=> Allow to set website URL for piratebay plugin

flexget/plugins/filter/series.py, flexget/plugins/parsers/parser_common.py, flexget/plugins/parsers/parser_guessit.py, flexget/plugins/parsers/parser_internal.py, flexget/tests/test_metainfo.py, flexget/tests/test_series.py, flexget/tests/test_seriesparser.py, flexget/utils/titles/movie.py, flexget/utils/titles/series.py, requirements.in, requirements.txt
Trying to finish @gazpachoking parser simplification branch
- Upgraded to guessit 2.1.4
- Cleaned up @gazpachoking's old branch
- Fixed tests
- Fixes #1974
- Fixes #1804
- Closes #2019
- Related #1398
=> Simplify parsers v2

flexget/plugins/list/imdb_list.py
Indexing with magical values (ints) is prone to breakage and it suuuucks
- Changed to DictReader
- Fixes #2095
=> [imdb_list] Use DictReader and index into rows with header names

flexget/plugins/sites/descargas2020.py
Newpct now is descargas2020 (or tvsinpagar)
- Changed name to descargas2020
=> [fix] Renamed site newpct -> descargas 2020 + changes

flexget/plugins/list/imdb_list.py
- Changed the endpoints for removal and adding to the same as the ones used on the site. Maybe the endpoints in the app are better, but I don't have the setup required to examine them.
- Fixes the issue that skyway22 brought up in Gitter, but apparently wouldn't create an issue for.
=> imdb_list: Fix it... again

flexget/plugins/output/download.py, flexget/plugins/sites/torrentleech.py
The last PR I made used the Torrentleech V4 API as a temporary fix to get the plugin working. This could stop working any time. Implementing support for the new API will futureproof the plugin
- Reverted back the changes in https://github.com/Flexget/Flexget/pull/2117
- Rewrote the plugin so it interfaces directly with the torrentleech backend endpoint.
- Fixes #2115 
This is the first real PR I make to this project so if I have made any mistakes feel free to point them out and I will gladly fix them :)
=> Feature/Torrentleech v5 API

flexget/plugins/cli/series.py, flexget/plugins/sites/limetorrents.py
- Make series with quotation marks work
- Make it easier to figure out which episodes Flexget is going to download in a series
=> Couple of tweaks

flexget/plugins/filter/imdb.py
Previous update to add metacritic filtering left schema incorrect. this update corrects issue.
Fixes incorrect schema
- 
- Fixes # .
```
```
```
```
=> Fixed Schema

flexget/plugins/sites/iptorrents.py
Categories as changes on websites, so I updated them in the string listing.
Updated Categories
Update Wiki when pulled.
=> IPTorrents - Updated Categories + MovieXvid WrongNumber

flexget/plugins/sites/horriblesubs.py
To get the plugin working again.
Updated the plugin to use the new API.
- Fixes #2166
=> [fix] horriblesubs: updated to work with new site layout, fixes #2166

flexget/plugins/input/npo_watchlist.py
increase the domain delay limit
do not raise a plugin-error on non-critical failed fetches
=> NPOStart gives regularly 502 errors, handle those

flexget/plugins/input/letterboxd.py
=> Fix query for next page link in letterboxd plugin

flexget/plugins/output/subtitles_subliminal.py
Subliminal development seems dead-ish
- Added a try-except
- Fixes #2145
=> Subliminal crashes if Chardet can't guess the encoding

flexget/plugins/filter/exists_series.py
It's a silly message
- Changed "proper" to "episode".
- Fixes #1902
=> exists_series: Changed rejection message to "episode already exists"

flexget/plugins/internal/api_trakt.py, flexget/utils/simple_persistence.py
I'm tired of old simple_persistence values fucking everything up...
- Added UpgradeImpossible for really old configs that are missing a column for some reason.
- Mark any failed loads with DELETE
- Fixes #2154 
- Fixes #2101 
- Fixes #2031 
- Fixes #1176
- Fixes #1788
=> Fix simple_persistence issues with aggressive deletion

flexget/plugins/list/trakt_list.py
Feature Request
- Added ISO 639-1 language option -- no validation though
- Related to #795
- Feathub #[61](https://feathub.com/Flexget/Flexget/+61).
=> trakt_list: added ISO 639-1 language option

flexget/tests/test_qualities.py, flexget/utils/qualities.py
Some releases specify channels
- Added channels as optional in dtshd and truehd
=> Qualities: added support for channels in dtshd and truehd

flexget/plugins/operate/formlogin.py
- mechanize does not work on python 3
- mechanize did not use our task's requests session
- Uses mechanicalsoup to get/submit forms rather than mechanize
- mechanicalsoup now uses our task.requests session, improving compatibility with other plugins
- Fixes #728
- Fixes #1537
=> Convert form plugin to use mechanicalsoup rather than mechanize

flexget/plugins/list/trakt_list.py
- As discussed on IRC this could be improved as the API on Trakt's side changed
=> Additional changes to PR 2226

flexget/plugins/input/anidb_list.py
- Properly copy the headers, so the plugin doesn't affect the entire task.
As mentioned by @cvium in #2220
=> anidb_list: copy headers

flexget/plugins/clients/rtorrent.py
SGCITransport implementation was GPLed code. See #2196 This is hopefully just to inspire somebody to finish this job, as I haven't installed rtorrent or tested anything. Somebody with rtorrent can use this as a jumping off point for testing.
- Fixes #2196
=> Remove GPLed code from rtorrent implementation

.gitignore, dev-requirements.txt, flexget/plugins/parsers/parser_guessit.py, flexget/tests/test_seriesparser.py, flexget/utils/imdb.py, requirements.in, requirements.txt
Upgrade to guessit 3.0 so we can take advantage of new features and bugfixes.
- Rewrite initiation of GuessItApi for 3.0
- Added mapping for new guessit namings
- Bump requirements versions
- https://github.com/Flexget/Flexget/issues/2160
=> Guessit 3.0

flexget/plugins/sites/nyaa.py
- The nyaa plugin wasn't finished
- Added the remaining missing nyaa categories
- Added seeders, leechers, info hash, and content size.
```
2018-11-05 20:26 VERBOSE  urlrewrite_search test_rtorrent   Searching `Kin`iro Mosaic` from nyaa
2018-11-05 20:26 DEBUG    nyaa          test_rtorrent   requesting: https://www.nyaa.si/?page=rss&q=Kin%60iro%20Mosaic&c=1_2&f=0
2018-11-05 20:26 DEBUG    nyaa          test_rtorrent   Search result not 200 (OK), received 301
2018-11-05 20:26 TRACE    entry         test_rtorrent   ENTRY SET: title = 'Patches for [VCB-Studio] Hello!! Kin-iro Mosaic / ハロー!!きんいろモザイク 10bit 1080p HEVC BDRip
[Fin]'
2018-11-05 20:26 TRACE    entry         test_rtorrent   ENTRY SET: original_url = 'https://nyaa.si/download/771798.torrent'
2018-11-05 20:26 TRACE    entry …
```
=> Nyaa: Finish Todos

flexget/plugins/sites/torrentday.py
- torrentday always resulted in no entry found for searches
- The tags on torrentday changed, so I changed the plugin tags to match torrentday's current tags
- Fixes #2105
=> Erichlf torrentday

docs/develop/list_interface.rst
Fixes a small error in the documentation.
=> Fix documentation error

flexget/plugins/input/medusa.py
I was updating myinfrastructure with medusa, and i tried to connect with flexget via sickbear plugin, but the api of sickbear of medusa was outdated and i create a new plugin specific for medusa
I created the plugin based on old sickbear plugin, i reformat and created all the rest requests of that
- Feathub https://feathub.com/Flexget/Flexget/+65
```
templates:
medusa:
from:
medusa:
base_url: http://127.0.0.1
port: 8081
username: username
password: password
only_monitored: True
from:
medusa:
base_url: string
port: string default 8081
username: string
password: string
only_monitored: boolean default False
included_ended: boolean default False
```
```
DEBUG MODE 
2018-12-21 23:24 DEBUG    medusa        updating_series processing show: {'title': …
```
=> medusa plugin

flexget/plugins/search_yts.py
YTS search was created with https://github.com/Flexget/Flexget/pull/479
but has been deleted with https://github.com/Flexget/Flexget/commit/aee85576a71d10dfb5f41d57d2db91d992e62d43
yts is back at https://yts.am
- Restored yts search engine (`flexget/plugins/search_yts.py`) and fixed it to make it work
None
None
Use it with discover plugin the following way:
```
discover:
what:
- ...
from:
- yts: yes
```
```
2018-09-07 12:31 VERBOSE  discover      download        Discovering 48 titles ...
2018-09-07 12:31 INFO     discover      download        Ignoring interval because of --discover-now
2018-09-07 12:31 VERBOSE  discover      download        Searching for `Ghost World` with plugin `yts` (1 of 48)
2018-09-07 12:31 VERBOSE  discover      download        Searching for `Big Bad Wolves` with …
```
=> Restore yts search

flexget/plugins/input/my_anime_list.py
Entries can optionally be filtered by airing status (airing, finished, planned)
The lack of this filter was causing conflict with my config when tracking watch progress of anime that has finished airing with MAL, since I usually get these from a batch manually.
Added new optional parameter `airing_status` to further filter entries as `finished`, `airing` and\or `planned` (also shown as _Not Yet Aired_ on MAL)
```
Syntax:
my_anime_list:
username: <value>
status:
- <watching|completed|on_hold|dropped|plan_to_watch>
- <watching|completed|on_hold|dropped|plan_to_watch>
...
airing_status:
- <airing|finished|planned>
- <airing|finished|planned>
...
type:
- <series|ova...>
```
=> [add] "Airing Status" filter to MyAnimeList

flexget/plugins/sites/lostfilm.py
Update page info formatting on lostfilm.tv
- changed series regexp.
- fix pep8 warnings
=> Update lostfilm page info header parser

flexget/components/parsing/parsers/parser_guessit.py
- Changed casing on the string `Rip`.
- Fixes #2348
=> Guessit: Change to lowercase 'rip' in comparison

flexget/components/notify/notifiers/cronitor.py, requirements.txt
Wanted an uptime monitor. Cronitor is simple and free
- Added cronitor plugin
```yaml
cronitor: ABC123
```
Or:
```yaml
cronitor:
monitor_code: ABC123
on_start: yes
on_abort: no
auth_key: FOOBAR
```
=> Cronitor plugin

flexget/components/notify/notifiers/telegram.py
Some users have problem with access to telegram api url. They need use socks proxy for using telegram plugin.
I've just rebased #2308 over current develop branch, all credits go to @Danfocus.
- Add config settings for socks_proxy
- Feathub #[58](https://feathub.com/Flexget/Flexget/+58).
```
my-task:
notify:
title: {{title}}
message: {{title}}
entries:
via:
telegram:
bot_token: token
use_markdown: no
disable_previews: yes
recipients:
- username: my-user-name
- group: my-group-name
- fullname:
first: my-first-name
sur: my-sur-name
socks_proxy:
url: socks-proxy-url
username: socks-proxy-username
password: socks-proxy-password
```
=> Add socks proxy support for telegram plugin

flexget/plugins/input/betaseries_list.py
Betaseries removed member series listing in the profile API request for perf issues ( See :https://www.betaseries.com/bugs/api/437)
Method 'shows/member' should be used instead
- Changed method from 'members/infos' to 'shows/member'
- Changed JSON parsing to match new method answer 
```
2019-10-21 22:01 DEBUG    utils.requests series-XTHOR-HDTV POSTing URL https://api.betaseries.com/members/auth with args () and kwargs {'data': None, 'timeout
': 30, 'params': {'login': 'Mirgolth', 'password': 'xxxxxx'}, 'headers': {'X-BetaSeries-Version': '2.1', 'Accept': 'application/json
', 'X-BetaSeries-Key': 'xxxxx'}}
2019-10-21 22:01 DEBUG    utils.requests series-XTHOR-HDTV GETing URL https://api.betaseries.com/members/search with args () and kwargs {'timeout': 30, 'param
s': {'login': 'Mirgolth'}, …
```
=> Update to comply with betaseries API change

flexget/ui/v1/package.json
ESlint issue: https://github.com/Flexget/Flexget/network/alert/flexget/ui/v1/package.json/eslint/open
- Updtaed eslint dep
- Removed duplicate codacy dep
=> updated webui deps to remove security vulnerability

docs/develop/index.rst
* Minor RST fixup. Read the Docs' parser didn't seem to care while
pandoc did.
* Remove some unused hyperlink targets.
* Recommend venv rather than virtualenv.
* Some minor language improvements.
Fixes #2376.
=> Improve developer documentation slightly

flexget/plugins/filter/exists.py
Bug fix
- adjust directory iteration to pathlib in exists plugin
- Fixes #2494 .
```
N/A
```
```
N/A
```
=> Replace folder.walk with folder.rglob

flexget/components/sites/sites/argenteam.py
Argenteam API update
- Check if the subtitles tag has children.
- Add information for log control
- Fixes #2351
=> [fix] Fixed issue #2351 with new argenteam API

.github/workflows/main.yml, flexget/components/variables/variables.py, requirements.in, requirements.txt, setup.py
Work with python 3.8
- Updated dependencies to versions that work on 3.8
- Fix an issue with modifying a dictionary during iteration
- Start CI testing on 3.8
=> Support Python 3.8

flexget/plugins/clients/deluge.py
Remove some calls to deprecated deluge api methods
https://discuss.flexget.com/t/deluge-plugin-using-deprecated-apis/4835
=> Remove some deprecated calls to deluge rpc

flexget/components/notify/notifiers/pushover.py
Fix crash in pushover.
- Check for header defensively.
- Fixes #2507
=> [fix] check for 'X-Limit-App-Reset' header. Closes #2507

flexget/components/notify/notifiers/pushbullet.py
Fix the correct plugin this time.
- Fixes #2507
=> [fix] check for header. Closes #2507

flexget/components/notify/notifiers/pushbullet.py
=> [fix] even more check. Closes #2507

flexget/plugins/clients/qbittorrent.py
Incorrect address for adding torrents in older API version in qBittorrent.
=> Fixes wrong API adresses in #2525

flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistInfo.test_npowatchlist_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistLanguageTheTVDBLookup.test_tvdblang_lookup, flexget/tests/cassettes/test_npo_watchlist.TestNpoWatchlistPremium.test_npowatchlist_lookup, flexget/tests/test_npo_watchlist.py
Update the tests to reflect the content changes of npo.nl
(so that my automated testing for keeping track if npo.nl to monitor api changes, remains valid)
=> Update NPO test

flexget/components/tmdb/tmdb_lookup.py
- Add overview to tmdb_lookup plugin like we do with the api endpoint.
=> [Fix]: Add overview to tmdb_lookup

flexget/ui/v1/__init__.py
Fix v1/api redirect so it works for more than just git requests.
=> fix v1/api redirect

flexget/api/core/schema.py
Use url_root instead of base_url so that nested refs work properly
=> fix schema resolve refs

flexget/plugins/input/anilist.py
I made an oopsie and was feeding the wrong value to `al_list_status`.
- Added missing field to the query and assigned it to the Entry field
- Converted query to f-string
=> [fix] Anilist - Correct `al_list_status` value

flexget/components/sites/sites/hebits.py, requirements.in, requirements.txt
Get rid of requests_html as it's not worth the added and problematic deps
- Removed requests_html from deps
- Refactors hebits to ue BS4
- Upgraded BS4 version due to CSS selector upgrade
- Fixes #2571
=> Refactored hebits to use bs4 and upgrade bs4 (#2573). Closes #2571

flexget/config_schema.py, flexget/db_schema.py, flexget/plugin.py, flexget/utils/qualities.py, flexget/utils/requests.py
While doing some type hint stuff, I noticed there should be easier ways to handle the versioned_base stuff. There might even be ways to simplify it further, but this is what I came up with at first. Slightly nervous to merge it straight away, so going to let it sit here for a bit. 😝 If anyone notices problems, let me know.
=> Simplify versioned_base implementation

flexget/plugins/operate/cfscraper.py
Increase tries to solve cloudflare challenge giving a higher probability of solving it correctly. 
- #2614
=> Increase tries to solve challenge

flexget/plugins/operate/cfscraper.py, flexget/utils/requests.py
=> Exceptional error patch rate limit

flexget/plugins/operate/cfscraper.py, flexget/utils/requests.py
Apparently cloudflare challenges get broken by our domain limiting system. This disables our limiting system when responding to a cloudflare challenge. Makes the solution in #2619 less heavy handed.
Haven't tested this myself, would be good if someone who had the issue can confirm this works.
=> Cfscraper limiter fix

flexget/plugins/clients/pyload.py, flexget/plugins/input/json.py
There is an upcoming new version of pyload. This PR is for handling the new API.
=> Added support for pyload-ng API

.gitignore, flexget/components/sites/sites/ettv.py
Make ETTV play nice with html plugin
- Implemented ETTV rewriter plugin
=> [add] ETTV rewriter

flexget/components/ftp/sftp.py
Fix no output plugin warnings for sftp_download plugin.
- Add `SftpDownload.on_task_output()` method
- Fixes https://github.com/Flexget/Flexget/issues/2630
- N/A
N/A
```
flexget/tests/test_abort.py .                                                                                                                                                                        [  0%]
flexget/tests/test_abort_if_exists.py ..                                                                                                                                                             [  0%]
flexget/tests/test_archives.py ....                                                                                                                                                                  [  0%] …
```
=> Fix output task warnings when using sftp_download

flexget/components/sites/sites/lostfilm.py
Link to eposide in RSS was changed.
- Changed regexp to parse season and episode
=> New episode URL in RSS

flexget/components/sites/sites/filelist.py, flexget/components/sites/sites/filelist_api.py
Filelist released an API which can be used to search for torrents, this should replace the old search plugin which scraped the site.
=> [change] new search plugin for Filelist with API

flexget/ui/v2/__init__.py, flexget/ui/v2/index.html
- Changed Wiki links
- Correct dead link to WebUi wiki entry
=> Correcting dead link to WebUi

.github/workflows/no-prs-to-master.yml
=> Add a workflow that auto fails on prs made to the master branch

flexget/components/sites/sites/iptorrents.py
To be able to search IPTorrents for freeleech-only results.
- Added a `free` parameter to the IPTorrents search plugin schema that will include `&free=on` in the URL if set to `True`.
- N/A
- N/A
```
discover:
what:
- next_series_episodes: yes
from:
- iptorrents:
rss_key: ***
uid: ***
password: ***
free: True <---
```
```
> bin/flexget execute --tasks SEARCH_TV --discover-now --no-cache
2020-06-08 15:57:28 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-06-08 15:57:28 VERBOSE  series        SEARCH_TV       Series `RuPaul's Drag Race` is already configured in series plugin
2020-06-08 15:57:28 VERBOSE  series        SEARCH_TV       Series `Better Call Saul` is already configured in series plugin
2020-06-08 15:57:28 …
```
=> [add] Added free parameter to iptorrents search plugin

flexget/components/ftp/sftp_client.py
This fixes a regression introduced when I refactored the SFTP plugin.
- Add private_key and private_key_pass to entries produced by the SftpList plugin
- Fixes # https://github.com/Flexget/Flexget/issues/2692
=> Add private_key and private_key_pass to SftpList entries.

flexget/api/templates/swagger-ui.html
The upgrade to flask-restx brok the api docs since it's an updated version of swagger. This should fix it.
=> [Fix] API docs

flexget/components/sites/sites/piratebay.py
- Current piratebay search plugin has been broken since 3rd party website redesign. Static HTML parsing no longer works.
- Use piratebay JSON API (https://apibay.org) instead.
- Maintain support for old config and mirrors (such as TOR address http://piratebayztemzmv.onion/).
- Static HTML parsing no longer works due to 3rd party change.
```
tasks:
test-piratebay:
seen: no
discover:
what:
- rss: https://www.rogerebert.com/feed
from:
- piratebay:
category: highres movies
sort_by: seeds
url: https://apibay.org/
release_estimations: ignore
```
```
C:\Users\tuant\PycharmProjects\Flexget\venv\Scripts\python.exe C:/Users/tuant/PycharmProjects/Flexget/flexget_vanilla.py --loglevel=debug -c test-piratebay.yml execute --discover-now --now
2020-08-02 10:21:05 DEBUG    manager …
```
=> switched piratebay to new API due to breaking change from 3rd party

flexget/components/sites/sites/piratebay.py, flexget/tests/test_urlrewriting.py
Tests were broken when #2713  was merged. This fixes them
=> fix url rewriting tests for pirate bay

.gitignore, flexget/__init__.py, flexget/config_schema.py, flexget/db_schema.py, flexget/entry.py, flexget/event.py, flexget/ipc.py, flexget/log.py, flexget/manager.py, flexget/options.py, flexget/plugin.py, flexget/plugins/internal/api_bluray.py, flexget/plugins/internal/api_rottentomatoes.py, flexget/task.py, flexget/task_queue.py, flexget/terminal.py, flexget/tray_icon.py, flexget/webserver.py, setup.py, update-changelog.py
Add/enrich type annotations
- Add type annotation to `update-changelog.py` and files directly under `flexget` module
- Add `mypy_cache/` and `dmypy.json` to gitignore
```
❯ dmypy run -- --follow-imports=skip flexget/*.py  | tail -1
Found 174 errors in 14 files (checked 16 source files)
❯ dmypy run -- --follow-imports=skip flexget/*.py  | tail -1
Found 83 errors in 14 files (checked 16 source files)
```
I can keep adding commits to this PR
- No such issue exists, we can add one if you wish
=> Add type annotations (top-level files)

.github/workflows/main.yml, flexget/tests/test_rtorrent.py, pyproject.toml, requirements.in, requirements.txt, setup.py
=> Start testing python 3.9

flexget/components/sites/sites/iptorrents.py
A lot of the css classes were removed on the IPT site, which the
previous code relied on. Instead, this parses the table headers.
The html.parser doesn't parse tables correctly so I switched it to
html5lib. Specifically, `<td><td><td>` would create a nested
structure instead of siblings.
- Fixes https://github.com/Flexget/Flexget/issues/2769 .
I don't think there is a test for this? The log looks like the normal log when everything is working. You might have to pass `--discover-now`.
=> [fix] iptorrents: parse new search page redesign

flexget/plugins/clients/transmission.py
Forgot partial import
- Fixes #2777
=> added partial import

flexget/plugins/clients/transmission.py
[`transmissionrpc`](https://pypi.org/project/transmissionrpc/) is unmaintained. Swap to [`transmission-rpc`](https://pypi.org/project/transmission-rpc/) as suggested in #2727.
Drop-in replacement of imports.
The newer `transmission-rpc` does not provide `HTTPHandlerError`. Instead it raises exceptions from `requests.exceptions`. Error handling on connecting to transmission has to be changed accordingly.
-  #2727  .
Error handling could be more fine-grained, but `requests.exceptions` are very detailed as they are.
=> Replace obsoleted and unmaintaned transmissionrpc

flexget/components/bittorrent/convert_magnet.py
Implements fix reported in issue #2424 .
=> implements sugested fix of issue #2424

flexget/plugins/clients/transmission.py
The new `transmission-rpc` library doesn't use the host parameter for the protocol and path as the old `transmissionrpc` library did, these have to be given as separate parameters.
This PR is to make the host config option backwards compatible by parsing it with urlparse and passing them on. I'm also stripping out `rpc` from the path as the new library adds it on as seen [here](https://github.com/Trim21/transmission-rpc/blob/master/transmission_rpc/client.py#L109).
- Parse the host config value
- If protocol/scheme isn't given, use `http` otherwise urlparse doesn't do well
- Strip out `rpc` from the path if given
- Pass protocol and path to the library
=> [fix] Transmission: Make host config option backwards compatible

flexget/components/sites/sites/torrentday.py
Plugin did not return any titles.
Edited request to current torrentday settings. Parsing of page failed previously since minor changes in layout. This PR also fixes searching in certain categories which did not work due to parameter changes on site. 
Also added aliases for a couple of missing categories.
- Fixes #2742
N/A
N/A
N/A
=> Fix for torrentday search

flexget/components/notify/notifiers/telegram.py
Enable message transmission to the Telegram channel
=> [fix] Containment Test

flexget/plugins/input/from_telegram.py, flexget/plugins/input/telegram_input.py
Add the ability to input entries from a telegram chat
- Created telegram_input plugin
secrets.yml
```
telegram:
token: "<<my token>>"
from: [{username: "<< MyUser Name >>" }]
```
config.yml
```
variables: secrets.yml
tasks: 
#Task To add a Movie to the Queue
Telegram_Add_Movie:
disable:
- seen
- retry_failed
imdb_lookup: yes
from_telegram:
token: "{? telegram.token ?}"
only_new: yes
types:
- "private"
- "group"
whitelist: "{? telegram.from ?}"
entry:
title: download (?:movie )?(.*)
require_field:
- imdb_name
- imdb_id
list_add: 
- movie_list: download_movie
notify:
entries:
message: |+
Ok, i'll download {{imdb_name}}
[Imágem]({{(tvdb_posters|d|first )|d(imdb_photo)|d|replace("_", "%5F")}})
via:
- telegram:
bot_token: "{? telegram.token …
```
=> [add] Add Telegram Input Plugin

flexget/plugins/cli/try_regexp.py, flexget/plugins/clients/transmission.py, flexget/plugins/filter/accept_all.py, flexget/plugins/filter/age.py, flexget/plugins/filter/delay.py, flexget/plugins/filter/exists.py, flexget/plugins/filter/proper_movies.py, flexget/plugins/filter/regexp.py, flexget/plugins/filter/rottentomatoes.py, flexget/plugins/filter/thetvdb.py, flexget/plugins/input/anilist.py, flexget/plugins/input/apple_trailers.py, flexget/plugins/input/my_anime_list.py, flexget/plugins/internal/change_warn.py, flexget/plugins/modify/extension.py, flexget/plugins/modify/path_by_ext.py, flexget/plugins/modify/plugin_priority.py, flexget/plugins/modify/reorder_quality.py, flexget/plugins/operate/interval.py, flexget/plugins/operate/sequence.py, flexget/plugins/operate/spy_headers.py, flexget/plugins/output/dump_config.py
Better readability on docstrings
- Just ran black on plugins folder
- Inconsistant docstrings in plugins
=> Formatted plugins with new black

.pre-commit-config.yaml, dev-requirements.txt
Get pre-commit hooks working again
- Changes to pre-commit config and dev-requirement to allow for newer versions
=> Update some dev-tools to new versions

flexget/components/emby/api_emby.py, flexget/components/emby/emby_list.py, flexget/components/emby/emby_lookup.py, flexget/components/emby/emby_refresh.py, flexget/components/emby/emby_util.py, flexget/components/emby/from_emby.py
Emby is a media manager, like plex, and a lot can be pulled from there, listed series, listed movies, information regarding the medias present (audio languages, versions etc) and much more.
Also we can monitor our media with watch and favorites. 
All this can be pulled and applied to flexget. Create lists, change watch status in emby, add or remove favorites, create lists, etc
- Add emby_lookup - Retrieve information from emby to fill entry
- Add from_emby - Retrieve entries from emby library
- Add emby_list - Retrieve and manipulate emby library
- Add emby_refresh - Trigger emby to refresh library
- None
- None
```
tasks: 
emby_refresh:
disable:
- seen
- retry_failed
emby_refresh:
server:
host: http://emby.localhost:8096
username: flexget
return_host: …
```
=> Emby Components

dev-requirements.txt, requirements.txt
Dependabot alert address
- Ran pip-compile -U
- Vuln in urllib3
=> Update frozen deps

.pre-commit-config.yaml
Dependabot alert again
- Merge Dependabot PRs + pre-commit autoupdate
=> Update black to 21.4b2

Dockerfile
Sorry for the trouble. I just found that previous PR #2952 didn't cover all cases. It may fail with a new major version.
=> add rpc library version range again

flexget/components/emby/api_emby.py
Should check if no persist data exists
- Check if persist data exists
=> [fix] emby: Handle no persist data

flexget/components/emby/api_emby.py
In emby all search should be preformed without the year
- Strip year from the searches
=> [fix] emby: strip year in search

flexget/components/sites/sites/piratebay.py
Avoid crash if invalid json response from piratbay
- handle exception JSONDecodeError
- Fixes #2756
```
download-movies: 
priority: 4   
imdb_lookup: yes  # can also use imdb_lookup or tmdb_lookup
discover:
what:
- movie_list: watchlist
from:
- piratebay:
sort_by: seeds
category: video
url: https://www1.thepiratebay3.to/
- rarbg:
category: [48, 44, 14, 45, 17]
sorted_by: seeders
interval: 30 minutes        
```
```
2021-05-05 16:45:01 DEBUG    utils.requests download-movies GETing URL https://www1.thepiratebay3.to/q.php with args () and kwargs {'params': {'q': 'The Matrix', 'cat': 200}, 'allow_redirects': True, 'timeout': 30}
2021-05-05 16:45:02 ERROR    discover      download-movies Error searching with piratebay: Error while searching piratebay for The Matrix, invalid json response
```
=> [fix] piratbay: invalid json response

flexget/components/emby/api_emby.py
Fixes login and list matching
- The login was not renewing when token changed, fixed
- The list was not matching correctly episodes in some cases, added a new matching
=> [fix] emby: login and list matching

flexget/components/emby/api_emby.py
The entry should be matched with the emby list to ensure that the items can be added or removed... This sometimes can be difficult, depending on the available information on the entry. This PR improves the matching to be more accurate
- Improve the matching of the movie and episode series
Reported on Discord by @ProteinPig
Example provided by discord user @ProteinPig
```
templates:
global:
no_entries_ok: yes
pathscrub: windows
parsing:
movie: guessit
series: guessit
anchors:
_3rd_wanted_movies: &3rd_wanted_movies
emby_list:
server:
host: http://localhost:8096
username: *****
password: *****
return_host: lan
list: "Wanted Movies"
tasks:
sync.add_new_movies_to_3rd:
priority: 999
movie_list: wanted-movies
list_match:
from:
- <<: *3rd_wanted_movies
action: reject
remove_on_match: no …
```
=> [fix] emby: ensure entry is matched with list item

flexget/components/imdb/utils.py
Imdb changed the layout and the dom tree had some big differences! From what I can tell the transition is still under way, so it's better to keep both versions active for now
- Changed imdb parser to try the new layout if the old failed
- Fixes #3014
=> [fix] imdb: parse new layout

flexget/components/emby/api_emby.py, flexget/components/emby/emby_lookup.py
Make more searches with different fields if first search fails! This will help to make a better matching of media with the media in emby
- Add research with movie and serie title if failed by provider (for example imdb_id)
=> [fix] emby: Research if first search fails

flexget/components/emby/api_emby.py, flexget/components/emby/emby_lookup.py, flexget/components/emby/emby_util.py, flexget/components/emby/from_emby.py
Emby allows to login using a public proxy kwon as emby connect, this PR makes it possible to login to a server via the Emby Connect login
Also added the interface to use discover in from_emby
- Add emby connect validation and connect endpoints
- Add interface with discover search in from_emby
=> [fix] emby: allow emby connect login

flexget/plugins/input/letterboxd.py
This plugin uses tmdb plugin to do a lookup. This should handle the exceptions
- Handle exceptions in the lookup, also validade if movie contains a tmdb_id before lookup 
- Fixes #2998
```yaml
accept_all: true
disable: seen
free_space:
allotment: -1
path: /media/video-nas/
port: 22
space: 5000
letterboxd:
list: netflix-stand-up-comedy
sort_by: default
username: redacted
list_add:
- trakt_list:
account: redacted
list: netflix-stand-up-comedy
strip_dates: false
type: auto
username: redacted
metainfo_movie: true
no_entries_ok: true
parsing:
movie: guessit
pathscrub: windows
priority: 191
sort_by: added
template:
- movies-metainfo
trakt_lookup:
account: redacted
username: redacted
```
```
2021-05-27 11:24:00 WARNING  letterboxd    letterboxd      Can't search tmdb, no tmdb_id
2021-05-27 …
```
=> [fix] letterboxd: Handle no tmdb id

flexget/components/sites/sites/lostfilm.py
Added new site mirror to improve chances of successful connection
=> lostfilm plugin: added new mirror

flexget/components/sites/sites/ettv.py
- updated ettv download link selector
=> [fix] update ettv download link selector

flexget/utils/qualities.py
- 
- Fixes # .
```
```
```
```
=> Added dovi to color profile 50 (Dolby Vision)

flexget/components/managed_lists/lists/imdb_list.py
Change the mapping of cookie fields
- Changed the mapping of the cookie fields that was wrong in the schema
=> [fix] imdb_list: cookie login field map

.github/workflows/main.yml, .github/workflows/release.yml
- updated main and release workflows to use native pip caching
=> use native pip caching

flexget/tests/test_asciify.py, flexget/tests/test_jinja_filters.py, flexget/utils/template.py
Adds filters to normalize text
- Added filters
``` yaml
tasks:
asscify_me:
mock:
- {"title":"[My](Tìtlê)-ìs a' me^ss", "url":"mock://local" }
set:
title1: "{{title|asciify|replace('is','is still')}}"
title2: "{{title|strip_symbols|replace('ìs','ìs still')}}"
title3: "{{title|asciify|strip_symbols|replace('is','is not')}}"
```
```
title1           : [My](Title)-is still a' me^ss
title2           : My Tìtlê ìs still a mess
title3           : My Title is not a mess
```
=> [add] normalize filter

flexget/plugins/internal/api_bluray.py
Handle invalid json response from api
- Add try
- Fixes #3115
=> [fix] api_bluray: Invalid JSON handle

flexget/components/managed_lists/lists/imdb_list.py
Assume "tvspecial" as a movie in imdb_list
- Added tvspecial to movie type matching
- Fixes #3310
=> [fix] imdb_list: assume tvspecial

flexget/plugins/clients/qbittorrent.py
Avoid plugin errors when adding a invalid torrent to qBittorrent as reported in Issue #3312.
I was never able to recreate this error in my environment, but this push should fix this problem and future problems that are a result of a error adding a torrent to the client.
- Replaced plugin errors with log errors and fail entry to try again if possible
- Fixes #3312
=> [fix] qBittorrent: Avoid plugin error adding file

flexget/components/seen/cli.py, flexget/components/seen/db.py, flexget/manager.py
Adds new option to CLI seen to allow to search, forget, add specifying a task. This is very useful to maintain the entries via cli.
- Added the --tasks option to search, this will search only on that specific tasks.
- search value input was changed and implicit adding of '%' was removed, to add a '%' to the like it should be added a '*', this was done to make the output of search uniform to the actions on forger. Allowing to test a command before removing the entry
- Added the --tasks option to forget, this will forget only on that specific tasks.
- Allow to add '*' to match any char in forget, the forgotten entries should be the same that would output with the same parameters in search.
- Added the --task option to add. This will add a local entry to that specific task
```yaml
tasks: …
```
=> [add] seen cli: add task options

flexget/components/sites/sites/magnetdl.py, flexget/plugins/input/magnetdl.py, flexget/task.py
Add input for magnetdl
```
magnetdl:
category: tv
pages: 5
```
=> [add] magnetdl input

flexget/components/sites/sites/hebits.py
recently hebits had transition to gazelle based site
```yaml
trakt-movies-search:
template:
- global
- movie
priority: 10 # run after the movie queue fill task
discover:
what:
- movie_list: movies
from:
- hebits:
userid: 1337
session: "1CIecR845NxF8qmahs6sS4oGTbSP5USmHYiL8U3uaD108zL2RW7R4LIngCbqdCRG"
category: movies
interval: 1 hour
tmdb_lookup: yes
list_match:
from:
- movie_list: movies
```
=> overhaul hebits search plugin

dev-requirements.in, dev-requirements.txt, requirements.in, requirements.txt
- 
- Fixes # .
```
```
```
```
=> Upgrade all deps

flexget/components/imdb/utils.py
FIX: handles imdb genres if empty.
=> FIX: handles imdb genres if empty.

flexget/plugins/input/my_anime_list.py
Allows for more than 300 results (may the lord have mercy on your soul)
The referenced issue
- Added pagination logic with offsets
- Reordered some lines to group logic
- Updated to f-strings
- Updated as an entry generator (makes it compatible with `limit` plugin)
- Fixes #3421 .
=> [change] Added pagination to `my_anime_list`

flexget/_version.py, flexget/components/sites/sites/ncore.py
```
ncore:
username: 'username'
password: 'password'
category: ['hd_hun', 'xvid_hun'] #optional
sort_by: 'size' #optional
sort_reverse: true #optional
```
```
2022-06-06 22:30:24 VERBOSE  discover      movies search   Discovering 6 titles ...
2022-06-06 22:30:24 INFO     discover      movies search   Ignoring interval because of --discover-now
2022-06-06 22:30:24 VERBOSE  discover      movies search   Searching for `Spider-Man: No Way Home (2021)` with plugin `ncore` (1 of 6)
2022-06-06 22:30:25 VERBOSE  discover      movies search   Searching for `Inception (2010)` with plugin `ncore` (2 of 6)
2022-06-06 22:30:26 VERBOSE  discover      movies search   Searching for `The Lost City (2022)` with plugin `ncore` (3 of 6)
2022-06-06 22:30:27 VERBOSE  discover      movies search   Searching for …
```
=> added ncore site

flexget/plugins/input/html.py
Some sites will return 404 at pagination stop. Currently that causes the task to abort due to an uncaught `HTTPError`.
When `stop_when_404` is set to `false`, the `HTTPError` thrown by `requests` will bubble up (default and existing behaviour) - aborting the task. If it is set to `true`, the `HTTPError` will be caught and iteration will halt as if an empty page was returned and `stop_when_empty` was set to `true`.
N/A
N/A
```
html:
url: https://www.giantbomb.com/api/show-episode/19801/?display_type=1&display_order=0&page={{i}}
increment:
from: 1
stop_when_404: true
entries_count: 999
```
```
2021-11-20 14:22:15 VERBOSE  html          giant-bomb-unprofessional-fridays Requesting: https://www.giantbomb.com/api/show-episode/19801/?display_type=1&display_order=0&page=1
2021-11-20 14:22:15 …
```
=> html plugin: add stop_when_404 increment option

flexget/plugins/clients/aria2.py
Support https for aria2 plugin.
- Add `use_ssl` option to aria2 plugin
`use_ssl` is a boolean value (default to false)
- `true`: Connect to aria2 by HTTPS
- `false`: Connect to aria2 by HTTP (same as original)
N/A
N/A
```yaml
aria2:
server: domain.com
port: 443
use_ssl: true    # New option here
secret: 'password'
path: '/downloads'
```
```log
2022-06-08 22:25:14 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2022-06-08 22:25:14 VERBOSE  proxy         auto_anime_2022_4_shishangzuiqiangdedamowangzhuanshengweicunminA_LoliHouse Setting proxy to {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
2022-06-08 22:25:16 VERBOSE  details       auto_anime_2022_4_shishangzuiqiangdedamowangzhuanshengweicunminA_LoliH …
```
=> Add ssl support for aria2 plugin

flexget/components/notify/notifiers/bark.py
Push notification to Bark client
- Add a  new notifier
- N/A
- N/A
```
notify:
entries:
what: rejected  #only for test
title: |
{{task}}
message: |
{% if series_name is defined %}{{series_name}}{% if series_id is defined %} - {{series_id}}{% endif %}{% if trakt_ep_name is defined %} - {{trakt_ep_name}}{% endif %}
{% elif imdb_name is defined%}{{movie_name}}
{% else %}{{title}}
{% endif %}
via:
- bark:
server:  https://******
device_key: ******
```
flexget
```
2022-07-31 18:48:38 VERBOSE  details       MadeinAbyss     Produced 3 entries.
2022-07-31 18:48:38 VERBOSE  task          MadeinAbyss     REJECTED: `[桜都字幕组] 来自深渊 烈日的黄金乡 / Made in Abyss： Retsujitsu no Ougonkyou [03][1080p][简繁内封]` by seen plugin because entry with title `[桜都字幕组] 来自深渊 烈日的黄金乡 / Made in Abyss： Retsujitsu no Ougonkyou …
```
=> Notify support for Bark

.github/workflows/docker-image.yml
- add caching for faster builds
- added qemu builder, github caching, metadata provider for tags and labels
=> [add] docker: build caching

flexget/components/sites/sites/morethantv.py
=> [fix] morethantv domain (#3492)

Dockerfile
should copy webui to new python path
- Fixes #3580
caused by https://github.com/Flexget/Flexget/pull/3574
=> fix webui in 3.10 new python path

.github/workflows/main.yml
Support FlexGet on python 3.11
=> Python 3.11 Support

flexget/plugins/clients/transmission.py
Some useful fields for cleaning up stalled torrents.
=> Add activityDate and isStalled to transmission input

flexget/components/sites/sites/magnetdl.py
Fix missing import unicodedata from my previous merged request. Sorry about that.
I'm getting "name 'unicodedata' is not defined" errors. I think there's a missing `import unicodedata` at the top
_Originally posted by @yukatapangolin in https://github.com/Flexget/Flexget/issues/3644#issuecomment-1369339372_
=> [fix] magnetdl search error 404

flexget/manager.py
=> [Fix] link to version_checker in manager.py log message

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .dockerignore, .gitignore
vscode [devcontainers](https://code.visualstudio.com/docs/remote/containers) is one of the biggest steps forward in development and DevOps that I have ever seen. In my opinion it is bigger than Kubernetes or Terraform.
Unfortunately the documentation for the feature is a bit lacking. So let me explain. A devcontainer is just a docker container that has all the things needed for development already configured. Things like the correct version of python, the application and its dependencies and other tools like `pre-commit`. 
The magic is that if you are using vscode, then the IDE will run INSIDE the devcontainer. That means you will get really strong typing and intellesense as well as see errors/warnings from linting and formatting tools inside your IDE as you type. 
It's also make its …
=> add vscode dev container to project

flexget/components/irc/irc.py
Update irc to download tracker config correctly
=> Update irc to download tracker config correctly

flexget/plugins/clients/qbittorrent.py
I need this
Added new from_qbittorrent plugin, following other similar plugins
=> [add] from_qbittorrent plugin

Dockerfile, dev_tools.py
- 
- Fixes # .
```
```
```
```
=> build: only bundle v2 webui

flexget/components/sites/sites/newznab.py
Fix issue where newznab plugin loses the API key and category on successive searches.
- Stopped mutating config in favor of returning URL and parameters
=> nzbnab_parameters

flexget/components/sites/sites/ncore.py
Fixing minor bugs
- Seed and leech text converted to numbers
- Torrent title now uses tool-tip text instead of displayed text as it is sometimes shortened
- Using proper size conversion
=> ncore site fixes

flexget/plugins/output/file_operations.py
On certain filesystem shutil.copy can fail due to difference in filesystems between the source and destination (like in truenas when the target fs has ACLs).
this change makes the mode change warn instead of failing the command allowing it to function in such cases.
Create an implementation of the copy command from shutil which does not fail on copymode and just warn instead
=> copy files fails when copying between certain file systems.

.github/workflows/release.yml
original action is using deprecated node 12 base
- switch to forked action with node 16 base 
- https://github.com/justacodename/deployment-status
=> change: update deliverybot action

flexget/plugins/filter/best_quality.py
The best_quality plugin was just considering the first entry as the best quality, and that's not always true, many entries can have the same quality as the best.
Added comparison of every entry with the best quality.
=> [change] Update best_quality.py

flexget/plugins/input/anilist.py
I needed it
- Token based rate limiter and wait based on response header if we still hit it since sometimes they restrict it further from the documented limit.
- Include almost all metadata fields available.
- Call the `v2` endpoint of the relations API, providing `TheTVDB` and `TMDB` IDs (no season though)
- N/A
```
N/A
```
=> Anilist: Handle rate-limit and add more metadata

flexget/manager.py
- 
- Fixes # .
```
```
```
```
=> feat(manager): rm lock on ipc unconnectable

.github/workflows/main.yml
Tried to add publishing of test results to make failing tests a bit more visible. Failed with my simple attempt directly in the develop branch, fixing it here.
=> Fix test result publishing

flexget/components/notify/notifiers/telegram.py
After https://github.com/Flexget/Flexget/pull/4083#issuecomment-2540074040 all users have to install package `python-telegram-bot`, even though they don't use telegram.
=> Fix for people who don't use telegram

pyproject.toml, uv.lock
=> Revert "Update dependency urllib3 to v2"

renovate.json
This PR will not change Renovate's behavior. It simply simplifies the configuration by using presets, which is recommended by Renovate.
The current configuration is too verbose. This PR makes it more concise.
> [!TIP]
Also, be sure to check out Renovate's shareable config presets to save yourself from reinventing any wheels.
>
>_Originally posted on https://docs.renovatebot.com/configuration-options/#:~:text=branch%20if%20present.-,Also%2C%20be%20sure%20to%20check%20out%20Renovate%27s%20shareable%20config%20presets%20to%20save%20yourself%20from%20reinventing%20any%20wheels.,-Shareable%20config%20presets_
=> Follow Renovate's best practices

Dockerfile
Fix https://github.com/Flexget/Flexget/pull/4117#issuecomment-2574186470
=> switch to a specific version

flexget/components/estimate_release/estimators/est_series_tvmaze.py, flexget/components/imdb/imdb.py, flexget/components/notify/notifiers/telegram.py, flexget/components/pending_approval/cli.py, flexget/components/pending_approval/pending_approval.py, flexget/components/seen/db.py, flexget/components/series/db.py, flexget/components/series/internal_estimator.py, flexget/components/series/next_series_episodes.py, flexget/components/series/series.py, flexget/components/status/cli.py, flexget/plugins/internal/api_rottentomatoes.py, flexget/tests/api_tests/test_seen_api.py, flexget/tests/test_trakt.py, pyproject.toml
Use more idiomatic comparisons rather than add noqas in #4134
=> Clean up comparisons to None/True/False

renovate.json
PRs like these should be considered safe to merge once they pass tests:
```diff
- FROM docker.io/python:3.11-alpine3.20@sha256:6ed2b959e83a80b1611cce777d225097270e3c34c76755e60d357c869c04ccd7
+ FROM docker.io/python:3.11-alpine3.20@sha256:9e61b9dc6493270b15dae7189e6731423d155a1f13b8e82a0dea4c1c8190044c
- uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
+ uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3
```
Pinning digests ensures consistent, secure, and reproducible builds by locking exact package versions and content. It prevents discrepancies, tampering, and dependency drift across environments.
However, pinning digests can increase maintenance overhead, as any update to dependencies requires regenerating and verifying the hashes. …
=> Automerge digest PRs

.github/workflows/docker-image.yml
Fix https://github.com/Flexget/Flexget/pull/4144#discussion_r1912480600
=> Fix Docker image name

flexget/terminal.py, flexget/tests/test_asciify.py, flexget/tests/test_content_filter.py, flexget/tests/test_discover.py, flexget/tests/test_download.py, flexget/tests/test_manipulate.py, flexget/tests/test_pending_list.py, flexget/tests/test_plex_watchlist.py, flexget/tests/test_radarr_list.py, flexget/tests/test_regexp.py, flexget/tests/test_series.py, flexget/tests/test_sftp_list.py, flexget/tests/test_sonarr_list.py, flexget/tests/test_timeframe.py, flexget/tests/test_trakt.py, flexget/tests/test_upgrade.py, flexget/tests/test_yaml_list.py, pyproject.toml
Remove redundant whitespaces.
https://docs.astral.sh/ruff/rules/#warning-w
=> Adopt the `W` rules

.editorconfig
Remove `.editorconfig` becuase this file should not be added to Git.
=> [remove] Remove `.editorconfig` becuase this file should not be added to Git

.github/workflows/autofix.yml, .github/workflows/changelog.yml, .github/workflows/docker-image.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/test.yml
Add a name to each step in the GitHub Actions workflow to enhance readability.
I did not make any changes to the logic or functionality.
=> Add a name to each step in the GitHub Actions workflow to enhance readability

flexget/api/core/tasks.py, flexget/components/bittorrent/trackers.py, flexget/components/emby/api_emby.py, flexget/components/ftp/ftp_download.py, flexget/components/imdb/utils.py, flexget/components/irc/irc.py, flexget/components/managed_lists/lists/entry_list/entry_list.py, flexget/components/notify/notifiers/discord.py, flexget/components/series/db.py, flexget/components/sites/sites/eztv.py, flexget/log.py, flexget/plugins/cli/try_regexp.py, flexget/plugins/clients/aria2.py, flexget/plugins/filter/regexp.py, flexget/plugins/input/rss.py, flexget/plugins/metainfo/content_size.py, flexget/plugins/modify/sort_by.py, flexget/plugins/output/download.py, flexget/plugins/output/subtitles.py, flexget/tests/test_feed_control.py, flexget/utils/log.py, flexget/utils/parsers/generic.py, flexget/utils/parsers/parser.py, flexget/utils/parsers/series.py, flexget/utils/template.py, flexget/webserver.py, pyproject.toml
The `B` rules find likely bugs and design problems in the program.
All modifications are manual.
https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
=> Adopt the `B` rules

flexget/tests/api_tests/test_database_api.py, flexget/tests/conftest.py, flexget/tests/notifiers/conftest.py, flexget/tests/test_configure_series_betaseries_list.py, flexget/tests/test_cookies.py, flexget/tests/test_next_series_episodes.py, flexget/tests/test_next_series_seasons.py, flexget/tests/test_path_by_space.py, flexget/tests/test_pluginapi.py, flexget/tests/test_qualities.py, flexget/tests/test_series.py, flexget/tests/test_sort_by.py, flexget/tests/test_utils.py
https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
All modifications are automatic fixes.
=> Adopt the `PT` rules.

flexget/tests/test_misc.py, flexget/tests/test_pathscrub.py, flexget/tests/test_seen.py, flexget/tests/test_series.py, flexget/tests/test_seriesparser.py, flexget/tests/test_trakt.py, flexget/tests/test_utils.py, flexget/tests/test_wordpress.py, pyproject.toml
https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
All modifications are manual.
=> Adopt the `PT` rules

flexget/components/imdb/utils.py, flexget/components/sites/sites/serienjunkies.py, flexget/manager.py, flexget/plugins/daemon/web_server.py, flexget/plugins/input/regexp_parse.py, flexget/plugins/modify/extension.py, flexget/plugins/modify/manipulate.py, flexget/plugins/services/kodi_library.py, flexget/plugins/services/pogcal_acquired.py, flexget/utils/parsers/parser.py, pyproject.toml
All modifications are automatic fixes.
FURB: https://docs.astral.sh/ruff/rules/#refurb-furb
YTT: https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
=> Adopt the `FURB` and `YTT` rules

dev_tools.py, flexget/components/sites/sites/magnetdl.py, flexget/plugins/metainfo/nfo_lookup.py, flexget/plugins/output/file_operations.py, flexget/utils/qualities.py, pyproject.toml
All modifications are automatic fixes.
RSE: https://docs.astral.sh/ruff/rules/#flake8-raise-rse
=> Adopt the `RSE` rules

flexget/components/emby/api_emby.py, flexget/components/sites/sites/lostfilm.py, flexget/config_schema.py, flexget/tests/conftest.py, pyproject.toml
FLY: https://docs.astral.sh/ruff/rules/#flynt-fly
=> Adopt the `FLY` rules

flexget/api/core/server.py, flexget/api/core/tasks.py, flexget/components/archive/archive.py, flexget/components/archive/cli.py, flexget/components/backlog/cli.py, flexget/components/emby/from_emby.py, flexget/components/ftp/ftp_list.py, flexget/components/imdb/imdb_watchlist.py, flexget/components/irc/irc.py, flexget/components/managed_lists/lists/entry_list/cli.py, flexget/components/managed_lists/lists/movie_list/cli.py, flexget/components/managed_lists/lists/pending_list/cli.py, flexget/components/parsing/parsers/parser_guessit.py, flexget/components/seen/db.py, flexget/components/series/api.py, flexget/components/series/db.py, flexget/components/sites/sites/magnetdl.py, flexget/components/sites/sites/rlsbb.py, flexget/components/sites/sites/serienjunkies.py, flexget/components/sites/urlrewrite.py, flexget/plugins/cli/doc.py, flexget/plugins/clients/rtorrent.py, flexget/plugins/output/file_operations.py, flexget/plugins/output/subtitles.py, flexget/utils/bittorrent.py, flexget/utils/sqlalchemy_utils.py, pyproject.toml
All fixes are manual.
PERF: https://docs.astral.sh/ruff/rules/#perflint-perf
=> Adopt the `PERF` rules 

flexget/components/bittorrent/torrent_match.py, flexget/components/imdb/imdb_watchlist.py, flexget/components/managed_lists/lists/couchpotato_list.py, flexget/components/parsing/parsers/parser_common.py, flexget/components/series/db.py, flexget/components/sites/sites/morethantv.py, flexget/components/trakt/api_trakt.py, flexget/components/trakt/db.py, flexget/components/tvmaze/api_tvmaze.py, flexget/plugins/clients/rtorrent.py, flexget/plugins/output/download.py, flexget/tests/api_tests/test_tasks_api.py, flexget/tests/test_download.py, flexget/tests/test_next_series_seasons.py, flexget/tests/test_sftp_server.py, flexget/utils/cache.py, flexget/utils/parsers/series.py, pyproject.toml
`TD` rules: https://docs.astral.sh/ruff/rules/#flake8-todos-td
=> Adpot the `TD` rules

flexget/components/archives/utils.py, flexget/components/ftp/sftp_client.py, flexget/components/managed_lists/lists/ombi_list.py, flexget/components/notify/notifiers/telegram.py, flexget/db_schema.py, flexget/plugins/input/html.py, pyproject.toml
This PR only includes automatic fixes for the [TRY400](https://docs.astral.sh/ruff/rules/error-instead-of-exception/) rule. The benefits of adopting this rule are explained in the [linked document](https://docs.astral.sh/ruff/rules/error-instead-of-exception/#why-is-this-bad). Manual fixes for the `TRY` rule will be included in a separate PR.
=> Adopt the `TRY` rule (This PR only includes automatic fixes)

dev_tools.py, flexget/api/core/server.py, flexget/components/archives/utils.py, flexget/components/emby/api_emby.py, flexget/components/sites/sites/alpharatio.py, flexget/components/sites/sites/bakabt.py, flexget/components/sites/sites/deadfrog.py, flexget/components/sites/sites/magnetdl.py, flexget/components/sites/sites/newtorrents.py, flexget/components/sites/sites/serienjunkies.py, flexget/config_schema.py, flexget/plugins/clients/rtorrent.py, flexget/plugins/metainfo/nfo_lookup.py, flexget/tests/test_path_by_space.py, flexget/tests/test_trakt_list_interface.py, pyproject.toml
All fixes were applied automatically.
PIE: https://docs.astral.sh/ruff/rules/#flake8-pie-pie
=> Adopt the `PIE` rules

Dockerfile
Fix: Docker image does not include the Web UI (caused by #4163)
=> Fix: Docker image does not include the Web UI (caused by #4163)

.github/workflows/autofix.yml, .github/workflows/changelog.yml, .github/workflows/docker-image.yml, .github/workflows/nightly.yml, .github/workflows/no-prs-to-master.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/test.yml
This PR integrates [Zizmor](https://woodruffw.github.io/zizmor/) to identify security vulnerabilities in GitHub Actions workflows. By leveraging Zizmor, we can proactively detect misconfigurations and potential security risks, improving the overall security posture of our CI/CD pipelines.  
- **Early detection of security issues** in GitHub Actions workflows  
- **Automated scanning** to ensure best practices are followed  
- **Improved security compliance** with minimal manual effort  
Notably, projects such as [astral-sh/ruff](https://github.com/astral-sh/ruff) and [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/workflows/gha_security.yml) have also adopted Zizmor for security scanning in their repositories.  
Let me know if any …
=> Use Zizmor to Detect Security Vulnerabilities in GitHub Actions Workflows  

renovate.json
Fix an issue causing Renovate not to create PRs.
=> Fix an issue causing Renovate not to create PRs

flexget/components/ftp/ftp_list.py
Currently, the code for `ftp_list` supports both `FTP over TLS` and `PROT P`, but it does not support `TLS session resumption on data connection when using PROT P`.
**The latest version of FileZilla Server is not compatible with FTP clients which does not support `TLS session resumption on data connection when using PROT P`, because it's insecure without this feature.**
Also see:
https://forum.filezilla-project.org/viewtopic.php?p=181629#p181629
https://filezilla-project.org/misc/ftps_connection_stealing_exploit.cpp
https://forum.filezilla-project.org/viewtopic.php?t=56109
=> Fix an issue where the `ftp_list` plugin does not support `TLS session resumption on data connection when using PROT P`

.pre-commit-config.yaml, flexget/api/core/plugins.py, flexget/components/failed/api.py, flexget/components/history/api.py, flexget/components/irc/irc.py, flexget/components/managed_lists/lists/entry_list/api.py, flexget/components/managed_lists/lists/movie_list/api.py, flexget/components/managed_lists/lists/pending_list/api.py, flexget/components/pending_approval/api.py, flexget/components/rejected/api.py, flexget/components/seen/api.py, flexget/components/series/api.py, flexget/components/status/api.py, flexget/log.py, flexget/plugins/clients/transmission.py, flexget/plugins/input/next_sonarr_episodes.py, flexget/plugins/operate/proxy.py, flexget/utils/template.py, pyproject.toml, tests/sftp/test_sftp_server.py, tests/test_download.py, tests/test_misc.py, tests/test_series.py, uv.lock
Some new Ruff rules require manual changes.
=> Bump Ruff to v0.11.6

Dockerfile
I have already tested it locally, so there's no need to continue pinning the Alpine version.
=> Unpin the Alpine version

.github/codecov.yml, docs/_static/custom.css, docs/contributor/Getting started/Development environment setup.rst, docs/contributor/Topic guides/Database.rst, docs/contributor/Topic guides/Plugin schemas.rst, docs/contributor/Topic guides/Running and writing tests.rst
Made a few tweaks to the styling and wording.
=> Minor Improvements to the Documentation

README.rst, pyproject.toml
Add badges for supported Python versions and IRC channel for a quick project overview.
Also, include more PyPI classifiers to improve project discoverability and filtering on the PyPI website.
=> chore(metadata): Add more badges and classifiers
